// Code generated by mockery. DO NOT EDIT.
// Manually extended to match ccvclient.RPCClient (7 methods).

package mocks

import (
	context "context"

	protocol "github.com/stellar/go-stellar-sdk/protocols/rpc"
	mock "github.com/stretchr/testify/mock"
)

// MockRPCClient is an autogenerated mock type for the RPCClient type
type MockRPCClient struct {
	mock.Mock
}

type MockRPCClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRPCClient) EXPECT() *MockRPCClient_Expecter {
	return &MockRPCClient_Expecter{mock: &_m.Mock}
}

// SimulateTransaction provides a mock function with given fields: ctx, req
func (_m *MockRPCClient) SimulateTransaction(ctx context.Context, req protocol.SimulateTransactionRequest) (protocol.SimulateTransactionResponse, error) {
	ret := _m.Called(ctx, req)
	var r0 protocol.SimulateTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.SimulateTransactionRequest) (protocol.SimulateTransactionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.SimulateTransactionRequest) protocol.SimulateTransactionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.SimulateTransactionResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, protocol.SimulateTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SendTransaction provides a mock function with given fields: ctx, req
func (_m *MockRPCClient) SendTransaction(ctx context.Context, req protocol.SendTransactionRequest) (protocol.SendTransactionResponse, error) {
	ret := _m.Called(ctx, req)
	var r0 protocol.SendTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.SendTransactionRequest) (protocol.SendTransactionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.SendTransactionRequest) protocol.SendTransactionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.SendTransactionResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, protocol.SendTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetTransaction provides a mock function with given fields: ctx, req
func (_m *MockRPCClient) GetTransaction(ctx context.Context, req protocol.GetTransactionRequest) (protocol.GetTransactionResponse, error) {
	ret := _m.Called(ctx, req)
	var r0 protocol.GetTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetTransactionRequest) (protocol.GetTransactionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetTransactionRequest) protocol.GetTransactionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.GetTransactionResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, protocol.GetTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetLedgerEntries provides a mock function with given fields: ctx, req
func (_m *MockRPCClient) GetLedgerEntries(ctx context.Context, req protocol.GetLedgerEntriesRequest) (protocol.GetLedgerEntriesResponse, error) {
	ret := _m.Called(ctx, req)
	var r0 protocol.GetLedgerEntriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetLedgerEntriesRequest) (protocol.GetLedgerEntriesResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetLedgerEntriesRequest) protocol.GetLedgerEntriesResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.GetLedgerEntriesResponse)
	}
	if rf, ok := ret.Get(1).(func(context.Context, protocol.GetLedgerEntriesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetEvents provides a mock function with given fields: ctx, req
func (_m *MockRPCClient) GetEvents(ctx context.Context, req protocol.GetEventsRequest) (protocol.GetEventsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 protocol.GetEventsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetEventsRequest) (protocol.GetEventsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetEventsRequest) protocol.GetEventsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.GetEventsResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.GetEventsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRPCClient_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type MockRPCClient_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - req protocol.GetEventsRequest
func (_e *MockRPCClient_Expecter) GetEvents(ctx interface{}, req interface{}) *MockRPCClient_GetEvents_Call {
	return &MockRPCClient_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, req)}
}

func (_c *MockRPCClient_GetEvents_Call) Run(run func(ctx context.Context, req protocol.GetEventsRequest)) *MockRPCClient_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.GetEventsRequest))
	})
	return _c
}

func (_c *MockRPCClient_GetEvents_Call) Return(_a0 protocol.GetEventsResponse, _a1 error) *MockRPCClient_GetEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRPCClient_GetEvents_Call) RunAndReturn(run func(context.Context, protocol.GetEventsRequest) (protocol.GetEventsResponse, error)) *MockRPCClient_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestLedger provides a mock function with given fields: ctx
func (_m *MockRPCClient) GetLatestLedger(ctx context.Context) (protocol.GetLatestLedgerResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestLedger")
	}

	var r0 protocol.GetLatestLedgerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (protocol.GetLatestLedgerResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) protocol.GetLatestLedgerResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(protocol.GetLatestLedgerResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRPCClient_GetLatestLedger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestLedger'
type MockRPCClient_GetLatestLedger_Call struct {
	*mock.Call
}

// GetLatestLedger is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRPCClient_Expecter) GetLatestLedger(ctx interface{}) *MockRPCClient_GetLatestLedger_Call {
	return &MockRPCClient_GetLatestLedger_Call{Call: _e.mock.On("GetLatestLedger", ctx)}
}

func (_c *MockRPCClient_GetLatestLedger_Call) Run(run func(ctx context.Context)) *MockRPCClient_GetLatestLedger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRPCClient_GetLatestLedger_Call) Return(_a0 protocol.GetLatestLedgerResponse, _a1 error) *MockRPCClient_GetLatestLedger_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRPCClient_GetLatestLedger_Call) RunAndReturn(run func(context.Context) (protocol.GetLatestLedgerResponse, error)) *MockRPCClient_GetLatestLedger_Call {
	_c.Call.Return(run)
	return _c
}

// GetLedgers provides a mock function with given fields: ctx, req
func (_m *MockRPCClient) GetLedgers(ctx context.Context, req protocol.GetLedgersRequest) (protocol.GetLedgersResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetLedgers")
	}

	var r0 protocol.GetLedgersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetLedgersRequest) (protocol.GetLedgersResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protocol.GetLedgersRequest) protocol.GetLedgersResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(protocol.GetLedgersResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, protocol.GetLedgersRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRPCClient_GetLedgers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLedgers'
type MockRPCClient_GetLedgers_Call struct {
	*mock.Call
}

// GetLedgers is a helper method to define mock.On call
//   - ctx context.Context
//   - req protocol.GetLedgersRequest
func (_e *MockRPCClient_Expecter) GetLedgers(ctx interface{}, req interface{}) *MockRPCClient_GetLedgers_Call {
	return &MockRPCClient_GetLedgers_Call{Call: _e.mock.On("GetLedgers", ctx, req)}
}

func (_c *MockRPCClient_GetLedgers_Call) Run(run func(ctx context.Context, req protocol.GetLedgersRequest)) *MockRPCClient_GetLedgers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.GetLedgersRequest))
	})
	return _c
}

func (_c *MockRPCClient_GetLedgers_Call) Return(_a0 protocol.GetLedgersResponse, _a1 error) *MockRPCClient_GetLedgers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRPCClient_GetLedgers_Call) RunAndReturn(run func(context.Context, protocol.GetLedgersRequest) (protocol.GetLedgersResponse, error)) *MockRPCClient_GetLedgers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRPCClient creates a new instance of MockRPCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRPCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRPCClient {
	mock := &MockRPCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
