// Code generated by stellar-bindings-generator. DO NOT EDIT.
package cre_mock_forwarder

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// MockForwarderClient provides methods to interact with the MockForwarder contract.
type MockForwarderClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewMockForwarderClient creates a new MockForwarderClient.
func NewMockForwarderClient(invoker bindings.Invoker, contractID string) *MockForwarderClient {
	return &MockForwarderClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *MockForwarderClient) ContractID() string {
	return c.contractID
}

// Report calls the report function on the contract.
func (c *MockForwarderClient) Report(ctx context.Context, transmitter string, receiver string, rawReport []byte, reportContext []byte, signatures []Ed25519Signature) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(transmitter),
		scval.AddressToScVal(receiver),
		scval.BytesToScVal(rawReport),
		scval.BytesToScVal(reportContext),
		scval.StructSliceToScVal(signatures),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "report", args)
	if err != nil {
		return fmt.Errorf("failed to call report: %w", err)
	}

	_ = result // void return
	return nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *MockForwarderClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetTransmissionInfo calls the get_transmission_info function on the contract.
func (c *MockForwarderClient) GetTransmissionInfo(ctx context.Context, receiver string, workflowExecutionId [32]byte, reportId [2]byte) (*TransmissionInfo, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(receiver),
		scval.Bytes32ToScVal(workflowExecutionId),
		scval.Bytes2ToScVal(reportId),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_transmission_info", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_transmission_info: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_transmission_info")
	}

	return TransmissionInfoFromScVal(*result)
}

// WaitForReportProcessedEvent waits for a ReportProcessedEvent event.
func (c *MockForwarderClient) WaitForReportProcessedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ReportProcessedEvent) bool) (*ReportProcessedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ReportProcessedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseReportProcessedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseReportProcessedEvent(e protocolrpc.EventInfo) (*ReportProcessedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ReportProcessedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	if len(e.TopicXDR) > 1 {
		var tv xdr.ScVal
		if xdr.SafeUnmarshalBase64(e.TopicXDR[1], &tv) == nil {
			if v, err := scval.AddressFromScVal(tv); err == nil {
				result.Receiver = v
			}
		}
	}

	if len(e.TopicXDR) > 2 {
		var tv xdr.ScVal
		if xdr.SafeUnmarshalBase64(e.TopicXDR[2], &tv) == nil {
			if v, err := scval.Bytes32FromScVal(tv); err == nil {
				result.WorkflowExecutionId = v
			}
		}
	}

	if len(e.TopicXDR) > 3 {
		var tv xdr.ScVal
		if xdr.SafeUnmarshalBase64(e.TopicXDR[3], &tv) == nil {
			if v, err := scval.Bytes2FromScVal(tv); err == nil {
				result.ReportId = v
			}
		}
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "success":
			v, ok := entry.Val.GetB()
			if ok {
				result.Success = v
			}
		}
	}

	return result, nil
}
