// Code generated by stellar-bindings-generator. DO NOT EDIT.
package data_feeds_cache

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// DataFeedsCacheClient provides methods to interact with the DataFeedsCache contract.
type DataFeedsCacheClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewDataFeedsCacheClient creates a new DataFeedsCacheClient.
func NewDataFeedsCacheClient(invoker bindings.Invoker, contractID string) *DataFeedsCacheClient {
	return &DataFeedsCacheClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *DataFeedsCacheClient) ContractID() string {
	return c.contractID
}

// Upgrade builds a call to the upgrade contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) Upgrade(newWasmHash WasmHash) *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{
		scval.MustToScVal(newWasmHash.ToScVal()),
	}
	return bindings.NewCall(c.invoker, c.contractID, "upgrade", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// Version builds a call to the version contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) Version() *bindings.Call[uint32] {
	args := []xdr.ScVal{}
	return bindings.NewCall(c.invoker, c.contractID, "version", args, func(result *xdr.ScVal) (uint32, error) {
		if result == nil {
			return 0, fmt.Errorf("no return value from version")
		}
		v, ok := result.GetU32()
		if !ok {
			return 0, fmt.Errorf("expected u32 return type")
		}
		return uint32(v), nil
	})
}

// Decimals builds a call to the decimals contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) Decimals(dataId DataId) *bindings.Call[uint32] {
	args := []xdr.ScVal{
		scval.MustToScVal(dataId.ToScVal()),
	}
	return bindings.NewCall(c.invoker, c.contractID, "decimals", args, func(result *xdr.ScVal) (uint32, error) {
		if result == nil {
			return 0, fmt.Errorf("no return value from decimals")
		}
		v, ok := result.GetU32()
		if !ok {
			return 0, fmt.Errorf("expected u32 return type")
		}
		return uint32(v), nil
	})
}

// GetOwner builds a call to the get_owner contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) GetOwner() *bindings.Call[*string] {
	args := []xdr.ScVal{}
	return bindings.NewCall(c.invoker, c.contractID, "get_owner", args, func(result *xdr.ScVal) (*string, error) {
		if result == nil {
			return nil, fmt.Errorf("no return value from get_owner")
		}
		v, err := scval.OptionalAddressFromScVal(*result)
		if err != nil {
			return nil, err
		}
		return v, nil
	})
}

// GetRound builds a call to the get_round contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) GetRound(dataId DataId, roundId uint64) *bindings.Call[*RoundData] {
	args := []xdr.ScVal{
		scval.MustToScVal(dataId.ToScVal()),
		scval.Uint64ToScVal(roundId),
	}
	return bindings.NewCall(c.invoker, c.contractID, "get_round", args, func(result *xdr.ScVal) (*RoundData, error) {
		if result == nil {
			return nil, fmt.Errorf("no return value from get_round")
		}
		if result.Type == xdr.ScValTypeScvVoid {
			return nil, nil
		}
		v, err := RoundDataFromScVal(*result)
		if err != nil {
			return nil, err
		}
		return v, nil
	})
}

// OnReport builds a call to the on_report contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) OnReport(sender string, metadata []byte, report []byte) *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{
		scval.AddressToScVal(sender),
		scval.BytesToScVal(metadata),
		scval.BytesToScVal(report),
	}
	return bindings.NewCall(c.invoker, c.contractID, "on_report", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// FindRound builds a call to the find_round contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) FindRound(dataId DataId, timestamp uint64, bound Bound) *bindings.Call[*RoundData] {
	args := []xdr.ScVal{
		scval.MustToScVal(dataId.ToScVal()),
		scval.Uint64ToScVal(timestamp),
		scval.MustToScVal(bound.ToScVal()),
	}
	return bindings.NewCall(c.invoker, c.contractID, "find_round", args, func(result *xdr.ScVal) (*RoundData, error) {
		if result == nil {
			return nil, fmt.Errorf("no return value from find_round")
		}
		if result.Type == xdr.ScValTypeScvVoid {
			return nil, nil
		}
		v, err := RoundDataFromScVal(*result)
		if err != nil {
			return nil, err
		}
		return v, nil
	})
}

// Description builds a call to the description contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) Description(dataId DataId) *bindings.Call[string] {
	args := []xdr.ScVal{
		scval.MustToScVal(dataId.ToScVal()),
	}
	return bindings.NewCall(c.invoker, c.contractID, "description", args, func(result *xdr.ScVal) (string, error) {
		if result == nil {
			return "", fmt.Errorf("no return value from description")
		}
		return scval.StringFromScVal(*result)
	})
}

// RoundRange builds a call to the round_range contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) RoundRange(dataId DataId, from uint64, to uint64) *bindings.Call[[]RoundData] {
	args := []xdr.ScVal{
		scval.MustToScVal(dataId.ToScVal()),
		scval.Uint64ToScVal(from),
		scval.Uint64ToScVal(to),
	}
	return bindings.NewCall(c.invoker, c.contractID, "round_range", args, func(result *xdr.ScVal) ([]RoundData, error) {
		if result == nil {
			return nil, fmt.Errorf("no return value from round_range")
		}
		vec, ok := result.GetVec()
		if !ok || vec == nil {
			return nil, fmt.Errorf("expected vec return type")
		}
		out := make([]RoundData, len(*vec))
		for i, item := range *vec {
			v, err := RoundDataFromScVal(item)
			if err != nil {
				return nil, err
			}
			out[i] = *v
		}
		return out, nil
	})
}

// LatestRound builds a call to the latest_round contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) LatestRound(dataId DataId) *bindings.Call[*RoundData] {
	args := []xdr.ScVal{
		scval.MustToScVal(dataId.ToScVal()),
	}
	return bindings.NewCall(c.invoker, c.contractID, "latest_round", args, func(result *xdr.ScVal) (*RoundData, error) {
		if result == nil {
			return nil, fmt.Errorf("no return value from latest_round")
		}
		if result.Type == xdr.ScValTypeScvVoid {
			return nil, nil
		}
		v, err := RoundDataFromScVal(*result)
		if err != nil {
			return nil, err
		}
		return v, nil
	})
}

// IsFeedAdmin builds a call to the is_feed_admin contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) IsFeedAdmin(admin string) *bindings.Call[bool] {
	args := []xdr.ScVal{
		scval.AddressToScVal(admin),
	}
	return bindings.NewCall(c.invoker, c.contractID, "is_feed_admin", args, func(result *xdr.ScVal) (bool, error) {
		if result == nil {
			return false, fmt.Errorf("no return value from is_feed_admin")
		}
		v, ok := result.GetB()
		if !ok {
			return false, fmt.Errorf("expected bool return type")
		}
		return v, nil
	})
}

// AddFeedAdmin builds a call to the add_feed_admin contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) AddFeedAdmin(newAdmin string) *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{
		scval.AddressToScVal(newAdmin),
	}
	return bindings.NewCall(c.invoker, c.contractID, "add_feed_admin", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// HasPermission builds a call to the has_permission contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) HasPermission(dataId DataId, sender string, workflowOwner WorkflowOwner, workflowName WorkflowName) *bindings.Call[bool] {
	args := []xdr.ScVal{
		scval.MustToScVal(dataId.ToScVal()),
		scval.AddressToScVal(sender),
		scval.MustToScVal(workflowOwner.ToScVal()),
		scval.MustToScVal(workflowName.ToScVal()),
	}
	return bindings.NewCall(c.invoker, c.contractID, "has_permission", args, func(result *xdr.ScVal) (bool, error) {
		if result == nil {
			return false, fmt.Errorf("no return value from has_permission")
		}
		v, ok := result.GetB()
		if !ok {
			return false, fmt.Errorf("expected bool return type")
		}
		return v, nil
	})
}

// RecoverTokens builds a call to the recover_tokens contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) RecoverTokens(token string, to string, amount int64) *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
		scval.AddressToScVal(to),
		scval.I128ToScVal(amount),
	}
	return bindings.NewCall(c.invoker, c.contractID, "recover_tokens", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// AcceptOwnership builds a call to the accept_ownership contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) AcceptOwnership() *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{}
	return bindings.NewCall(c.invoker, c.contractID, "accept_ownership", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// SetFeedConfigs builds a call to the set_feed_configs contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) SetFeedConfigs(admin string, entries []FeedConfigEntry) *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{
		scval.AddressToScVal(admin),
		scval.StructSliceToScVal(entries),
	}
	return bindings.NewCall(c.invoker, c.contractID, "set_feed_configs", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// TypeAndVersion builds a call to the type_and_version contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) TypeAndVersion() *bindings.Call[string] {
	args := []xdr.ScVal{}
	return bindings.NewCall(c.invoker, c.contractID, "type_and_version", args, func(result *xdr.ScVal) (string, error) {
		if result == nil {
			return "", fmt.Errorf("no return value from type_and_version")
		}
		return scval.StringFromScVal(*result)
	})
}

// RemoveFeedAdmin builds a call to the remove_feed_admin contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) RemoveFeedAdmin(admin string) *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{
		scval.AddressToScVal(admin),
	}
	return bindings.NewCall(c.invoker, c.contractID, "remove_feed_admin", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// RenounceOwnership builds a call to the renounce_ownership contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) RenounceOwnership() *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{}
	return bindings.NewCall(c.invoker, c.contractID, "renounce_ownership", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// TransferOwnership builds a call to the transfer_ownership contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) TransferOwnership(newOwner string, liveUntilLedger uint32) *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
		scval.Uint32ToScVal(liveUntilLedger),
	}
	return bindings.NewCall(c.invoker, c.contractID, "transfer_ownership", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// RemoveFeedConfigs builds a call to the remove_feed_configs contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) RemoveFeedConfigs(admin string, dataIds []DataId) *bindings.Call[bindings.Void] {
	args := []xdr.ScVal{
		scval.AddressToScVal(admin),
		scval.StructSliceToScVal(dataIds),
	}
	return bindings.NewCall(c.invoker, c.contractID, "remove_feed_configs", args, func(result *xdr.ScVal) (bindings.Void, error) {
		_ = result // void return
		return bindings.Void{}, nil
	})
}

// GetFeedPermissions builds a call to the get_feed_permissions contract function.
// Execute it with Result (free simulation, state changes discarded) or
// SignAndSend (fee-paying transaction).
func (c *DataFeedsCacheClient) GetFeedPermissions(dataId DataId) *bindings.Call[[]WorkflowPermission] {
	args := []xdr.ScVal{
		scval.MustToScVal(dataId.ToScVal()),
	}
	return bindings.NewCall(c.invoker, c.contractID, "get_feed_permissions", args, func(result *xdr.ScVal) ([]WorkflowPermission, error) {
		if result == nil {
			return nil, fmt.Errorf("no return value from get_feed_permissions")
		}
		vec, ok := result.GetVec()
		if !ok || vec == nil {
			return nil, fmt.Errorf("expected vec return type")
		}
		out := make([]WorkflowPermission, len(*vec))
		for i, item := range *vec {
			v, err := WorkflowPermissionFromScVal(item)
			if err != nil {
				return nil, err
			}
			out[i] = *v
		}
		return out, nil
	})
}

// WaitForFeedUpdated waits for a FeedUpdated event.
func (c *DataFeedsCacheClient) WaitForFeedUpdated(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FeedUpdated) bool) (*FeedUpdated, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FeedUpdatedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFeedUpdated(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFeedUpdated(e protocolrpc.EventInfo) (*FeedUpdated, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FeedUpdated{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data_id":
			v, err := DataIdFromScVal(entry.Val)
			if err == nil {
				result.DataId = *v
			}
		case "round_id":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RoundId = v
			}
		case "timestamp":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.Timestamp = v
			}
		case "answer":
			v, err := scval.I256FromScVal(entry.Val)
			if err == nil {
				result.Answer = v
			}
		case "ledger_seq":
			v, ok := entry.Val.GetU32()
			if ok {
				result.LedgerSeq = uint32(v)
			}
		case "primary":
			v, ok := entry.Val.GetB()
			if ok {
				result.Primary = v
			}
		}
	}

	return result, nil
}

// WaitForStaleReport waits for a StaleReport event.
func (c *DataFeedsCacheClient) WaitForStaleReport(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*StaleReport) bool) (*StaleReport, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{StaleReportTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseStaleReport(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseStaleReport(e protocolrpc.EventInfo) (*StaleReport, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &StaleReport{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data_id":
			v, err := DataIdFromScVal(entry.Val)
			if err == nil {
				result.DataId = *v
			}
		case "report_ts":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.ReportTs = v
			}
		case "stored_ts":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.StoredTs = v
			}
		}
	}

	return result, nil
}

// WaitForFeedConfigSet waits for a FeedConfigSet event.
func (c *DataFeedsCacheClient) WaitForFeedConfigSet(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FeedConfigSet) bool) (*FeedConfigSet, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FeedConfigSetTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFeedConfigSet(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFeedConfigSet(e protocolrpc.EventInfo) (*FeedConfigSet, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FeedConfigSet{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data_id":
			v, err := DataIdFromScVal(entry.Val)
			if err == nil {
				result.DataId = *v
			}
		case "decimals":
			v, ok := entry.Val.GetU32()
			if ok {
				result.Decimals = uint32(v)
			}
		case "description":
			v, err := scval.StringFromScVal(entry.Val)
			if err == nil {
				result.Description = v
			}
		case "workflow_permissions":
			vec, ok := entry.Val.GetVec()
			if ok && vec != nil {
				parsed := make([]WorkflowPermission, 0, len(*vec))
				for _, item := range *vec {
					v, err := WorkflowPermissionFromScVal(item)
					if err == nil {
						parsed = append(parsed, *v)
					}
				}
				result.WorkflowPermissions = parsed
			}
		}
	}

	return result, nil
}

// WaitForFeedAdminAdded waits for a FeedAdminAdded event.
func (c *DataFeedsCacheClient) WaitForFeedAdminAdded(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FeedAdminAdded) bool) (*FeedAdminAdded, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FeedAdminAddedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFeedAdminAdded(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFeedAdminAdded(e protocolrpc.EventInfo) (*FeedAdminAdded, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FeedAdminAdded{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "admin":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Admin = v
			}
		}
	}

	return result, nil
}

// WaitForFeedAdminRemoved waits for a FeedAdminRemoved event.
func (c *DataFeedsCacheClient) WaitForFeedAdminRemoved(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FeedAdminRemoved) bool) (*FeedAdminRemoved, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FeedAdminRemovedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFeedAdminRemoved(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFeedAdminRemoved(e protocolrpc.EventInfo) (*FeedAdminRemoved, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FeedAdminRemoved{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "admin":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Admin = v
			}
		}
	}

	return result, nil
}

// WaitForFeedConfigRemoved waits for a FeedConfigRemoved event.
func (c *DataFeedsCacheClient) WaitForFeedConfigRemoved(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FeedConfigRemoved) bool) (*FeedConfigRemoved, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FeedConfigRemovedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFeedConfigRemoved(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFeedConfigRemoved(e protocolrpc.EventInfo) (*FeedConfigRemoved, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FeedConfigRemoved{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data_id":
			v, err := DataIdFromScVal(entry.Val)
			if err == nil {
				result.DataId = *v
			}
		}
	}

	return result, nil
}

// WaitForInvalidUpdatePermission waits for a InvalidUpdatePermission event.
func (c *DataFeedsCacheClient) WaitForInvalidUpdatePermission(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*InvalidUpdatePermission) bool) (*InvalidUpdatePermission, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{InvalidUpdatePermissionTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseInvalidUpdatePermission(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseInvalidUpdatePermission(e protocolrpc.EventInfo) (*InvalidUpdatePermission, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &InvalidUpdatePermission{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data_id":
			v, err := DataIdFromScVal(entry.Val)
			if err == nil {
				result.DataId = *v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "workflow_owner":
			v, err := WorkflowOwnerFromScVal(entry.Val)
			if err == nil {
				result.WorkflowOwner = *v
			}
		case "workflow_name":
			v, err := WorkflowNameFromScVal(entry.Val)
			if err == nil {
				result.WorkflowName = *v
			}
		}
	}

	return result, nil
}

// WaitForUpgraded waits for a Upgraded event.
func (c *DataFeedsCacheClient) WaitForUpgraded(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*Upgraded) bool) (*Upgraded, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{UpgradedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseUpgraded(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseUpgraded(e protocolrpc.EventInfo) (*Upgraded, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &Upgraded{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "new_wasm_hash":
			v, err := WasmHashFromScVal(entry.Val)
			if err == nil {
				result.NewWasmHash = *v
			}
		}
	}

	return result, nil
}

// WaitForTokenRecovered waits for a TokenRecovered event.
func (c *DataFeedsCacheClient) WaitForTokenRecovered(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*TokenRecovered) bool) (*TokenRecovered, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{TokenRecoveredTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseTokenRecovered(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseTokenRecovered(e protocolrpc.EventInfo) (*TokenRecovered, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &TokenRecovered{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Token = v
			}
		case "to":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.To = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransfer waits for a OwnershipTransfer event.
func (c *DataFeedsCacheClient) WaitForOwnershipTransfer(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransfer) bool) (*OwnershipTransfer, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipTransfer(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipTransfer(e protocolrpc.EventInfo) (*OwnershipTransfer, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransfer{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "old_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.OldOwner = v
			}
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		case "live_until_ledger":
			v, ok := entry.Val.GetU32()
			if ok {
				result.LiveUntilLedger = uint32(v)
			}
		}
	}

	return result, nil
}

// WaitForOwnershipRenounced waits for a OwnershipRenounced event.
func (c *DataFeedsCacheClient) WaitForOwnershipRenounced(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipRenounced) bool) (*OwnershipRenounced, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipRenouncedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipRenounced(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipRenounced(e protocolrpc.EventInfo) (*OwnershipRenounced, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipRenounced{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "old_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.OldOwner = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransferCompleted waits for a OwnershipTransferCompleted event.
func (c *DataFeedsCacheClient) WaitForOwnershipTransferCompleted(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransferCompleted) bool) (*OwnershipTransferCompleted, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferCompletedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipTransferCompleted(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipTransferCompleted(e protocolrpc.EventInfo) (*OwnershipTransferCompleted, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransferCompleted{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		}
	}

	return result, nil
}
