// Code generated by stellar-bindings-generator. DO NOT EDIT.
package fee_quoter

import (
	"context"
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// FeeQuoterClient provides methods to interact with the FeeQuoter contract.
type FeeQuoterClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewFeeQuoterClient creates a new FeeQuoterClient.
func NewFeeQuoterClient(invoker bindings.Invoker, contractID string) *FeeQuoterClient {
	return &FeeQuoterClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *FeeQuoterClient) ContractID() string {
	return c.contractID
}

// Owner calls the owner function on the contract.
func (c *FeeQuoterClient) Owner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// IsOwner calls the is_owner function on the contract.
func (c *FeeQuoterClient) IsOwner(ctx context.Context, addr string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_owner", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_owner: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_owner")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// InitOwner calls the init_owner function on the contract.
func (c *FeeQuoterClient) InitOwner(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call init_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// Initialize calls the initialize function on the contract.
func (c *FeeQuoterClient) Initialize(ctx context.Context, owner string, staticConfig StaticConfig, authorizedCallers []string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
		scval.MustToScVal(staticConfig.ToScVal()),
		scval.AddressSliceToScVal(authorizedCallers),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// RequireOwner calls the require_owner function on the contract.
func (c *FeeQuoterClient) RequireOwner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call require_owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from require_owner")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// SetNewOwner calls the set_new_owner function on the contract.
func (c *FeeQuoterClient) SetNewOwner(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_new_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call set_new_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// UpdatePrices calls the update_prices function on the contract.
func (c *FeeQuoterClient) UpdatePrices(ctx context.Context, updater string, priceUpdates PriceUpdates) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(updater),
		scval.MustToScVal(priceUpdates.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "update_prices", args)
	if err != nil {
		return fmt.Errorf("failed to call update_prices: %w", err)
	}

	_ = result // void return
	return nil
}

// GetFeeTokens calls the get_fee_tokens function on the contract.
func (c *FeeQuoterClient) GetFeeTokens(ctx context.Context) ([]string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_fee_tokens", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_fee_tokens: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_fee_tokens")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]string, len(*vec))
	for i, item := range *vec {
		v, err := scval.AddressFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

// GetMessageFee calls the get_message_fee function on the contract.
func (c *FeeQuoterClient) GetMessageFee(ctx context.Context, destChainSelector uint64, message StellarToAnyMessage) (*MessageFeeResult, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.MustToScVal(message.ToScVal()),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_message_fee", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_message_fee: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_message_fee")
	}

	return MessageFeeResultFromScVal(*result)
}

// GetTokenPrice calls the get_token_price function on the contract.
func (c *FeeQuoterClient) GetTokenPrice(ctx context.Context, token string) (*TimestampedPrice, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_price", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_price: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_price")
	}

	return TimestampedPriceFromScVal(*result)
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *FeeQuoterClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// GetTokenPrices calls the get_token_prices function on the contract.
func (c *FeeQuoterClient) GetTokenPrices(ctx context.Context, tokens []string) ([]TimestampedPrice, error) {
	args := []xdr.ScVal{
		scval.AddressSliceToScVal(tokens),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_prices", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_prices: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_prices")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]TimestampedPrice, len(*vec))
	for i, item := range *vec {
		v, err := TimestampedPriceFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = *v
	}
	return out, nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *FeeQuoterClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetPendingOwner calls the get_pending_owner function on the contract.
func (c *FeeQuoterClient) GetPendingOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pending_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pending_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pending_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// GetStaticConfig calls the get_static_config function on the contract.
func (c *FeeQuoterClient) GetStaticConfig(ctx context.Context) (*StaticConfig, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_static_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_static_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_static_config")
	}

	return StaticConfigFromScVal(*result)
}

// RemoveFeeTokens calls the remove_fee_tokens function on the contract.
func (c *FeeQuoterClient) RemoveFeeTokens(ctx context.Context, tokens []string) error {
	args := []xdr.ScVal{
		scval.AddressSliceToScVal(tokens),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "remove_fee_tokens", args)
	if err != nil {
		return fmt.Errorf("failed to call remove_fee_tokens: %w", err)
	}

	_ = result // void return
	return nil
}

// QuoteGasForExec calls the quote_gas_for_exec function on the contract.
func (c *FeeQuoterClient) QuoteGasForExec(ctx context.Context, destChainSelector uint64, nonCalldataGas uint32, calldataSize uint32, feeToken string) (*GasQuoteResult, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.Uint32ToScVal(nonCalldataGas),
		scval.Uint32ToScVal(calldataSize),
		scval.AddressToScVal(feeToken),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "quote_gas_for_exec", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call quote_gas_for_exec: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from quote_gas_for_exec")
	}

	return GasQuoteResultFromScVal(*result)
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *FeeQuoterClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// ConvertTokenAmount calls the convert_token_amount function on the contract.
func (c *FeeQuoterClient) ConvertTokenAmount(ctx context.Context, fromToken string, fromTokenAmount int64, toToken string) (int64, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(fromToken),
		scval.I128ToScVal(fromTokenAmount),
		scval.AddressToScVal(toToken),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "convert_token_amount", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call convert_token_amount: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from convert_token_amount")
	}

	v, err := scval.I128FromScVal(*result)
	if err != nil {
		return 0, err
	}
	return v, nil
}

// GetAllDestConfigs calls the get_all_dest_configs function on the contract.
func (c *FeeQuoterClient) GetAllDestConfigs(ctx context.Context) ([]uint64, []DestChainConfig, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_all_dest_configs", args)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to call get_all_dest_configs: %w", err)
	}

	if result == nil {
		return nil, nil, fmt.Errorf("no return value from get_all_dest_configs")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, nil, fmt.Errorf("expected vec for tuple return")
	}
	if len(*vec) != 2 {
		return nil, nil, fmt.Errorf("expected 2 elements, got %d", len(*vec))
	}

	v0Vec, ok := (*vec)[0].GetVec()
	if !ok || v0Vec == nil {
		return nil, nil, fmt.Errorf("tuple[0]: expected vec")
	}
	v0 := make([]uint64, len(*v0Vec))
	for i, item := range *v0Vec {
		val, err := scval.Uint64FromScVal(item)
		if err != nil {
			return nil, nil, fmt.Errorf("tuple[0][%d]: %w", i, err)
		}
		v0[i] = val
	}

	v1Vec, ok := (*vec)[1].GetVec()
	if !ok || v1Vec == nil {
		return nil, nil, fmt.Errorf("tuple[1]: expected vec")
	}
	v1 := make([]DestChainConfig, len(*v1Vec))
	for i, item := range *v1Vec {
		val, err := DestChainConfigFromScVal(item)
		if err != nil {
			return nil, nil, fmt.Errorf("tuple[1][%d]: %w", i, err)
		}
		v1[i] = *val
	}

	return v0, v1, nil
}

// GetTokenFeeConfig calls the get_token_fee_config function on the contract.
func (c *FeeQuoterClient) GetTokenFeeConfig(ctx context.Context, destChainSelector uint64, token string) (*TokenTransferFeeConfig, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_fee_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_fee_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_fee_config")
	}

	return TokenTransferFeeConfigFromScVal(*result)
}

// GetDestChainConfig calls the get_dest_chain_config function on the contract.
func (c *FeeQuoterClient) GetDestChainConfig(ctx context.Context, destChainSelector uint64) (*DestChainConfig, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_dest_chain_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_dest_chain_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_dest_chain_config")
	}

	return DestChainConfigFromScVal(*result)
}

// GetTokenTransferFee calls the get_token_transfer_fee function on the contract.
func (c *FeeQuoterClient) GetTokenTransferFee(ctx context.Context, destChainSelector uint64, token string) (*TokenTransferFeeResult, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_transfer_fee", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_transfer_fee: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_transfer_fee")
	}

	return TokenTransferFeeResultFromScVal(*result)
}

// ApplyTokenFeeConfigs calls the apply_token_fee_configs function on the contract.
func (c *FeeQuoterClient) ApplyTokenFeeConfigs(ctx context.Context, configArgs []TokenFeeConfigArgs, removeArgs []TokenFeeConfigRemoveArgs) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(configArgs),
		scval.StructSliceToScVal(removeArgs),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_token_fee_configs", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_token_fee_configs: %w", err)
	}

	_ = result // void return
	return nil
}

// ApplyDestChainConfigs calls the apply_dest_chain_configs function on the contract.
func (c *FeeQuoterClient) ApplyDestChainConfigs(ctx context.Context, configArgs []DestChainConfigArgs) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(configArgs),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_dest_chain_configs", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_dest_chain_configs: %w", err)
	}

	_ = result // void return
	return nil
}

// GetDestChainGasPrice calls the get_dest_chain_gas_price function on the contract.
func (c *FeeQuoterClient) GetDestChainGasPrice(ctx context.Context, destChainSelector uint64) (*TimestampedPrice, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_dest_chain_gas_price", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_dest_chain_gas_price: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_dest_chain_gas_price")
	}

	return TimestampedPriceFromScVal(*result)
}

// CancelOwnershipTransfer calls the cancel_ownership_transfer function on the contract.
func (c *FeeQuoterClient) CancelOwnershipTransfer(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "cancel_ownership_transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call cancel_ownership_transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// GetValidatedTokenPrice calls the get_validated_token_price function on the contract.
func (c *FeeQuoterClient) GetValidatedTokenPrice(ctx context.Context, token string) (scval.U128, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_validated_token_price", args)
	if err != nil {
		return scval.U128{}, fmt.Errorf("failed to call get_validated_token_price: %w", err)
	}

	if result == nil {
		return scval.U128{}, fmt.Errorf("no return value from get_validated_token_price")
	}

	v, err := scval.U128FromScVal(*result)
	if err != nil {
		return scval.U128{}, err
	}
	return v, nil
}
