// Code generated by stellar-bindings-generator. DO NOT EDIT.
package fee_quoter

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// FeeQuoterClient provides methods to interact with the FeeQuoter contract.
type FeeQuoterClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewFeeQuoterClient creates a new FeeQuoterClient.
func NewFeeQuoterClient(invoker bindings.Invoker, contractID string) *FeeQuoterClient {
	return &FeeQuoterClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *FeeQuoterClient) ContractID() string {
	return c.contractID
}

// Owner calls the owner function on the contract.
func (c *FeeQuoterClient) Owner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// IsOwner calls the is_owner function on the contract.
func (c *FeeQuoterClient) IsOwner(ctx context.Context, addr string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_owner", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_owner: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_owner")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// InitOwner calls the init_owner function on the contract.
func (c *FeeQuoterClient) InitOwner(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call init_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// Initialize calls the initialize function on the contract.
func (c *FeeQuoterClient) Initialize(ctx context.Context, owner string, staticConfig StaticConfig, authorizedCallers []string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
		scval.MustToScVal(staticConfig.ToScVal()),
		scval.AddressSliceToScVal(authorizedCallers),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// RequireOwner calls the require_owner function on the contract.
func (c *FeeQuoterClient) RequireOwner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call require_owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from require_owner")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// SetNewOwner calls the set_new_owner function on the contract.
func (c *FeeQuoterClient) SetNewOwner(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_new_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call set_new_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// UpdatePrices calls the update_prices function on the contract.
func (c *FeeQuoterClient) UpdatePrices(ctx context.Context, priceUpdates PriceUpdates) error {
	args := []xdr.ScVal{
		scval.MustToScVal(priceUpdates.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "update_prices", args)
	if err != nil {
		return fmt.Errorf("failed to call update_prices: %w", err)
	}

	_ = result // void return
	return nil
}

// GetFeeTokens calls the get_fee_tokens function on the contract.
func (c *FeeQuoterClient) GetFeeTokens(ctx context.Context) ([]string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_fee_tokens", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_fee_tokens: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_fee_tokens")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]string, len(*vec))
	for i, item := range *vec {
		v, err := scval.AddressFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

// GetMessageFee calls the get_message_fee function on the contract.
func (c *FeeQuoterClient) GetMessageFee(ctx context.Context, destChainSelector uint64, message StellarToAnyMessage) (int64, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.MustToScVal(message.ToScVal()),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_message_fee", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_message_fee: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_message_fee")
	}

	v, err := scval.I128FromScVal(*result)
	if err != nil {
		return 0, err
	}
	return v, nil
}

// GetTokenPrice calls the get_token_price function on the contract.
func (c *FeeQuoterClient) GetTokenPrice(ctx context.Context, token string) (*TimestampedPrice, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_price", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_price: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_price")
	}

	return TimestampedPriceFromScVal(*result)
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *FeeQuoterClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// GetTokenPrices calls the get_token_prices function on the contract.
func (c *FeeQuoterClient) GetTokenPrices(ctx context.Context, tokens []string) ([]TimestampedPrice, error) {
	args := []xdr.ScVal{
		scval.AddressSliceToScVal(tokens),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_prices", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_prices: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_prices")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]TimestampedPrice, len(*vec))
	for i, item := range *vec {
		v, err := TimestampedPriceFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = *v
	}
	return out, nil
}

// GetPendingOwner calls the get_pending_owner function on the contract.
func (c *FeeQuoterClient) GetPendingOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pending_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pending_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pending_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// GetStaticConfig calls the get_static_config function on the contract.
func (c *FeeQuoterClient) GetStaticConfig(ctx context.Context) (*StaticConfig, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_static_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_static_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_static_config")
	}

	return StaticConfigFromScVal(*result)
}

// RemoveFeeTokens calls the remove_fee_tokens function on the contract.
func (c *FeeQuoterClient) RemoveFeeTokens(ctx context.Context, tokens []string) error {
	args := []xdr.ScVal{
		scval.AddressSliceToScVal(tokens),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "remove_fee_tokens", args)
	if err != nil {
		return fmt.Errorf("failed to call remove_fee_tokens: %w", err)
	}

	_ = result // void return
	return nil
}

// QuoteGasForExec calls the quote_gas_for_exec function on the contract.
func (c *FeeQuoterClient) QuoteGasForExec(ctx context.Context, destChainSelector uint64, nonCalldataGas uint32, calldataSize uint32, feeToken string) (*GasQuoteResult, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.Uint32ToScVal(nonCalldataGas),
		scval.Uint32ToScVal(calldataSize),
		scval.AddressToScVal(feeToken),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "quote_gas_for_exec", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call quote_gas_for_exec: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from quote_gas_for_exec")
	}

	return GasQuoteResultFromScVal(*result)
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *FeeQuoterClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// ConvertTokenAmount calls the convert_token_amount function on the contract.
func (c *FeeQuoterClient) ConvertTokenAmount(ctx context.Context, fromToken string, fromTokenAmount int64, toToken string) (int64, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(fromToken),
		scval.I128ToScVal(fromTokenAmount),
		scval.AddressToScVal(toToken),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "convert_token_amount", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call convert_token_amount: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from convert_token_amount")
	}

	v, err := scval.I128FromScVal(*result)
	if err != nil {
		return 0, err
	}
	return v, nil
}

// GetAllDestConfigs calls the get_all_dest_configs function on the contract.
func (c *FeeQuoterClient) GetAllDestConfigs(ctx context.Context) ([]uint64, []DestChainConfig, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_all_dest_configs", args)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to call get_all_dest_configs: %w", err)
	}

	if result == nil {
		return nil, nil, fmt.Errorf("no return value from get_all_dest_configs")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, nil, fmt.Errorf("expected vec for tuple return")
	}
	if len(*vec) != 2 {
		return nil, nil, fmt.Errorf("expected 2 elements, got %d", len(*vec))
	}

	v0Vec, ok := (*vec)[0].GetVec()
	if !ok || v0Vec == nil {
		return nil, nil, fmt.Errorf("tuple[0]: expected vec")
	}
	v0 := make([]uint64, len(*v0Vec))
	for i, item := range *v0Vec {
		val, err := scval.Uint64FromScVal(item)
		if err != nil {
			return nil, nil, fmt.Errorf("tuple[0][%d]: %w", i, err)
		}
		v0[i] = val
	}

	v1Vec, ok := (*vec)[1].GetVec()
	if !ok || v1Vec == nil {
		return nil, nil, fmt.Errorf("tuple[1]: expected vec")
	}
	v1 := make([]DestChainConfig, len(*v1Vec))
	for i, item := range *v1Vec {
		val, err := DestChainConfigFromScVal(item)
		if err != nil {
			return nil, nil, fmt.Errorf("tuple[1][%d]: %w", i, err)
		}
		v1[i] = *val
	}

	return v0, v1, nil
}

// GetTokenFeeConfig calls the get_token_fee_config function on the contract.
func (c *FeeQuoterClient) GetTokenFeeConfig(ctx context.Context, destChainSelector uint64, token string) (*TokenTransferFeeConfig, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_fee_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_fee_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_fee_config")
	}

	return TokenTransferFeeConfigFromScVal(*result)
}

// GetDestChainConfig calls the get_dest_chain_config function on the contract.
func (c *FeeQuoterClient) GetDestChainConfig(ctx context.Context, destChainSelector uint64) (*DestChainConfig, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_dest_chain_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_dest_chain_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_dest_chain_config")
	}

	return DestChainConfigFromScVal(*result)
}

// GetTokenTransferFee calls the get_token_transfer_fee function on the contract.
func (c *FeeQuoterClient) GetTokenTransferFee(ctx context.Context, destChainSelector uint64, token string) (*TokenTransferFeeResult, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_transfer_fee", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_transfer_fee: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_transfer_fee")
	}

	return TokenTransferFeeResultFromScVal(*result)
}

// ApplyTokenFeeConfigs calls the apply_token_fee_configs function on the contract.
func (c *FeeQuoterClient) ApplyTokenFeeConfigs(ctx context.Context, configArgs []TokenFeeConfigArgs, removeArgs []TokenFeeConfigRemoveArgs) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(configArgs),
		scval.StructSliceToScVal(removeArgs),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_token_fee_configs", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_token_fee_configs: %w", err)
	}

	_ = result // void return
	return nil
}

// ApplyDestChainConfigs calls the apply_dest_chain_configs function on the contract.
func (c *FeeQuoterClient) ApplyDestChainConfigs(ctx context.Context, configArgs []DestChainConfigArgs) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(configArgs),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_dest_chain_configs", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_dest_chain_configs: %w", err)
	}

	_ = result // void return
	return nil
}

// GetDestChainGasPrice calls the get_dest_chain_gas_price function on the contract.
func (c *FeeQuoterClient) GetDestChainGasPrice(ctx context.Context, destChainSelector uint64) (*TimestampedPrice, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_dest_chain_gas_price", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_dest_chain_gas_price: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_dest_chain_gas_price")
	}

	return TimestampedPriceFromScVal(*result)
}

// CancelOwnershipTransfer calls the cancel_ownership_transfer function on the contract.
func (c *FeeQuoterClient) CancelOwnershipTransfer(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "cancel_ownership_transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call cancel_ownership_transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// GetValidatedTokenPrice calls the get_validated_token_price function on the contract.
func (c *FeeQuoterClient) GetValidatedTokenPrice(ctx context.Context, token string) (scval.U128, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_validated_token_price", args)
	if err != nil {
		return scval.U128{}, fmt.Errorf("failed to call get_validated_token_price: %w", err)
	}

	if result == nil {
		return scval.U128{}, fmt.Errorf("no return value from get_validated_token_price")
	}

	v, err := scval.U128FromScVal(*result)
	if err != nil {
		return scval.U128{}, err
	}
	return v, nil
}

// WaitForRoleGrantedEvent waits for a RoleGrantedEvent event.
func (c *FeeQuoterClient) WaitForRoleGrantedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RoleGrantedEvent) bool) (*RoleGrantedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RoleGrantedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseRoleGrantedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseRoleGrantedEvent(e protocolrpc.EventInfo) (*RoleGrantedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RoleGrantedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "role":
			v, err := scval.SymbolFromScVal(entry.Val)
			if err == nil {
				result.Role = v
			}
		case "account":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Account = v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		}
	}

	return result, nil
}

// WaitForRoleRevokedEvent waits for a RoleRevokedEvent event.
func (c *FeeQuoterClient) WaitForRoleRevokedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RoleRevokedEvent) bool) (*RoleRevokedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RoleRevokedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseRoleRevokedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseRoleRevokedEvent(e protocolrpc.EventInfo) (*RoleRevokedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RoleRevokedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "role":
			v, err := scval.SymbolFromScVal(entry.Val)
			if err == nil {
				result.Role = v
			}
		case "account":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Account = v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerAddedEvent waits for a AuthorizedCallerAddedEvent event.
func (c *FeeQuoterClient) WaitForAuthorizedCallerAddedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerAddedEvent) bool) (*AuthorizedCallerAddedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerAddedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseAuthorizedCallerAddedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseAuthorizedCallerAddedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerAddedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerAddedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerRemovedEvent waits for a AuthorizedCallerRemovedEvent event.
func (c *FeeQuoterClient) WaitForAuthorizedCallerRemovedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerRemovedEvent) bool) (*AuthorizedCallerRemovedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerRemovedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseAuthorizedCallerRemovedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseAuthorizedCallerRemovedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerRemovedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerRemovedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransferStartedEvent waits for a OwnershipTransferStartedEvent event.
func (c *FeeQuoterClient) WaitForOwnershipTransferStartedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransferStartedEvent) bool) (*OwnershipTransferStartedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferStartedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseOwnershipTransferStartedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseOwnershipTransferStartedEvent(e protocolrpc.EventInfo) (*OwnershipTransferStartedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransferStartedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "previous_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.PreviousOwner = v
			}
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		}
	}

	return result, nil
}

// WaitForFeeTokenAddedEvent waits for a FeeTokenAddedEvent event.
func (c *FeeQuoterClient) WaitForFeeTokenAddedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FeeTokenAddedEvent) bool) (*FeeTokenAddedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FeeTokenAddedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseFeeTokenAddedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseFeeTokenAddedEvent(e protocolrpc.EventInfo) (*FeeTokenAddedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FeeTokenAddedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "fee_token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.FeeToken = v
			}
		}
	}

	return result, nil
}

// WaitForDestChainAddedEvent waits for a DestChainAddedEvent event.
func (c *FeeQuoterClient) WaitForDestChainAddedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*DestChainAddedEvent) bool) (*DestChainAddedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{DestChainAddedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseDestChainAddedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseDestChainAddedEvent(e protocolrpc.EventInfo) (*DestChainAddedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &DestChainAddedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.DestChainSelector = v
			}
		case "is_enabled":
			// TODO: parse complex type
		case "max_data_bytes":
			// TODO: parse complex type
		}
	}

	return result, nil
}

// WaitForFeeTokenRemovedEvent waits for a FeeTokenRemovedEvent event.
func (c *FeeQuoterClient) WaitForFeeTokenRemovedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FeeTokenRemovedEvent) bool) (*FeeTokenRemovedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FeeTokenRemovedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseFeeTokenRemovedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseFeeTokenRemovedEvent(e protocolrpc.EventInfo) (*FeeTokenRemovedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FeeTokenRemovedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "fee_token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.FeeToken = v
			}
		}
	}

	return result, nil
}

// WaitForUsdPerTokenUpdatedEvent waits for a UsdPerTokenUpdatedEvent event.
func (c *FeeQuoterClient) WaitForUsdPerTokenUpdatedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*UsdPerTokenUpdatedEvent) bool) (*UsdPerTokenUpdatedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{UsdPerTokenUpdatedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseUsdPerTokenUpdatedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseUsdPerTokenUpdatedEvent(e protocolrpc.EventInfo) (*UsdPerTokenUpdatedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &UsdPerTokenUpdatedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Token = v
			}
		case "value":
			v, err := scval.U128FromScVal(entry.Val)
			if err == nil {
				result.Value = v
			}
		case "timestamp":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.Timestamp = v
			}
		}
	}

	return result, nil
}

// WaitForUsdPerUnitGasUpdatedEvent waits for a UsdPerUnitGasUpdatedEvent event.
func (c *FeeQuoterClient) WaitForUsdPerUnitGasUpdatedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*UsdPerUnitGasUpdatedEvent) bool) (*UsdPerUnitGasUpdatedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{UsdPerUnitGasUpdatedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseUsdPerUnitGasUpdatedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseUsdPerUnitGasUpdatedEvent(e protocolrpc.EventInfo) (*UsdPerUnitGasUpdatedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &UsdPerUnitGasUpdatedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.DestChainSelector = v
			}
		case "value":
			v, err := scval.U128FromScVal(entry.Val)
			if err == nil {
				result.Value = v
			}
		case "timestamp":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.Timestamp = v
			}
		}
	}

	return result, nil
}

// WaitForTokenFeeConfigDeletedEvent waits for a TokenFeeConfigDeletedEvent event.
func (c *FeeQuoterClient) WaitForTokenFeeConfigDeletedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*TokenFeeConfigDeletedEvent) bool) (*TokenFeeConfigDeletedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{TokenFeeConfigDeletedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseTokenFeeConfigDeletedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseTokenFeeConfigDeletedEvent(e protocolrpc.EventInfo) (*TokenFeeConfigDeletedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &TokenFeeConfigDeletedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.DestChainSelector = v
			}
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Token = v
			}
		}
	}

	return result, nil
}

// WaitForTokenFeeConfigUpdatedEvent waits for a TokenFeeConfigUpdatedEvent event.
func (c *FeeQuoterClient) WaitForTokenFeeConfigUpdatedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*TokenFeeConfigUpdatedEvent) bool) (*TokenFeeConfigUpdatedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{TokenFeeConfigUpdatedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseTokenFeeConfigUpdatedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseTokenFeeConfigUpdatedEvent(e protocolrpc.EventInfo) (*TokenFeeConfigUpdatedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &TokenFeeConfigUpdatedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.DestChainSelector = v
			}
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Token = v
			}
		case "fee_usd_cents":
			// TODO: parse complex type
		case "dest_gas_overhead":
			// TODO: parse complex type
		case "dest_bytes_overhead":
			// TODO: parse complex type
		}
	}

	return result, nil
}

// WaitForDestChainConfigUpdatedEvent waits for a DestChainConfigUpdatedEvent event.
func (c *FeeQuoterClient) WaitForDestChainConfigUpdatedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*DestChainConfigUpdatedEvent) bool) (*DestChainConfigUpdatedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{DestChainConfigUpdatedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := parseDestChainConfigUpdatedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func parseDestChainConfigUpdatedEvent(e protocolrpc.EventInfo) (*DestChainConfigUpdatedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &DestChainConfigUpdatedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.DestChainSelector = v
			}
		case "is_enabled":
			// TODO: parse complex type
		case "max_data_bytes":
			// TODO: parse complex type
		}
	}

	return result, nil
}
