// Code generated by stellar-bindings-generator. DO NOT EDIT.
package fee_quoter

import (
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// TokenAmount represents the TokenAmount struct from the contract.
type TokenAmount struct {
	Amount int64
	Token  string
}

// ToScVal converts TokenAmount to an xdr.ScVal for contract calls.
func (s TokenAmount) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"amount": scval.I128ToScVal(s.Amount),
		"token":  scval.AddressToScVal(s.Token),
	})
}

// TokenAmountFromScVal parses an xdr.ScVal into TokenAmount.
func TokenAmountFromScVal(val xdr.ScVal) (*TokenAmount, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenAmount{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("amount: %w", err)
			}
			result.Amount = v
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("token: %w", err)
			}
			result.Token = v
		}
	}

	return result, nil
}

// StellarToAnyMessage represents the StellarToAnyMessage struct from the contract.
type StellarToAnyMessage struct {
	Data         []byte
	ExtraArgs    []byte
	FeeToken     string
	Receiver     []byte
	TokenAmounts []TokenAmount
}

// ToScVal converts StellarToAnyMessage to an xdr.ScVal for contract calls.
func (s StellarToAnyMessage) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"data":          scval.BytesToScVal(s.Data),
		"extra_args":    scval.BytesToScVal(s.ExtraArgs),
		"fee_token":     scval.AddressToScVal(s.FeeToken),
		"receiver":      scval.BytesToScVal(s.Receiver),
		"token_amounts": scval.StructSliceToScVal(s.TokenAmounts),
	})
}

// StellarToAnyMessageFromScVal parses an xdr.ScVal into StellarToAnyMessage.
func StellarToAnyMessageFromScVal(val xdr.ScVal) (*StellarToAnyMessage, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &StellarToAnyMessage{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("data is not bytes")
			}
			result.Data = []byte(v)
		case "extra_args":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("extra_args is not bytes")
			}
			result.ExtraArgs = []byte(v)
		case "fee_token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("fee_token: %w", err)
			}
			result.FeeToken = v
		case "receiver":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("receiver is not bytes")
			}
			result.Receiver = []byte(v)
		case "token_amounts":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("token_amounts is not a vec")
			}
			result.TokenAmounts = make([]TokenAmount, len(*vec))
			for i, item := range *vec {
				v, err := TokenAmountFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.TokenAmounts[i] = *v
			}
		}
	}

	return result, nil
}

// AnyToStellarMessage represents the AnyToStellarMessage struct from the contract.
type AnyToStellarMessage struct {
	Placeholder uint64
}

// ToScVal converts AnyToStellarMessage to an xdr.ScVal for contract calls.
func (s AnyToStellarMessage) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"placeholder": scval.Uint64ToScVal(s.Placeholder),
	})
}

// AnyToStellarMessageFromScVal parses an xdr.ScVal into AnyToStellarMessage.
func AnyToStellarMessageFromScVal(val xdr.ScVal) (*AnyToStellarMessage, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &AnyToStellarMessage{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "placeholder":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("placeholder: %w", err)
			}
			result.Placeholder = v
		}
	}

	return result, nil
}

// PriceUpdates represents the PriceUpdates struct from the contract.
type PriceUpdates struct {
	GasPriceUpdates   []GasPriceUpdate
	TokenPriceUpdates []TokenPriceUpdate
}

// ToScVal converts PriceUpdates to an xdr.ScVal for contract calls.
func (s PriceUpdates) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"gas_price_updates":   scval.StructSliceToScVal(s.GasPriceUpdates),
		"token_price_updates": scval.StructSliceToScVal(s.TokenPriceUpdates),
	})
}

// PriceUpdatesFromScVal parses an xdr.ScVal into PriceUpdates.
func PriceUpdatesFromScVal(val xdr.ScVal) (*PriceUpdates, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &PriceUpdates{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "gas_price_updates":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("gas_price_updates is not a vec")
			}
			result.GasPriceUpdates = make([]GasPriceUpdate, len(*vec))
			for i, item := range *vec {
				v, err := GasPriceUpdateFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.GasPriceUpdates[i] = *v
			}
		case "token_price_updates":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("token_price_updates is not a vec")
			}
			result.TokenPriceUpdates = make([]TokenPriceUpdate, len(*vec))
			for i, item := range *vec {
				v, err := TokenPriceUpdateFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.TokenPriceUpdates[i] = *v
			}
		}
	}

	return result, nil
}

// StaticConfig represents the StaticConfig struct from the contract.
type StaticConfig struct {
	LinkToken         string
	MaxFeeJuelsPerMsg int64
}

// ToScVal converts StaticConfig to an xdr.ScVal for contract calls.
func (s StaticConfig) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"link_token":            scval.AddressToScVal(s.LinkToken),
		"max_fee_juels_per_msg": scval.I128ToScVal(s.MaxFeeJuelsPerMsg),
	})
}

// StaticConfigFromScVal parses an xdr.ScVal into StaticConfig.
func StaticConfigFromScVal(val xdr.ScVal) (*StaticConfig, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &StaticConfig{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "link_token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("link_token: %w", err)
			}
			result.LinkToken = v
		case "max_fee_juels_per_msg":
			v, err := scval.I128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("max_fee_juels_per_msg: %w", err)
			}
			result.MaxFeeJuelsPerMsg = v
		}
	}

	return result, nil
}

// GasPriceUpdate represents the GasPriceUpdate struct from the contract.
type GasPriceUpdate struct {
	DestChainSelector uint64
	UsdPerUnitGas     scval.U128
}

// ToScVal converts GasPriceUpdate to an xdr.ScVal for contract calls.
func (s GasPriceUpdate) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"dest_chain_selector": scval.Uint64ToScVal(s.DestChainSelector),
		"usd_per_unit_gas":    scval.MustToScVal((s.UsdPerUnitGas).ToScVal()),
	})
}

// GasPriceUpdateFromScVal parses an xdr.ScVal into GasPriceUpdate.
func GasPriceUpdateFromScVal(val xdr.ScVal) (*GasPriceUpdate, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &GasPriceUpdate{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		case "usd_per_unit_gas":
			v, err := scval.U128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("usd_per_unit_gas: %w", err)
			}
			result.UsdPerUnitGas = v
		}
	}

	return result, nil
}

// GasQuoteResult represents the GasQuoteResult struct from the contract.
type GasQuoteResult struct {
	FeeTokenPrice     scval.U128
	GasCostUsdCents   scval.U128
	PremiumMultiplier uint32
	TotalGas          uint32
}

// ToScVal converts GasQuoteResult to an xdr.ScVal for contract calls.
func (s GasQuoteResult) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"fee_token_price":    scval.MustToScVal((s.FeeTokenPrice).ToScVal()),
		"gas_cost_usd_cents": scval.MustToScVal((s.GasCostUsdCents).ToScVal()),
		"premium_multiplier": scval.Uint32ToScVal(s.PremiumMultiplier),
		"total_gas":          scval.Uint32ToScVal(s.TotalGas),
	})
}

// GasQuoteResultFromScVal parses an xdr.ScVal into GasQuoteResult.
func GasQuoteResultFromScVal(val xdr.ScVal) (*GasQuoteResult, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &GasQuoteResult{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "fee_token_price":
			v, err := scval.U128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("fee_token_price: %w", err)
			}
			result.FeeTokenPrice = v
		case "gas_cost_usd_cents":
			v, err := scval.U128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("gas_cost_usd_cents: %w", err)
			}
			result.GasCostUsdCents = v
		case "premium_multiplier":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("premium_multiplier is not u32")
			}
			result.PremiumMultiplier = uint32(v)
		case "total_gas":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("total_gas is not u32")
			}
			result.TotalGas = uint32(v)
		}
	}

	return result, nil
}

// DestChainConfig represents the DestChainConfig struct from the contract.
type DestChainConfig struct {
	DefaultTokenDestGas   uint32
	DefaultTokenFeeUsd    uint32
	DefaultTxGasLimit     uint32
	DestGasOverhead       uint32
	DestGasPerPayloadByte uint32
	IsEnabled             bool
	LinkPremiumPercent    uint32
	MaxDataBytes          uint32
	MaxPerMsgGasLimit     uint32
	NetworkFeeUsdCents    uint32
}

// ToScVal converts DestChainConfig to an xdr.ScVal for contract calls.
func (s DestChainConfig) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"default_token_dest_gas":    scval.Uint32ToScVal(s.DefaultTokenDestGas),
		"default_token_fee_usd":     scval.Uint32ToScVal(s.DefaultTokenFeeUsd),
		"default_tx_gas_limit":      scval.Uint32ToScVal(s.DefaultTxGasLimit),
		"dest_gas_overhead":         scval.Uint32ToScVal(s.DestGasOverhead),
		"dest_gas_per_payload_byte": scval.Uint32ToScVal(s.DestGasPerPayloadByte),
		"is_enabled":                scval.BoolToScVal(s.IsEnabled),
		"link_premium_percent":      scval.Uint32ToScVal(s.LinkPremiumPercent),
		"max_data_bytes":            scval.Uint32ToScVal(s.MaxDataBytes),
		"max_per_msg_gas_limit":     scval.Uint32ToScVal(s.MaxPerMsgGasLimit),
		"network_fee_usd_cents":     scval.Uint32ToScVal(s.NetworkFeeUsdCents),
	})
}

// DestChainConfigFromScVal parses an xdr.ScVal into DestChainConfig.
func DestChainConfigFromScVal(val xdr.ScVal) (*DestChainConfig, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &DestChainConfig{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "default_token_dest_gas":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("default_token_dest_gas is not u32")
			}
			result.DefaultTokenDestGas = uint32(v)
		case "default_token_fee_usd":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("default_token_fee_usd is not u32")
			}
			result.DefaultTokenFeeUsd = uint32(v)
		case "default_tx_gas_limit":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("default_tx_gas_limit is not u32")
			}
			result.DefaultTxGasLimit = uint32(v)
		case "dest_gas_overhead":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("dest_gas_overhead is not u32")
			}
			result.DestGasOverhead = uint32(v)
		case "dest_gas_per_payload_byte":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("dest_gas_per_payload_byte is not u32")
			}
			result.DestGasPerPayloadByte = uint32(v)
		case "is_enabled":
			v, ok := entry.Val.GetB()
			if !ok {
				return nil, fmt.Errorf("is_enabled is not bool")
			}
			result.IsEnabled = v
		case "link_premium_percent":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("link_premium_percent is not u32")
			}
			result.LinkPremiumPercent = uint32(v)
		case "max_data_bytes":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("max_data_bytes is not u32")
			}
			result.MaxDataBytes = uint32(v)
		case "max_per_msg_gas_limit":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("max_per_msg_gas_limit is not u32")
			}
			result.MaxPerMsgGasLimit = uint32(v)
		case "network_fee_usd_cents":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("network_fee_usd_cents is not u32")
			}
			result.NetworkFeeUsdCents = uint32(v)
		}
	}

	return result, nil
}

// TimestampedPrice represents the TimestampedPrice struct from the contract.
type TimestampedPrice struct {
	Timestamp uint64
	Value     scval.U128
}

// ToScVal converts TimestampedPrice to an xdr.ScVal for contract calls.
func (s TimestampedPrice) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"timestamp": scval.Uint64ToScVal(s.Timestamp),
		"value":     scval.MustToScVal((s.Value).ToScVal()),
	})
}

// TimestampedPriceFromScVal parses an xdr.ScVal into TimestampedPrice.
func TimestampedPriceFromScVal(val xdr.ScVal) (*TimestampedPrice, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TimestampedPrice{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "timestamp":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("timestamp: %w", err)
			}
			result.Timestamp = v
		case "value":
			v, err := scval.U128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("value: %w", err)
			}
			result.Value = v
		}
	}

	return result, nil
}

// TokenPriceUpdate represents the TokenPriceUpdate struct from the contract.
type TokenPriceUpdate struct {
	Token       string
	UsdPerToken scval.U128
}

// ToScVal converts TokenPriceUpdate to an xdr.ScVal for contract calls.
func (s TokenPriceUpdate) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"token":         scval.AddressToScVal(s.Token),
		"usd_per_token": scval.MustToScVal((s.UsdPerToken).ToScVal()),
	})
}

// TokenPriceUpdateFromScVal parses an xdr.ScVal into TokenPriceUpdate.
func TokenPriceUpdateFromScVal(val xdr.ScVal) (*TokenPriceUpdate, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenPriceUpdate{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("token: %w", err)
			}
			result.Token = v
		case "usd_per_token":
			v, err := scval.U128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("usd_per_token: %w", err)
			}
			result.UsdPerToken = v
		}
	}

	return result, nil
}

// TokenFeeConfigArgs represents the TokenFeeConfigArgs struct from the contract.
type TokenFeeConfigArgs struct {
	Config            TokenTransferFeeConfig
	DestChainSelector uint64
	Token             string
}

// ToScVal converts TokenFeeConfigArgs to an xdr.ScVal for contract calls.
func (s TokenFeeConfigArgs) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"config":              scval.MustToScVal((s.Config).ToScVal()),
		"dest_chain_selector": scval.Uint64ToScVal(s.DestChainSelector),
		"token":               scval.AddressToScVal(s.Token),
	})
}

// TokenFeeConfigArgsFromScVal parses an xdr.ScVal into TokenFeeConfigArgs.
func TokenFeeConfigArgsFromScVal(val xdr.ScVal) (*TokenFeeConfigArgs, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenFeeConfigArgs{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "config":
			v, err := TokenTransferFeeConfigFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("config: %w", err)
			}
			result.Config = *v
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("token: %w", err)
			}
			result.Token = v
		}
	}

	return result, nil
}

// DestChainConfigArgs represents the DestChainConfigArgs struct from the contract.
type DestChainConfigArgs struct {
	Config            DestChainConfig
	DestChainSelector uint64
}

// ToScVal converts DestChainConfigArgs to an xdr.ScVal for contract calls.
func (s DestChainConfigArgs) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"config":              scval.MustToScVal((s.Config).ToScVal()),
		"dest_chain_selector": scval.Uint64ToScVal(s.DestChainSelector),
	})
}

// DestChainConfigArgsFromScVal parses an xdr.ScVal into DestChainConfigArgs.
func DestChainConfigArgsFromScVal(val xdr.ScVal) (*DestChainConfigArgs, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &DestChainConfigArgs{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "config":
			v, err := DestChainConfigFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("config: %w", err)
			}
			result.Config = *v
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		}
	}

	return result, nil
}

// TokenTransferFeeConfig represents the TokenTransferFeeConfig struct from the contract.
type TokenTransferFeeConfig struct {
	DestBytesOverhead uint32
	DestGasOverhead   uint32
	FeeUsdCents       uint32
	IsEnabled         bool
}

// ToScVal converts TokenTransferFeeConfig to an xdr.ScVal for contract calls.
func (s TokenTransferFeeConfig) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"dest_bytes_overhead": scval.Uint32ToScVal(s.DestBytesOverhead),
		"dest_gas_overhead":   scval.Uint32ToScVal(s.DestGasOverhead),
		"fee_usd_cents":       scval.Uint32ToScVal(s.FeeUsdCents),
		"is_enabled":          scval.BoolToScVal(s.IsEnabled),
	})
}

// TokenTransferFeeConfigFromScVal parses an xdr.ScVal into TokenTransferFeeConfig.
func TokenTransferFeeConfigFromScVal(val xdr.ScVal) (*TokenTransferFeeConfig, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenTransferFeeConfig{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_bytes_overhead":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("dest_bytes_overhead is not u32")
			}
			result.DestBytesOverhead = uint32(v)
		case "dest_gas_overhead":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("dest_gas_overhead is not u32")
			}
			result.DestGasOverhead = uint32(v)
		case "fee_usd_cents":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("fee_usd_cents is not u32")
			}
			result.FeeUsdCents = uint32(v)
		case "is_enabled":
			v, ok := entry.Val.GetB()
			if !ok {
				return nil, fmt.Errorf("is_enabled is not bool")
			}
			result.IsEnabled = v
		}
	}

	return result, nil
}

// TokenTransferFeeResult represents the TokenTransferFeeResult struct from the contract.
type TokenTransferFeeResult struct {
	DestBytesOverhead uint32
	DestGasOverhead   uint32
	FeeUsdCents       uint32
}

// ToScVal converts TokenTransferFeeResult to an xdr.ScVal for contract calls.
func (s TokenTransferFeeResult) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"dest_bytes_overhead": scval.Uint32ToScVal(s.DestBytesOverhead),
		"dest_gas_overhead":   scval.Uint32ToScVal(s.DestGasOverhead),
		"fee_usd_cents":       scval.Uint32ToScVal(s.FeeUsdCents),
	})
}

// TokenTransferFeeResultFromScVal parses an xdr.ScVal into TokenTransferFeeResult.
func TokenTransferFeeResultFromScVal(val xdr.ScVal) (*TokenTransferFeeResult, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenTransferFeeResult{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_bytes_overhead":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("dest_bytes_overhead is not u32")
			}
			result.DestBytesOverhead = uint32(v)
		case "dest_gas_overhead":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("dest_gas_overhead is not u32")
			}
			result.DestGasOverhead = uint32(v)
		case "fee_usd_cents":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("fee_usd_cents is not u32")
			}
			result.FeeUsdCents = uint32(v)
		}
	}

	return result, nil
}

// TokenFeeConfigRemoveArgs represents the TokenFeeConfigRemoveArgs struct from the contract.
type TokenFeeConfigRemoveArgs struct {
	DestChainSelector uint64
	Token             string
}

// ToScVal converts TokenFeeConfigRemoveArgs to an xdr.ScVal for contract calls.
func (s TokenFeeConfigRemoveArgs) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"dest_chain_selector": scval.Uint64ToScVal(s.DestChainSelector),
		"token":               scval.AddressToScVal(s.Token),
	})
}

// TokenFeeConfigRemoveArgsFromScVal parses an xdr.ScVal into TokenFeeConfigRemoveArgs.
func TokenFeeConfigRemoveArgsFromScVal(val xdr.ScVal) (*TokenFeeConfigRemoveArgs, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenFeeConfigRemoveArgs{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("token: %w", err)
			}
			result.Token = v
		}
	}

	return result, nil
}

// CCIPError represents the contract error codes.
const (
	CCIPErrorNotInitialized                 = 1
	CCIPErrorAlreadyInitialized             = 2
	CCIPErrorUnauthorized                   = 3
	CCIPErrorNotOwner                       = 4
	CCIPErrorNoPendingOwner                 = 5
	CCIPErrorCallerNotAuthorized            = 6
	CCIPErrorCallerAlreadyAuthorized        = 7
	CCIPErrorCallerNotFound                 = 8
	CCIPErrorRoleNotGranted                 = 9
	CCIPErrorFeatureNotEnabled              = 10
	CCIPErrorRoleAlreadyGranted             = 11
	CCIPErrorCannotRenounceRole             = 12
	CCIPErrorInvalidVersionTag              = 13
	CCIPErrorInvalidSignatureLength         = 14
	CCIPErrorInvalidSignature               = 15
	CCIPErrorInvalidSignatureCount          = 16
	CCIPErrorInvalidSignatureThreshold      = 17
	CCIPErrorInvalidSignaturePubkey         = 18
	CCIPErrorSourceNotConfigured            = 19
	CCIPErrorInvalidVerifierResults         = 20
	CCIPErrorReentrantCall                  = 21
	CCIPErrorTokenNotSupported              = 22
	CCIPErrorFeeTokenNotSupported           = 23
	CCIPErrorNoGasPriceAvailable            = 24
	CCIPErrorDestinationChainNotEnabled     = 25
	CCIPErrorInvalidExtraArgsTag            = 26
	CCIPErrorInvalidExtraArgsData           = 27
	CCIPErrorMessageGasLimitTooHigh         = 28
	CCIPErrorMessageTooLarge                = 29
	CCIPErrorUnsupportedNumberOfTokens      = 30
	CCIPErrorInvalidDestChainConfig         = 31
	CCIPErrorMessageFeeTooHigh              = 32
	CCIPErrorInvalidStaticConfig            = 33
	CCIPErrorInvalidTokenReceiver           = 34
	CCIPErrorSourceTokenDataTooLarge        = 35
	CCIPErrorInvalidDestBytesOverhead       = 36
	CCIPErrorDestinationChainNotSupported   = 37
	CCIPErrorMustBeCalledByRouter           = 38
	CCIPErrorRouterMustSetOriginalSender    = 39
	CCIPErrorCannotSendZeroTokens           = 40
	CCIPErrorCanOnlySendOneTokenPerMessage  = 41
	CCIPErrorUnsupportedToken               = 42
	CCIPErrorInvalidDestChainAddress        = 43
	CCIPErrorFeeExceedsMaxAllowed           = 44
	CCIPErrorInsufficientFeeTokenAmount     = 45
	CCIPErrorTokenReceiverNotAllowed        = 46
	CCIPErrorCursedByRMN                    = 47
	CCIPErrorRemoteChainNotSupported        = 48
	CCIPErrorSenderNotAllowed               = 49
	CCIPErrorInvalidTokenAmount             = 50
	CCIPErrorInvalidReceiverAddress         = 51
	CCIPErrorInvalidConfig                  = 52
	CCIPErrorInvalidVerifierResultsLength   = 53
	CCIPErrorInboundImplementationNotFound  = 54
	CCIPErrorOutboundImplementationNotFound = 55
	CCIPErrorInvalidAddress                 = 56
	CCIPErrorInvalidChainSelector           = 57
	CCIPErrorInvalidVersion                 = 58
	CCIPErrorInvalidCCVVersion              = 59
	CCIPErrorOffRampAlreadyExists           = 60
	CCIPErrorOffRampMismatch                = 61
	CCIPErrorBadRMNSignal                   = 62
	CCIPErrorUnsupportedDestinationChain    = 63
)

// CCIPErrorMessage returns a human-readable message for error codes.
var CCIPErrorMessage = map[int]string{
	1:  "not initialized",
	2:  "already initialized",
	3:  "unauthorized",
	4:  "not owner",
	5:  "no pending owner",
	6:  "caller not authorized",
	7:  "caller already authorized",
	8:  "caller not found",
	9:  "role not granted",
	10: "feature not enabled",
	11: "role already granted",
	12: "cannot renounce role",
	13: "invalid version tag",
	14: "invalid signature length",
	15: "invalid signature",
	16: "invalid signature count",
	17: "invalid signature threshold",
	18: "invalid signature pubkey",
	19: "source not configured",
	20: "invalid verifier results",
	21: "reentrant call",
	22: "token not supported",
	23: "fee token not supported",
	24: "no gas price available",
	25: "destination chain not enabled",
	26: "invalid extra args tag",
	27: "invalid extra args data",
	28: "message gas limit too high",
	29: "message too large",
	30: "unsupported number of tokens",
	31: "invalid dest chain config",
	32: "message fee too high",
	33: "invalid static config",
	34: "invalid token receiver",
	35: "source token data too large",
	36: "invalid dest bytes overhead",
	37: "destination chain not supported",
	38: "must be called by router",
	39: "router must set original sender",
	40: "cannot send zero tokens",
	41: "can only send one token per message",
	42: "unsupported token",
	43: "invalid dest chain address",
	44: "fee exceeds max allowed",
	45: "insufficient fee token amount",
	46: "token receiver not allowed",
	47: "cursed by r m n",
	48: "remote chain not supported",
	49: "sender not allowed",
	50: "invalid token amount",
	51: "invalid receiver address",
	52: "invalid config",
	53: "invalid verifier results length",
	54: "inbound implementation not found",
	55: "outbound implementation not found",
	56: "invalid address",
	57: "invalid chain selector",
	58: "invalid version",
	59: "invalid c c v version",
	60: "off ramp already exists",
	61: "off ramp mismatch",
	62: "bad r m n signal",
	63: "unsupported destination chain",
}

// RoleGrantedEvent represents the RoleGrantedEvent event.
// Topics: [auth_RoleGranted]
type RoleGrantedEvent struct {
	Role    string
	Account string
	Sender  string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleGrantedEventTopic is the event topic identifier.
const RoleGrantedEventTopic = "auth_RoleGranted"

// RoleRevokedEvent represents the RoleRevokedEvent event.
// Topics: [auth_RoleRevoked]
type RoleRevokedEvent struct {
	Role    string
	Account string
	Sender  string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleRevokedEventTopic is the event topic identifier.
const RoleRevokedEventTopic = "auth_RoleRevoked"

// AuthorizedCallerAddedEvent represents the AuthorizedCallerAddedEvent event.
// Topics: [auth_CallerAdded]
type AuthorizedCallerAddedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerAddedEventTopic is the event topic identifier.
const AuthorizedCallerAddedEventTopic = "auth_CallerAdded"

// AuthorizedCallerRemovedEvent represents the AuthorizedCallerRemovedEvent event.
// Topics: [auth_CallerRemoved]
type AuthorizedCallerRemovedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerRemovedEventTopic is the event topic identifier.
const AuthorizedCallerRemovedEventTopic = "auth_CallerRemoved"

// OwnershipTransferStartedEvent represents the OwnershipTransferStartedEvent event.
// Topics: [auth_OwnerTransferStart]
type OwnershipTransferStartedEvent struct {
	PreviousOwner string
	NewOwner      string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferStartedEventTopic is the event topic identifier.
const OwnershipTransferStartedEventTopic = "auth_OwnerTransferStart"

// FeeTokenAddedEvent represents the FeeTokenAddedEvent event.
// Topics: [fq_FeeTokenAdded]
type FeeTokenAddedEvent struct {
	FeeToken string
	// Event metadata
	Ledger uint32
	TxHash string
}

// FeeTokenAddedEventTopic is the event topic identifier.
const FeeTokenAddedEventTopic = "fq_FeeTokenAdded"

// DestChainAddedEvent represents the DestChainAddedEvent event.
// Topics: [fq_DestChainAdded]
type DestChainAddedEvent struct {
	DestChainSelector uint64
	IsEnabled         bool
	MaxDataBytes      uint32
	// Event metadata
	Ledger uint32
	TxHash string
}

// DestChainAddedEventTopic is the event topic identifier.
const DestChainAddedEventTopic = "fq_DestChainAdded"

// FeeTokenRemovedEvent represents the FeeTokenRemovedEvent event.
// Topics: [fq_FeeTokenRemoved]
type FeeTokenRemovedEvent struct {
	FeeToken string
	// Event metadata
	Ledger uint32
	TxHash string
}

// FeeTokenRemovedEventTopic is the event topic identifier.
const FeeTokenRemovedEventTopic = "fq_FeeTokenRemoved"

// UsdPerTokenUpdatedEvent represents the UsdPerTokenUpdatedEvent event.
// Topics: [fq_UsdPerTokenUpdated]
type UsdPerTokenUpdatedEvent struct {
	Token     string
	Value     scval.U128
	Timestamp uint64
	// Event metadata
	Ledger uint32
	TxHash string
}

// UsdPerTokenUpdatedEventTopic is the event topic identifier.
const UsdPerTokenUpdatedEventTopic = "fq_UsdPerTokenUpdated"

// UsdPerUnitGasUpdatedEvent represents the UsdPerUnitGasUpdatedEvent event.
// Topics: [fq_UsdPerUnitGasUpdated]
type UsdPerUnitGasUpdatedEvent struct {
	DestChainSelector uint64
	Value             scval.U128
	Timestamp         uint64
	// Event metadata
	Ledger uint32
	TxHash string
}

// UsdPerUnitGasUpdatedEventTopic is the event topic identifier.
const UsdPerUnitGasUpdatedEventTopic = "fq_UsdPerUnitGasUpdated"

// TokenFeeConfigDeletedEvent represents the TokenFeeConfigDeletedEvent event.
// Topics: [fq_TknTransferFeeDeleted]
type TokenFeeConfigDeletedEvent struct {
	DestChainSelector uint64
	Token             string
	// Event metadata
	Ledger uint32
	TxHash string
}

// TokenFeeConfigDeletedEventTopic is the event topic identifier.
const TokenFeeConfigDeletedEventTopic = "fq_TknTransferFeeDeleted"

// TokenFeeConfigUpdatedEvent represents the TokenFeeConfigUpdatedEvent event.
// Topics: [fq_TknTransferFeeUpdated]
type TokenFeeConfigUpdatedEvent struct {
	DestChainSelector uint64
	Token             string
	FeeUsdCents       uint32
	DestGasOverhead   uint32
	DestBytesOverhead uint32
	// Event metadata
	Ledger uint32
	TxHash string
}

// TokenFeeConfigUpdatedEventTopic is the event topic identifier.
const TokenFeeConfigUpdatedEventTopic = "fq_TknTransferFeeUpdated"

// DestChainConfigUpdatedEvent represents the DestChainConfigUpdatedEvent event.
// Topics: [fq_DestChainConfigUpdated]
type DestChainConfigUpdatedEvent struct {
	DestChainSelector uint64
	IsEnabled         bool
	MaxDataBytes      uint32
	// Event metadata
	Ledger uint32
	TxHash string
}

// DestChainConfigUpdatedEventTopic is the event topic identifier.
const DestChainConfigUpdatedEventTopic = "fq_DestChainConfigUpdated"
