// Code generated by stellar-bindings-generator. DO NOT EDIT.
package token_admin_registry

import (
	"context"
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// TokenAdminRegistryClient provides methods to interact with the TokenAdminRegistry contract.
type TokenAdminRegistryClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewTokenAdminRegistryClient creates a new TokenAdminRegistryClient.
func NewTokenAdminRegistryClient(invoker bindings.Invoker, contractID string) *TokenAdminRegistryClient {
	return &TokenAdminRegistryClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *TokenAdminRegistryClient) ContractID() string {
	return c.contractID
}

// Initialize calls the initialize function on the contract.
func (c *TokenAdminRegistryClient) Initialize(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *TokenAdminRegistryClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetPool calls the get_pool function on the contract.
func (c *TokenAdminRegistryClient) GetPool(ctx context.Context, token string) (*string, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pool", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pool: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pool")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// GetPools calls the get_pools function on the contract.
func (c *TokenAdminRegistryClient) GetPools(ctx context.Context, tokens []string) ([]*string, error) {
	args := []xdr.ScVal{
		scval.AddressSliceToScVal(tokens),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pools", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pools: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pools")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]*string, len(*vec))
	for i, item := range *vec {
		v, err := scval.OptionalAddressFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

// GetTokenConfig calls the get_token_config function on the contract.
func (c *TokenAdminRegistryClient) GetTokenConfig(ctx context.Context, token string) (*TokenConfig, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_token_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_token_config")
	}

	return TokenConfigFromScVal(*result)
}

// GetAllConfiguredTokens calls the get_all_configured_tokens function on the contract.
func (c *TokenAdminRegistryClient) GetAllConfiguredTokens(ctx context.Context, startIndex uint32, maxCount uint32) ([]string, error) {
	args := []xdr.ScVal{
		scval.Uint32ToScVal(startIndex),
		scval.Uint32ToScVal(maxCount),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_all_configured_tokens", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_all_configured_tokens: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_all_configured_tokens")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]string, len(*vec))
	for i, item := range *vec {
		v, err := scval.AddressFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

// IsAdministrator calls the is_administrator function on the contract.
func (c *TokenAdminRegistryClient) IsAdministrator(ctx context.Context, localToken string, administrator string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(localToken),
		scval.AddressToScVal(administrator),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_administrator", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_administrator: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_administrator")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// SetPool calls the set_pool function on the contract.
func (c *TokenAdminRegistryClient) SetPool(ctx context.Context, localToken string, pool *string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(localToken),
		scval.OptionalAddressToScVal(pool),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_pool", args)
	if err != nil {
		return fmt.Errorf("failed to call set_pool: %w", err)
	}

	_ = result // void return
	return nil
}

// ProposeAdministrator calls the propose_administrator function on the contract.
func (c *TokenAdminRegistryClient) ProposeAdministrator(ctx context.Context, caller string, localToken string, administrator string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.AddressToScVal(localToken),
		scval.AddressToScVal(administrator),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "propose_administrator", args)
	if err != nil {
		return fmt.Errorf("failed to call propose_administrator: %w", err)
	}

	_ = result // void return
	return nil
}

// AcceptAdminRole calls the accept_admin_role function on the contract.
func (c *TokenAdminRegistryClient) AcceptAdminRole(ctx context.Context, localToken string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(localToken),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_admin_role", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_admin_role: %w", err)
	}

	_ = result // void return
	return nil
}

// TransferAdminRole calls the transfer_admin_role function on the contract.
func (c *TokenAdminRegistryClient) TransferAdminRole(ctx context.Context, localToken string, newAdmin *string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(localToken),
		scval.OptionalAddressToScVal(newAdmin),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_admin_role", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_admin_role: %w", err)
	}

	_ = result // void return
	return nil
}

// IsRegistryModule calls the is_registry_module function on the contract.
func (c *TokenAdminRegistryClient) IsRegistryModule(ctx context.Context, module string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(module),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_registry_module", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_registry_module: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_registry_module")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// AddRegistryModule calls the add_registry_module function on the contract.
func (c *TokenAdminRegistryClient) AddRegistryModule(ctx context.Context, module string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(module),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "add_registry_module", args)
	if err != nil {
		return fmt.Errorf("failed to call add_registry_module: %w", err)
	}

	_ = result // void return
	return nil
}

// RemoveRegistryModule calls the remove_registry_module function on the contract.
func (c *TokenAdminRegistryClient) RemoveRegistryModule(ctx context.Context, module string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(module),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "remove_registry_module", args)
	if err != nil {
		return fmt.Errorf("failed to call remove_registry_module: %w", err)
	}

	_ = result // void return
	return nil
}
