// Code generated by stellar-bindings-generator. DO NOT EDIT.
package rmn_remote

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// RmnRemoteClient provides methods to interact with the RmnRemote contract.
type RmnRemoteClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewRmnRemoteClient creates a new RmnRemoteClient.
func NewRmnRemoteClient(invoker bindings.Invoker, contractID string) *RmnRemoteClient {
	return &RmnRemoteClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *RmnRemoteClient) ContractID() string {
	return c.contractID
}

// Curse calls the curse function on the contract.
func (c *RmnRemoteClient) Curse(ctx context.Context, caller string, subjects [][16]byte) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.Bytes16SliceToScVal(subjects),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "curse", args)
	if err != nil {
		return fmt.Errorf("failed to call curse: %w", err)
	}

	_ = result // void return
	return nil
}

// Owner calls the owner function on the contract.
func (c *RmnRemoteClient) Owner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// Uncurse calls the uncurse function on the contract.
func (c *RmnRemoteClient) Uncurse(ctx context.Context, subjects [][16]byte) error {
	args := []xdr.ScVal{
		scval.Bytes16SliceToScVal(subjects),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "uncurse", args)
	if err != nil {
		return fmt.Errorf("failed to call uncurse: %w", err)
	}

	_ = result // void return
	return nil
}

// IsOwner calls the is_owner function on the contract.
func (c *RmnRemoteClient) IsOwner(ctx context.Context, addr string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_owner", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_owner: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_owner")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// IsCursed calls the is_cursed function on the contract.
func (c *RmnRemoteClient) IsCursed(ctx context.Context) (bool, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_cursed", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_cursed: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_cursed")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// InitOwner calls the init_owner function on the contract.
func (c *RmnRemoteClient) InitOwner(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call init_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// Initialize calls the initialize function on the contract.
func (c *RmnRemoteClient) Initialize(ctx context.Context, owner string, curseAdmins []string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
		scval.AddressSliceToScVal(curseAdmins),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// RequireOwner calls the require_owner function on the contract.
func (c *RmnRemoteClient) RequireOwner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call require_owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from require_owner")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// SetNewOwner calls the set_new_owner function on the contract.
func (c *RmnRemoteClient) SetNewOwner(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_new_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call set_new_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *RmnRemoteClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// GetCurseAdmins calls the get_curse_admins function on the contract.
func (c *RmnRemoteClient) GetCurseAdmins(ctx context.Context) ([]string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_curse_admins", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_curse_admins: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_curse_admins")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]string, len(*vec))
	for i, item := range *vec {
		v, err := scval.AddressFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *RmnRemoteClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetPendingOwner calls the get_pending_owner function on the contract.
func (c *RmnRemoteClient) GetPendingOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pending_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pending_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pending_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *RmnRemoteClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// GetCursedSubjects calls the get_cursed_subjects function on the contract.
func (c *RmnRemoteClient) GetCursedSubjects(ctx context.Context) ([][16]byte, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_cursed_subjects", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_cursed_subjects: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_cursed_subjects")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([][16]byte, len(*vec))
	for i, item := range *vec {
		v, err := scval.Bytes16FromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

// IsCursedBySubject calls the is_cursed_by_subject function on the contract.
func (c *RmnRemoteClient) IsCursedBySubject(ctx context.Context, subject [16]byte) (bool, error) {
	args := []xdr.ScVal{
		scval.Bytes16ToScVal(subject),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_cursed_by_subject", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_cursed_by_subject: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_cursed_by_subject")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// ApplyCurseAdminUpdates calls the apply_curse_admin_updates function on the contract.
func (c *RmnRemoteClient) ApplyCurseAdminUpdates(ctx context.Context, addedAdmins []string, removedAdmins []string) error {
	args := []xdr.ScVal{
		scval.AddressSliceToScVal(addedAdmins),
		scval.AddressSliceToScVal(removedAdmins),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_curse_admin_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_curse_admin_updates: %w", err)
	}

	_ = result // void return
	return nil
}

// CancelOwnershipTransfer calls the cancel_ownership_transfer function on the contract.
func (c *RmnRemoteClient) CancelOwnershipTransfer(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "cancel_ownership_transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call cancel_ownership_transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// WaitForAuthorizedCallerAddedEvent waits for a AuthorizedCallerAddedEvent event.
func (c *RmnRemoteClient) WaitForAuthorizedCallerAddedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerAddedEvent) bool) (*AuthorizedCallerAddedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerAddedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAuthorizedCallerAddedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAuthorizedCallerAddedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerAddedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerAddedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerRemovedEvent waits for a AuthorizedCallerRemovedEvent event.
func (c *RmnRemoteClient) WaitForAuthorizedCallerRemovedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerRemovedEvent) bool) (*AuthorizedCallerRemovedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerRemovedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAuthorizedCallerRemovedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAuthorizedCallerRemovedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerRemovedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerRemovedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransferStartedEvent waits for a OwnershipTransferStartedEvent event.
func (c *RmnRemoteClient) WaitForOwnershipTransferStartedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransferStartedEvent) bool) (*OwnershipTransferStartedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferStartedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipTransferStartedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipTransferStartedEvent(e protocolrpc.EventInfo) (*OwnershipTransferStartedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransferStartedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "previous_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.PreviousOwner = v
			}
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		}
	}

	return result, nil
}

// WaitForCursedEvent waits for a CursedEvent event.
func (c *RmnRemoteClient) WaitForCursedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*CursedEvent) bool) (*CursedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{CursedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseCursedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseCursedEvent(e protocolrpc.EventInfo) (*CursedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &CursedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "subjects":
			vec, ok := entry.Val.GetVec()
			if ok && vec != nil {
				parsed := make([][16]byte, len(*vec))
				for i, item := range *vec {
					v, err := scval.Bytes16FromScVal(item)
					if err == nil {
						parsed[i] = v
					}
				}
				result.Subjects = parsed
			}
		}
	}

	return result, nil
}

// WaitForUncursedEvent waits for a UncursedEvent event.
func (c *RmnRemoteClient) WaitForUncursedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*UncursedEvent) bool) (*UncursedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{UncursedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseUncursedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseUncursedEvent(e protocolrpc.EventInfo) (*UncursedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &UncursedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "subjects":
			vec, ok := entry.Val.GetVec()
			if ok && vec != nil {
				parsed := make([][16]byte, len(*vec))
				for i, item := range *vec {
					v, err := scval.Bytes16FromScVal(item)
					if err == nil {
						parsed[i] = v
					}
				}
				result.Subjects = parsed
			}
		}
	}

	return result, nil
}
