// Code generated by stellar-bindings-generator. DO NOT EDIT.
package rmn_remote

// AuthorizedCallerAddedEvent represents the AuthorizedCallerAddedEvent event.
// Topics: [auth_CallerAdded]
type AuthorizedCallerAddedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerAddedEventTopic is the event topic identifier.
const AuthorizedCallerAddedEventTopic = "auth_CallerAdded"

// AuthorizedCallerRemovedEvent represents the AuthorizedCallerRemovedEvent event.
// Topics: [auth_CallerRemoved]
type AuthorizedCallerRemovedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerRemovedEventTopic is the event topic identifier.
const AuthorizedCallerRemovedEventTopic = "auth_CallerRemoved"

// OwnershipTransferStartedEvent represents the OwnershipTransferStartedEvent event.
// Topics: [auth_OwnerTransferStart]
type OwnershipTransferStartedEvent struct {
	PreviousOwner string
	NewOwner      string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferStartedEventTopic is the event topic identifier.
const OwnershipTransferStartedEventTopic = "auth_OwnerTransferStart"

// CursedEvent represents the CursedEvent event.
// Topics: [rmn_Cursed]
type CursedEvent struct {
	Subjects [][16]byte
	// Event metadata
	Ledger uint32
	TxHash string
}

// CursedEventTopic is the event topic identifier.
const CursedEventTopic = "rmn_Cursed"

// UncursedEvent represents the UncursedEvent event.
// Topics: [rmn_Uncursed]
type UncursedEvent struct {
	Subjects [][16]byte
	// Event metadata
	Ledger uint32
	TxHash string
}

// UncursedEventTopic is the event topic identifier.
const UncursedEventTopic = "rmn_Uncursed"
