// Code generated by stellar-bindings-generator. DO NOT EDIT.
package ccip_receiver

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// ExampleCcipReceiverClient provides methods to interact with the ExampleCcipReceiver contract.
type ExampleCcipReceiverClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewExampleCcipReceiverClient creates a new ExampleCcipReceiverClient.
func NewExampleCcipReceiverClient(invoker bindings.Invoker, contractID string) *ExampleCcipReceiverClient {
	return &ExampleCcipReceiverClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *ExampleCcipReceiverClient) ContractID() string {
	return c.contractID
}

// Owner calls the owner function on the contract.
func (c *ExampleCcipReceiverClient) Owner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// IsOwner calls the is_owner function on the contract.
func (c *ExampleCcipReceiverClient) IsOwner(ctx context.Context, addr string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_owner", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_owner: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_owner")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// GetRouter calls the get_router function on the contract.
func (c *ExampleCcipReceiverClient) GetRouter(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_router", args)
	if err != nil {
		return "", fmt.Errorf("failed to call get_router: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from get_router")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// InitOwner calls the init_owner function on the contract.
func (c *ExampleCcipReceiverClient) InitOwner(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call init_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// Initialize calls the initialize function on the contract.
func (c *ExampleCcipReceiverClient) Initialize(ctx context.Context, owner string, router string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
		scval.AddressToScVal(router),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// CcipReceive calls the ccip_receive function on the contract.
func (c *ExampleCcipReceiverClient) CcipReceive(ctx context.Context, message AnyToStellarMessage) error {
	args := []xdr.ScVal{
		scval.MustToScVal(message.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "ccip_receive", args)
	if err != nil {
		return fmt.Errorf("failed to call ccip_receive: %w", err)
	}

	_ = result // void return
	return nil
}

// RequireOwner calls the require_owner function on the contract.
func (c *ExampleCcipReceiverClient) RequireOwner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call require_owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from require_owner")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// SetNewOwner calls the set_new_owner function on the contract.
func (c *ExampleCcipReceiverClient) SetNewOwner(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_new_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call set_new_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// GetCcvConfig calls the get_ccv_config function on the contract.
func (c *ExampleCcipReceiverClient) GetCcvConfig(ctx context.Context, sourceChainSelector uint64) (*CcvChainConfig, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(sourceChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_ccv_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_ccv_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_ccv_config")
	}

	return CcvChainConfigFromScVal(*result)
}

// LastMessageId calls the last_message_id function on the contract.
func (c *ExampleCcipReceiverClient) LastMessageId(ctx context.Context) ([32]byte, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "last_message_id", args)
	if err != nil {
		return [32]byte{}, fmt.Errorf("failed to call last_message_id: %w", err)
	}

	if result == nil {
		return [32]byte{}, fmt.Errorf("no return value from last_message_id")
	}

	v, err := scval.Bytes32FromScVal(*result)
	if err != nil {
		return [32]byte{}, err
	}
	return v, nil
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *ExampleCcipReceiverClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *ExampleCcipReceiverClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetPendingOwner calls the get_pending_owner function on the contract.
func (c *ExampleCcipReceiverClient) GetPendingOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pending_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pending_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pending_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *ExampleCcipReceiverClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// EnableRemoteChain calls the enable_remote_chain function on the contract.
func (c *ExampleCcipReceiverClient) EnableRemoteChain(ctx context.Context, caller string, destChainSelector uint64, extraArgs []byte, allowedFinalityConfig uint32) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.Uint64ToScVal(destChainSelector),
		scval.BytesToScVal(extraArgs),
		scval.Uint32ToScVal(allowedFinalityConfig),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "enable_remote_chain", args)
	if err != nil {
		return fmt.Errorf("failed to call enable_remote_chain: %w", err)
	}

	_ = result // void return
	return nil
}

// DisableRemoteChain calls the disable_remote_chain function on the contract.
func (c *ExampleCcipReceiverClient) DisableRemoteChain(ctx context.Context, caller string, destChainSelector uint64) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.Uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "disable_remote_chain", args)
	if err != nil {
		return fmt.Errorf("failed to call disable_remote_chain: %w", err)
	}

	_ = result // void return
	return nil
}

// GetRemoteChainConfig calls the get_remote_chain_config function on the contract.
func (c *ExampleCcipReceiverClient) GetRemoteChainConfig(ctx context.Context, chainSelector uint64) (*RemoteChainConfig, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(chainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_chain_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_chain_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_chain_config")
	}

	return RemoteChainConfigFromScVal(*result)
}

// SendDataPayFeeToken calls the send_data_pay_fee_token function on the contract.
func (c *ExampleCcipReceiverClient) SendDataPayFeeToken(ctx context.Context, caller string, destChainSelector uint64, receiver []byte, data []byte, feeToken string, feeTokenAmount int64) ([32]byte, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.Uint64ToScVal(destChainSelector),
		scval.BytesToScVal(receiver),
		scval.BytesToScVal(data),
		scval.AddressToScVal(feeToken),
		scval.I128ToScVal(feeTokenAmount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "send_data_pay_fee_token", args)
	if err != nil {
		return [32]byte{}, fmt.Errorf("failed to call send_data_pay_fee_token: %w", err)
	}

	if result == nil {
		return [32]byte{}, fmt.Errorf("no return value from send_data_pay_fee_token")
	}

	v, err := scval.Bytes32FromScVal(*result)
	if err != nil {
		return [32]byte{}, err
	}
	return v, nil
}

// ApplyCcvConfigUpdates calls the apply_ccv_config_updates function on the contract.
func (c *ExampleCcipReceiverClient) ApplyCcvConfigUpdates(ctx context.Context, caller string, updates []CcvConfigUpdate) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.StructSliceToScVal(updates),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_ccv_config_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_ccv_config_updates: %w", err)
	}

	_ = result // void return
	return nil
}

// CancelOwnershipTransfer calls the cancel_ownership_transfer function on the contract.
func (c *ExampleCcipReceiverClient) CancelOwnershipTransfer(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "cancel_ownership_transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call cancel_ownership_transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// GetRemoteChainSelectors calls the get_remote_chain_selectors function on the contract.
func (c *ExampleCcipReceiverClient) GetRemoteChainSelectors(ctx context.Context) ([]uint64, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_chain_selectors", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_chain_selectors: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_chain_selectors")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]uint64, len(*vec))
	for i, item := range *vec {
		v, err := scval.Uint64FromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

// GetRemoteChainExtraArgs calls the get_remote_chain_extra_args function on the contract.
func (c *ExampleCcipReceiverClient) GetRemoteChainExtraArgs(ctx context.Context, destChainSelector uint64) ([]byte, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_chain_extra_args", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_chain_extra_args: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_chain_extra_args")
	}

	v, ok := result.GetBytes()
	if !ok {
		return nil, fmt.Errorf("expected bytes return type")
	}
	return []byte(v), nil
}

// GetCcvsAndFinalityConfig calls the get_ccvs_and_finality_config function on the contract.
func (c *ExampleCcipReceiverClient) GetCcvsAndFinalityConfig(ctx context.Context, sourceChainSelector uint64, unused []byte) (*CcvsAndFinalityConfig, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(sourceChainSelector),
		scval.BytesToScVal(unused),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_ccvs_and_finality_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_ccvs_and_finality_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_ccvs_and_finality_config")
	}

	return CcvsAndFinalityConfigFromScVal(*result)
}

// WaitForCcipCcvConfigSetEvent waits for a CcipCcvConfigSetEvent event.
func (c *ExampleCcipReceiverClient) WaitForCcipCcvConfigSetEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*CcipCcvConfigSetEvent) bool) (*CcipCcvConfigSetEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{CcipCcvConfigSetEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseCcipCcvConfigSetEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseCcipCcvConfigSetEvent(e protocolrpc.EventInfo) (*CcipCcvConfigSetEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &CcipCcvConfigSetEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "source_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.SourceChainSelector = v
			}
		case "required_len":
			v, ok := entry.Val.GetU32()
			if ok {
				result.RequiredLen = uint32(v)
			}
		case "optional_len":
			v, ok := entry.Val.GetU32()
			if ok {
				result.OptionalLen = uint32(v)
			}
		case "optional_threshold":
			v, ok := entry.Val.GetU32()
			if ok {
				result.OptionalThreshold = uint32(v)
			}
		}
	}

	return result, nil
}

// WaitForCcipMessageReceivedEvent waits for a CcipMessageReceivedEvent event.
func (c *ExampleCcipReceiverClient) WaitForCcipMessageReceivedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*CcipMessageReceivedEvent) bool) (*CcipMessageReceivedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{CcipMessageReceivedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseCcipMessageReceivedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseCcipMessageReceivedEvent(e protocolrpc.EventInfo) (*CcipMessageReceivedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &CcipMessageReceivedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "message_id":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err == nil {
				result.MessageId = v
			}
		case "source_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.SourceChainSelector = v
			}
		case "data_len":
			v, ok := entry.Val.GetU32()
			if ok {
				result.DataLen = uint32(v)
			}
		case "sender_len":
			v, ok := entry.Val.GetU32()
			if ok {
				result.SenderLen = uint32(v)
			}
		case "dest_token_transfers":
			v, ok := entry.Val.GetU32()
			if ok {
				result.DestTokenTransfers = uint32(v)
			}
		}
	}

	return result, nil
}

// WaitForCcipRemoteChainConfiguredEvent waits for a CcipRemoteChainConfiguredEvent event.
func (c *ExampleCcipReceiverClient) WaitForCcipRemoteChainConfiguredEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*CcipRemoteChainConfiguredEvent) bool) (*CcipRemoteChainConfiguredEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{CcipRemoteChainConfiguredEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseCcipRemoteChainConfiguredEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseCcipRemoteChainConfiguredEvent(e protocolrpc.EventInfo) (*CcipRemoteChainConfiguredEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &CcipRemoteChainConfiguredEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.DestChainSelector = v
			}
		case "extra_args_len":
			v, ok := entry.Val.GetU32()
			if ok {
				result.ExtraArgsLen = uint32(v)
			}
		case "allowed_finality_config":
			v, ok := entry.Val.GetU32()
			if ok {
				result.AllowedFinalityConfig = uint32(v)
			}
		}
	}

	return result, nil
}
