// Code generated by stellar-bindings-generator. DO NOT EDIT.
package ccip_receiver

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// ExampleCcipReceiverClient provides methods to interact with the ExampleCcipReceiver contract.
type ExampleCcipReceiverClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewExampleCcipReceiverClient creates a new ExampleCcipReceiverClient.
func NewExampleCcipReceiverClient(invoker bindings.Invoker, contractID string) *ExampleCcipReceiverClient {
	return &ExampleCcipReceiverClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *ExampleCcipReceiverClient) ContractID() string {
	return c.contractID
}

// GetRouter calls the get_router function on the contract.
func (c *ExampleCcipReceiverClient) GetRouter(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_router", args)
	if err != nil {
		return "", fmt.Errorf("failed to call get_router: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from get_router")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// Initialize calls the initialize function on the contract.
func (c *ExampleCcipReceiverClient) Initialize(ctx context.Context, router string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(router),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// CcipReceive calls the ccip_receive function on the contract.
func (c *ExampleCcipReceiverClient) CcipReceive(ctx context.Context, message AnyToStellarMessage) error {
	args := []xdr.ScVal{
		scval.MustToScVal(message.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "ccip_receive", args)
	if err != nil {
		return fmt.Errorf("failed to call ccip_receive: %w", err)
	}

	_ = result // void return
	return nil
}

// LastMessageId calls the last_message_id function on the contract.
func (c *ExampleCcipReceiverClient) LastMessageId(ctx context.Context) ([32]byte, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "last_message_id", args)
	if err != nil {
		return [32]byte{}, fmt.Errorf("failed to call last_message_id: %w", err)
	}

	if result == nil {
		return [32]byte{}, fmt.Errorf("no return value from last_message_id")
	}

	v, err := scval.Bytes32FromScVal(*result)
	if err != nil {
		return [32]byte{}, err
	}
	return v, nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *ExampleCcipReceiverClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// WaitForCcipMessageReceivedEvent waits for a CcipMessageReceivedEvent event.
func (c *ExampleCcipReceiverClient) WaitForCcipMessageReceivedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*CcipMessageReceivedEvent) bool) (*CcipMessageReceivedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{CcipMessageReceivedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseCcipMessageReceivedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseCcipMessageReceivedEvent(e protocolrpc.EventInfo) (*CcipMessageReceivedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &CcipMessageReceivedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "message_id":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err == nil {
				result.MessageId = v
			}
		case "source_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.SourceChainSelector = v
			}
		case "data_len":
			v, ok := entry.Val.GetU32()
			if ok {
				result.DataLen = uint32(v)
			}
		case "sender_len":
			v, ok := entry.Val.GetU32()
			if ok {
				result.SenderLen = uint32(v)
			}
		case "dest_token_transfers":
			v, ok := entry.Val.GetU32()
			if ok {
				result.DestTokenTransfers = uint32(v)
			}
		}
	}

	return result, nil
}
