// Code generated by stellar-bindings-generator. DO NOT EDIT.
package link_token

import (
	"context"
	"fmt"
	"math/big"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// LinkTokenClient provides methods to interact with the LinkToken contract.
type LinkTokenClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewLinkTokenClient creates a new LinkTokenClient.
func NewLinkTokenClient(invoker bindings.Invoker, contractID string) *LinkTokenClient {
	return &LinkTokenClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *LinkTokenClient) ContractID() string {
	return c.contractID
}

// Burn calls the burn function on the contract.
func (c *LinkTokenClient) Burn(ctx context.Context, from string, amount *big.Int) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(from),
		scval.I128ToScVal(amount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "burn", args)
	if err != nil {
		return fmt.Errorf("failed to call burn: %w", err)
	}

	_ = result // void return
	return nil
}

// Mint calls the mint function on the contract.
func (c *LinkTokenClient) Mint(ctx context.Context, to string, amount *big.Int) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(to),
		scval.I128ToScVal(amount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "mint", args)
	if err != nil {
		return fmt.Errorf("failed to call mint: %w", err)
	}

	_ = result // void return
	return nil
}

// Name calls the name function on the contract.
func (c *LinkTokenClient) Name(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "name", args)
	if err != nil {
		return "", fmt.Errorf("failed to call name: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from name")
	}

	return scval.StringFromScVal(*result)
}

// Admin calls the admin function on the contract.
func (c *LinkTokenClient) Admin(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "admin", args)
	if err != nil {
		return "", fmt.Errorf("failed to call admin: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from admin")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// Owner calls the owner function on the contract.
func (c *LinkTokenClient) Owner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// Trust calls the trust function on the contract.
func (c *LinkTokenClient) Trust(ctx context.Context, addr string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "trust", args)
	if err != nil {
		return fmt.Errorf("failed to call trust: %w", err)
	}

	_ = result // void return
	return nil
}

// Symbol calls the symbol function on the contract.
func (c *LinkTokenClient) Symbol(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "symbol", args)
	if err != nil {
		return "", fmt.Errorf("failed to call symbol: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from symbol")
	}

	return scval.StringFromScVal(*result)
}

// Approve calls the approve function on the contract.
func (c *LinkTokenClient) Approve(ctx context.Context, from string, spender string, amount *big.Int, expirationLedger uint32) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(from),
		scval.AddressToScVal(spender),
		scval.I128ToScVal(amount),
		scval.Uint32ToScVal(expirationLedger),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "approve", args)
	if err != nil {
		return fmt.Errorf("failed to call approve: %w", err)
	}

	_ = result // void return
	return nil
}

// Balance calls the balance function on the contract.
func (c *LinkTokenClient) Balance(ctx context.Context, id string) (*big.Int, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(id),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "balance", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call balance: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from balance")
	}

	v, err := scval.I128FromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// MintAs calls the mint_as function on the contract.
func (c *LinkTokenClient) MintAs(ctx context.Context, caller string, to string, amount *big.Int) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.AddressToScVal(to),
		scval.I128ToScVal(amount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "mint_as", args)
	if err != nil {
		return fmt.Errorf("failed to call mint_as: %w", err)
	}

	_ = result // void return
	return nil
}

// Clawback calls the clawback function on the contract.
func (c *LinkTokenClient) Clawback(ctx context.Context, from string, amount *big.Int) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(from),
		scval.I128ToScVal(amount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "clawback", args)
	if err != nil {
		return fmt.Errorf("failed to call clawback: %w", err)
	}

	_ = result // void return
	return nil
}

// Decimals calls the decimals function on the contract.
func (c *LinkTokenClient) Decimals(ctx context.Context) (uint32, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "decimals", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call decimals: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from decimals")
	}

	v, ok := result.GetU32()
	if !ok {
		return 0, fmt.Errorf("expected u32 return type")
	}
	return uint32(v), nil
}

// IsOwner calls the is_owner function on the contract.
func (c *LinkTokenClient) IsOwner(ctx context.Context, addr string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_owner", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_owner: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_owner")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// Transfer calls the transfer function on the contract.
func (c *LinkTokenClient) Transfer(ctx context.Context, from string, to string, amount *big.Int) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(from),
		scval.AddressToScVal(to),
		scval.I128ToScVal(amount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// Allowance calls the allowance function on the contract.
func (c *LinkTokenClient) Allowance(ctx context.Context, from string, spender string) (*big.Int, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(from),
		scval.AddressToScVal(spender),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "allowance", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call allowance: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from allowance")
	}

	v, err := scval.I128FromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// BurnFrom calls the burn_from function on the contract.
func (c *LinkTokenClient) BurnFrom(ctx context.Context, spender string, from string, amount *big.Int) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(spender),
		scval.AddressToScVal(from),
		scval.I128ToScVal(amount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "burn_from", args)
	if err != nil {
		return fmt.Errorf("failed to call burn_from: %w", err)
	}

	_ = result // void return
	return nil
}

// SetAdmin calls the set_admin function on the contract.
func (c *LinkTokenClient) SetAdmin(ctx context.Context, newAdmin string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newAdmin),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_admin", args)
	if err != nil {
		return fmt.Errorf("failed to call set_admin: %w", err)
	}

	_ = result // void return
	return nil
}

// AddMinter calls the add_minter function on the contract.
func (c *LinkTokenClient) AddMinter(ctx context.Context, minter string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(minter),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "add_minter", args)
	if err != nil {
		return fmt.Errorf("failed to call add_minter: %w", err)
	}

	_ = result // void return
	return nil
}

// Authorized calls the authorized function on the contract.
func (c *LinkTokenClient) Authorized(ctx context.Context, id string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(id),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "authorized", args)
	if err != nil {
		return false, fmt.Errorf("failed to call authorized: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from authorized")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// InitOwner calls the init_owner function on the contract.
func (c *LinkTokenClient) InitOwner(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call init_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// Initialize calls the initialize function on the contract.
func (c *LinkTokenClient) Initialize(ctx context.Context, admin string, name string, symbol string, decimals uint32) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(admin),
		scval.StringToScVal(name),
		scval.StringToScVal(symbol),
		scval.Uint32ToScVal(decimals),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// GetMinters calls the get_minters function on the contract.
func (c *LinkTokenClient) GetMinters(ctx context.Context) ([]string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_minters", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_minters: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_minters")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]string, len(*vec))
	for i, item := range *vec {
		v, err := scval.AddressFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}

// RemoveMinter calls the remove_minter function on the contract.
func (c *LinkTokenClient) RemoveMinter(ctx context.Context, minter string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(minter),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "remove_minter", args)
	if err != nil {
		return fmt.Errorf("failed to call remove_minter: %w", err)
	}

	_ = result // void return
	return nil
}

// RequireOwner calls the require_owner function on the contract.
func (c *LinkTokenClient) RequireOwner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call require_owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from require_owner")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// TransferFrom calls the transfer_from function on the contract.
func (c *LinkTokenClient) TransferFrom(ctx context.Context, spender string, from string, to string, amount *big.Int) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(spender),
		scval.AddressToScVal(from),
		scval.AddressToScVal(to),
		scval.I128ToScVal(amount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_from", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_from: %w", err)
	}

	_ = result // void return
	return nil
}

// SetAuthorized calls the set_authorized function on the contract.
func (c *LinkTokenClient) SetAuthorized(ctx context.Context, id string, authorize bool) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(id),
		scval.BoolToScVal(authorize),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_authorized", args)
	if err != nil {
		return fmt.Errorf("failed to call set_authorized: %w", err)
	}

	_ = result // void return
	return nil
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *LinkTokenClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *LinkTokenClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetPendingOwner calls the get_pending_owner function on the contract.
func (c *LinkTokenClient) GetPendingOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pending_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pending_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pending_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *LinkTokenClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// CancelOwnershipTransfer calls the cancel_ownership_transfer function on the contract.
func (c *LinkTokenClient) CancelOwnershipTransfer(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "cancel_ownership_transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call cancel_ownership_transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// WaitForUpgraded waits for a Upgraded event.
func (c *LinkTokenClient) WaitForUpgraded(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*Upgraded) bool) (*Upgraded, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{UpgradedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseUpgraded(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseUpgraded(e protocolrpc.EventInfo) (*Upgraded, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &Upgraded{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "new_wasm_hash":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err == nil {
				result.NewWasmHash = v
			}
		}
	}

	return result, nil
}

// WaitForRoleGrantedEvent waits for a RoleGrantedEvent event.
func (c *LinkTokenClient) WaitForRoleGrantedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RoleGrantedEvent) bool) (*RoleGrantedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RoleGrantedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseRoleGrantedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseRoleGrantedEvent(e protocolrpc.EventInfo) (*RoleGrantedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RoleGrantedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "role":
			v, err := scval.SymbolFromScVal(entry.Val)
			if err == nil {
				result.Role = v
			}
		case "account":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Account = v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		}
	}

	return result, nil
}

// WaitForRoleRevokedEvent waits for a RoleRevokedEvent event.
func (c *LinkTokenClient) WaitForRoleRevokedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RoleRevokedEvent) bool) (*RoleRevokedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RoleRevokedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseRoleRevokedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseRoleRevokedEvent(e protocolrpc.EventInfo) (*RoleRevokedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RoleRevokedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "role":
			v, err := scval.SymbolFromScVal(entry.Val)
			if err == nil {
				result.Role = v
			}
		case "account":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Account = v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerAddedEvent waits for a AuthorizedCallerAddedEvent event.
func (c *LinkTokenClient) WaitForAuthorizedCallerAddedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerAddedEvent) bool) (*AuthorizedCallerAddedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerAddedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAuthorizedCallerAddedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAuthorizedCallerAddedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerAddedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerAddedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerRemovedEvent waits for a AuthorizedCallerRemovedEvent event.
func (c *LinkTokenClient) WaitForAuthorizedCallerRemovedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerRemovedEvent) bool) (*AuthorizedCallerRemovedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerRemovedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAuthorizedCallerRemovedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAuthorizedCallerRemovedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerRemovedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerRemovedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransferStartedEvent waits for a OwnershipTransferStartedEvent event.
func (c *LinkTokenClient) WaitForOwnershipTransferStartedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransferStartedEvent) bool) (*OwnershipTransferStartedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferStartedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipTransferStartedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipTransferStartedEvent(e protocolrpc.EventInfo) (*OwnershipTransferStartedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransferStartedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "previous_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.PreviousOwner = v
			}
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		}
	}

	return result, nil
}

// WaitForBurnEvent waits for a BurnEvent event.
func (c *LinkTokenClient) WaitForBurnEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*BurnEvent) bool) (*BurnEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{BurnEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseBurnEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseBurnEvent(e protocolrpc.EventInfo) (*BurnEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &BurnEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "from":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.From = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForMintEvent waits for a MintEvent event.
func (c *LinkTokenClient) WaitForMintEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*MintEvent) bool) (*MintEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{MintEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseMintEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseMintEvent(e protocolrpc.EventInfo) (*MintEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &MintEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "to":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.To = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForApproveEvent waits for a ApproveEvent event.
func (c *LinkTokenClient) WaitForApproveEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ApproveEvent) bool) (*ApproveEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ApproveEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseApproveEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseApproveEvent(e protocolrpc.EventInfo) (*ApproveEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ApproveEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "from":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.From = v
			}
		case "spender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Spender = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		case "expiration_ledger":
			v, ok := entry.Val.GetU32()
			if ok {
				result.ExpirationLedger = uint32(v)
			}
		}
	}

	return result, nil
}

// WaitForSetAdminEvent waits for a SetAdminEvent event.
func (c *LinkTokenClient) WaitForSetAdminEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*SetAdminEvent) bool) (*SetAdminEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{SetAdminEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseSetAdminEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseSetAdminEvent(e protocolrpc.EventInfo) (*SetAdminEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &SetAdminEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "admin":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Admin = v
			}
		case "new_admin":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewAdmin = v
			}
		}
	}

	return result, nil
}

// WaitForTransferEvent waits for a TransferEvent event.
func (c *LinkTokenClient) WaitForTransferEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*TransferEvent) bool) (*TransferEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{TransferEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseTransferEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseTransferEvent(e protocolrpc.EventInfo) (*TransferEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &TransferEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "from":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.From = v
			}
		case "to":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.To = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForSetAuthorizedEvent waits for a SetAuthorizedEvent event.
func (c *LinkTokenClient) WaitForSetAuthorizedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*SetAuthorizedEvent) bool) (*SetAuthorizedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{SetAuthorizedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseSetAuthorizedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseSetAuthorizedEvent(e protocolrpc.EventInfo) (*SetAuthorizedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &SetAuthorizedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "id":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Id = v
			}
		case "authorize":
			v, ok := entry.Val.GetB()
			if ok {
				result.Authorize = v
			}
		}
	}

	return result, nil
}
