// Code generated by stellar-bindings-generator. DO NOT EDIT.
package lock_release_pool

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// LockReleasePoolClient provides methods to interact with the LockReleasePool contract.
type LockReleasePoolClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewLockReleasePoolClient creates a new LockReleasePoolClient.
func NewLockReleasePoolClient(invoker bindings.Invoker, contractID string) *LockReleasePoolClient {
	return &LockReleasePoolClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *LockReleasePoolClient) ContractID() string {
	return c.contractID
}

// Owner calls the owner function on the contract.
func (c *LockReleasePoolClient) Owner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// GetFee calls the get_fee function on the contract.
func (c *LockReleasePoolClient) GetFee(ctx context.Context, remoteChainSelector uint64) (*PoolFeeResult, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_fee", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_fee: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_fee")
	}

	return PoolFeeResultFromScVal(*result)
}

// IsOwner calls the is_owner function on the contract.
func (c *LockReleasePoolClient) IsOwner(ctx context.Context, addr string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_owner", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_owner: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_owner")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// GetToken calls the get_token function on the contract.
func (c *LockReleasePoolClient) GetToken(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token", args)
	if err != nil {
		return "", fmt.Errorf("failed to call get_token: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from get_token")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// GetRouter calls the get_router function on the contract.
func (c *LockReleasePoolClient) GetRouter(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_router", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_router: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_router")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// InitOwner calls the init_owner function on the contract.
func (c *LockReleasePoolClient) InitOwner(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call init_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// Initialize calls the initialize function on the contract.
func (c *LockReleasePoolClient) Initialize(ctx context.Context, owner string, token string, tokenDecimals uint32, router string, rampRegistry string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
		scval.AddressToScVal(token),
		scval.Uint32ToScVal(tokenDecimals),
		scval.AddressToScVal(router),
		scval.AddressToScVal(rampRegistry),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// SetRouter calls the set_router function on the contract.
func (c *LockReleasePoolClient) SetRouter(ctx context.Context, router string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(router),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_router", args)
	if err != nil {
		return fmt.Errorf("failed to call set_router: %w", err)
	}

	_ = result // void return
	return nil
}

// LockOrBurn calls the lock_or_burn function on the contract.
func (c *LockReleasePoolClient) LockOrBurn(ctx context.Context, caller string, input LockOrBurnIn, requestedFinality uint32) (*LockOrBurnOut, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.MustToScVal(input.ToScVal()),
		scval.Uint32ToScVal(requestedFinality),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "lock_or_burn", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call lock_or_burn: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from lock_or_burn")
	}

	return LockOrBurnOutFromScVal(*result)
}

// RequireOwner calls the require_owner function on the contract.
func (c *LockReleasePoolClient) RequireOwner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call require_owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from require_owner")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// SetNewOwner calls the set_new_owner function on the contract.
func (c *LockReleasePoolClient) SetNewOwner(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_new_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call set_new_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// GetRemotePool calls the get_remote_pool function on the contract.
func (c *LockReleasePoolClient) GetRemotePool(ctx context.Context, remoteChainSelector uint64) ([]byte, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_pool", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_pool: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_pool")
	}

	v, ok := result.GetBytes()
	if !ok {
		return nil, fmt.Errorf("expected bytes return type")
	}
	return []byte(v), nil
}

// ReleaseOrMint calls the release_or_mint function on the contract.
func (c *LockReleasePoolClient) ReleaseOrMint(ctx context.Context, caller string, input ReleaseOrMintIn, requestedFinality uint32) (*ReleaseOrMintOut, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(caller),
		scval.MustToScVal(input.ToScVal()),
		scval.Uint32ToScVal(requestedFinality),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "release_or_mint", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call release_or_mint: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from release_or_mint")
	}

	return ReleaseOrMintOutFromScVal(*result)
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *LockReleasePoolClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// GetRemoteToken calls the get_remote_token function on the contract.
func (c *LockReleasePoolClient) GetRemoteToken(ctx context.Context, remoteChainSelector uint64) ([]byte, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_token", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_token: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_token")
	}

	v, ok := result.GetBytes()
	if !ok {
		return nil, fmt.Errorf("expected bytes return type")
	}
	return []byte(v), nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *LockReleasePoolClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetPendingOwner calls the get_pending_owner function on the contract.
func (c *LockReleasePoolClient) GetPendingOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pending_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pending_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pending_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// GetRampRegistry calls the get_ramp_registry function on the contract.
func (c *LockReleasePoolClient) GetRampRegistry(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_ramp_registry", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_ramp_registry: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_ramp_registry")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// GetRequiredCcvs calls the get_required_ccvs function on the contract.
func (c *LockReleasePoolClient) GetRequiredCcvs(ctx context.Context, localToken string, remoteChainSelector uint64, amount int64, requestedFinality uint32, extraData []byte, direction MessageDirection) (*PoolRequiredCCVs, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(localToken),
		scval.Uint64ToScVal(remoteChainSelector),
		scval.I128ToScVal(amount),
		scval.Uint32ToScVal(requestedFinality),
		scval.BytesToScVal(extraData),
		scval.MustToScVal(direction.ToScVal()),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_required_ccvs", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_required_ccvs: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_required_ccvs")
	}

	return PoolRequiredCCVsFromScVal(*result)
}

// SetRampRegistry calls the set_ramp_registry function on the contract.
func (c *LockReleasePoolClient) SetRampRegistry(ctx context.Context, rampRegistry string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(rampRegistry),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_ramp_registry", args)
	if err != nil {
		return fmt.Errorf("failed to call set_ramp_registry: %w", err)
	}

	_ = result // void return
	return nil
}

// GetTokenDecimals calls the get_token_decimals function on the contract.
func (c *LockReleasePoolClient) GetTokenDecimals(ctx context.Context) (uint32, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_decimals", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_token_decimals: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_token_decimals")
	}

	v, ok := result.GetU32()
	if !ok {
		return 0, fmt.Errorf("expected u32 return type")
	}
	return uint32(v), nil
}

// IsSupportedChain calls the is_supported_chain function on the contract.
func (c *LockReleasePoolClient) IsSupportedChain(ctx context.Context, remoteChainSelector uint64) (bool, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_supported_chain", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_supported_chain: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_supported_chain")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// IsSupportedToken calls the is_supported_token function on the contract.
func (c *LockReleasePoolClient) IsSupportedToken(ctx context.Context, token string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_supported_token", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_supported_token: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_supported_token")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *LockReleasePoolClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// ApplyChainUpdates calls the apply_chain_updates function on the contract.
func (c *LockReleasePoolClient) ApplyChainUpdates(ctx context.Context, adds []ChainUpdate, removes []uint64) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(adds),
		scval.Uint64SliceToScVal(removes),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_chain_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_chain_updates: %w", err)
	}

	_ = result // void return
	return nil
}

// SetPoolFeeConfig calls the set_pool_fee_config function on the contract.
func (c *LockReleasePoolClient) SetPoolFeeConfig(ctx context.Context, remoteChainSelector uint64, config PoolFeeConfig) error {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
		scval.MustToScVal(config.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_pool_fee_config", args)
	if err != nil {
		return fmt.Errorf("failed to call set_pool_fee_config: %w", err)
	}

	_ = result // void return
	return nil
}

// GetRateLimitAdmin calls the get_rate_limit_admin function on the contract.
func (c *LockReleasePoolClient) GetRateLimitAdmin(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_rate_limit_admin", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_rate_limit_admin: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_rate_limit_admin")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// SetRateLimitAdmin calls the set_rate_limit_admin function on the contract.
func (c *LockReleasePoolClient) SetRateLimitAdmin(ctx context.Context, admin string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(admin),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_rate_limit_admin", args)
	if err != nil {
		return fmt.Errorf("failed to call set_rate_limit_admin: %w", err)
	}

	_ = result // void return
	return nil
}

// SetRateLimitConfig calls the set_rate_limit_config function on the contract.
func (c *LockReleasePoolClient) SetRateLimitConfig(ctx context.Context, remoteChainSelector uint64, outboundConfig RateLimitConfig, inboundConfig RateLimitConfig, fastFinality bool) error {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
		scval.MustToScVal(outboundConfig.ToScVal()),
		scval.MustToScVal(inboundConfig.ToScVal()),
		scval.BoolToScVal(fastFinality),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_rate_limit_config", args)
	if err != nil {
		return fmt.Errorf("failed to call set_rate_limit_config: %w", err)
	}

	_ = result // void return
	return nil
}

// GetAdvancedPoolHooks calls the get_advanced_pool_hooks function on the contract.
func (c *LockReleasePoolClient) GetAdvancedPoolHooks(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_advanced_pool_hooks", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_advanced_pool_hooks: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_advanced_pool_hooks")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// SetAdvancedPoolHooks calls the set_advanced_pool_hooks function on the contract.
func (c *LockReleasePoolClient) SetAdvancedPoolHooks(ctx context.Context, hooks string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(hooks),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_advanced_pool_hooks", args)
	if err != nil {
		return fmt.Errorf("failed to call set_advanced_pool_hooks: %w", err)
	}

	_ = result // void return
	return nil
}

// CancelOwnershipTransfer calls the cancel_ownership_transfer function on the contract.
func (c *LockReleasePoolClient) CancelOwnershipTransfer(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "cancel_ownership_transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call cancel_ownership_transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// RemoveAdvancedPoolHooks calls the remove_advanced_pool_hooks function on the contract.
func (c *LockReleasePoolClient) RemoveAdvancedPoolHooks(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "remove_advanced_pool_hooks", args)
	if err != nil {
		return fmt.Errorf("failed to call remove_advanced_pool_hooks: %w", err)
	}

	_ = result // void return
	return nil
}

// GetAllowedFinalityConfig calls the get_allowed_finality_config function on the contract.
func (c *LockReleasePoolClient) GetAllowedFinalityConfig(ctx context.Context) (uint32, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_allowed_finality_config", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_allowed_finality_config: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_allowed_finality_config")
	}

	v, ok := result.GetU32()
	if !ok {
		return 0, fmt.Errorf("expected u32 return type")
	}
	return uint32(v), nil
}

// SetAllowedFinalityConfig calls the set_allowed_finality_config function on the contract.
func (c *LockReleasePoolClient) SetAllowedFinalityConfig(ctx context.Context, allowedFinality uint32) error {
	args := []xdr.ScVal{
		scval.Uint32ToScVal(allowedFinality),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_allowed_finality_config", args)
	if err != nil {
		return fmt.Errorf("failed to call set_allowed_finality_config: %w", err)
	}

	_ = result // void return
	return nil
}

// GetCurrentRateLimiterState calls the get_current_rate_limiter_state function on the contract.
func (c *LockReleasePoolClient) GetCurrentRateLimiterState(ctx context.Context, remoteChainSelector uint64, fastFinality bool) (*RateLimiterState, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
		scval.BoolToScVal(fastFinality),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_current_rate_limiter_state", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_current_rate_limiter_state: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_current_rate_limiter_state")
	}

	return RateLimiterStateFromScVal(*result)
}

// WaitForRoleGrantedEvent waits for a RoleGrantedEvent event.
func (c *LockReleasePoolClient) WaitForRoleGrantedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RoleGrantedEvent) bool) (*RoleGrantedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RoleGrantedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseRoleGrantedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseRoleGrantedEvent(e protocolrpc.EventInfo) (*RoleGrantedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RoleGrantedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "role":
			v, err := scval.SymbolFromScVal(entry.Val)
			if err == nil {
				result.Role = v
			}
		case "account":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Account = v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		}
	}

	return result, nil
}

// WaitForRoleRevokedEvent waits for a RoleRevokedEvent event.
func (c *LockReleasePoolClient) WaitForRoleRevokedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RoleRevokedEvent) bool) (*RoleRevokedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RoleRevokedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseRoleRevokedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseRoleRevokedEvent(e protocolrpc.EventInfo) (*RoleRevokedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RoleRevokedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "role":
			v, err := scval.SymbolFromScVal(entry.Val)
			if err == nil {
				result.Role = v
			}
		case "account":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Account = v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerAddedEvent waits for a AuthorizedCallerAddedEvent event.
func (c *LockReleasePoolClient) WaitForAuthorizedCallerAddedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerAddedEvent) bool) (*AuthorizedCallerAddedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerAddedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAuthorizedCallerAddedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAuthorizedCallerAddedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerAddedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerAddedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerRemovedEvent waits for a AuthorizedCallerRemovedEvent event.
func (c *LockReleasePoolClient) WaitForAuthorizedCallerRemovedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerRemovedEvent) bool) (*AuthorizedCallerRemovedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerRemovedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAuthorizedCallerRemovedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAuthorizedCallerRemovedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerRemovedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerRemovedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransferStartedEvent waits for a OwnershipTransferStartedEvent event.
func (c *LockReleasePoolClient) WaitForOwnershipTransferStartedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransferStartedEvent) bool) (*OwnershipTransferStartedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferStartedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipTransferStartedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipTransferStartedEvent(e protocolrpc.EventInfo) (*OwnershipTransferStartedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransferStartedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "previous_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.PreviousOwner = v
			}
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		}
	}

	return result, nil
}

// WaitForBurnedEvent waits for a BurnedEvent event.
func (c *LockReleasePoolClient) WaitForBurnedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*BurnedEvent) bool) (*BurnedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{BurnedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseBurnedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseBurnedEvent(e protocolrpc.EventInfo) (*BurnedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &BurnedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForLockedEvent waits for a LockedEvent event.
func (c *LockReleasePoolClient) WaitForLockedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*LockedEvent) bool) (*LockedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{LockedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseLockedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseLockedEvent(e protocolrpc.EventInfo) (*LockedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &LockedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForMintedEvent waits for a MintedEvent event.
func (c *LockReleasePoolClient) WaitForMintedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*MintedEvent) bool) (*MintedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{MintedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseMintedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseMintedEvent(e protocolrpc.EventInfo) (*MintedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &MintedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "recipient":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Recipient = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForReleasedEvent waits for a ReleasedEvent event.
func (c *LockReleasePoolClient) WaitForReleasedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ReleasedEvent) bool) (*ReleasedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ReleasedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseReleasedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseReleasedEvent(e protocolrpc.EventInfo) (*ReleasedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ReleasedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "recipient":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Recipient = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForChainRemovedEvent waits for a ChainRemovedEvent event.
func (c *LockReleasePoolClient) WaitForChainRemovedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ChainRemovedEvent) bool) (*ChainRemovedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ChainRemovedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseChainRemovedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseChainRemovedEvent(e protocolrpc.EventInfo) (*ChainRemovedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ChainRemovedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		}
	}

	return result, nil
}

// WaitForChainConfiguredEvent waits for a ChainConfiguredEvent event.
func (c *LockReleasePoolClient) WaitForChainConfiguredEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ChainConfiguredEvent) bool) (*ChainConfiguredEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ChainConfiguredEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseChainConfiguredEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseChainConfiguredEvent(e protocolrpc.EventInfo) (*ChainConfiguredEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ChainConfiguredEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "remote_pool_address":
			v, ok := entry.Val.GetBytes()
			if ok {
				result.RemotePoolAddress = []byte(v)
			}
		case "remote_token_address":
			v, ok := entry.Val.GetBytes()
			if ok {
				result.RemoteTokenAddress = []byte(v)
			}
		case "outbound_rate_limiter_config":
			v, err := RateLimitConfigFromScVal(entry.Val)
			if err == nil {
				result.OutboundRateLimiterConfig = *v
			}
		case "inbound_rate_limiter_config":
			v, err := RateLimitConfigFromScVal(entry.Val)
			if err == nil {
				result.InboundRateLimiterConfig = *v
			}
		}
	}

	return result, nil
}

// WaitForFinalityConfigSetEvent waits for a FinalityConfigSetEvent event.
func (c *LockReleasePoolClient) WaitForFinalityConfigSetEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FinalityConfigSetEvent) bool) (*FinalityConfigSetEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FinalityConfigSetEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFinalityConfigSetEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFinalityConfigSetEvent(e protocolrpc.EventInfo) (*FinalityConfigSetEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FinalityConfigSetEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "allowed_finality":
			v, ok := entry.Val.GetU32()
			if ok {
				result.AllowedFinality = uint32(v)
			}
		}
	}

	return result, nil
}

// WaitForFtfInboundConsumedEvent waits for a FtfInboundConsumedEvent event.
func (c *LockReleasePoolClient) WaitForFtfInboundConsumedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FtfInboundConsumedEvent) bool) (*FtfInboundConsumedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FtfInboundConsumedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFtfInboundConsumedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFtfInboundConsumedEvent(e protocolrpc.EventInfo) (*FtfInboundConsumedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FtfInboundConsumedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForFtfOutboundConsumedEvent waits for a FtfOutboundConsumedEvent event.
func (c *LockReleasePoolClient) WaitForFtfOutboundConsumedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FtfOutboundConsumedEvent) bool) (*FtfOutboundConsumedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FtfOutboundConsumedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFtfOutboundConsumedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFtfOutboundConsumedEvent(e protocolrpc.EventInfo) (*FtfOutboundConsumedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FtfOutboundConsumedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForRateLimitConfiguredEvent waits for a RateLimitConfiguredEvent event.
func (c *LockReleasePoolClient) WaitForRateLimitConfiguredEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RateLimitConfiguredEvent) bool) (*RateLimitConfiguredEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RateLimitConfiguredEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseRateLimitConfiguredEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseRateLimitConfiguredEvent(e protocolrpc.EventInfo) (*RateLimitConfiguredEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RateLimitConfiguredEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "fast_finality":
			v, ok := entry.Val.GetB()
			if ok {
				result.FastFinality = v
			}
		case "outbound_config":
			v, err := RateLimitConfigFromScVal(entry.Val)
			if err == nil {
				result.OutboundConfig = *v
			}
		case "inbound_config":
			v, err := RateLimitConfigFromScVal(entry.Val)
			if err == nil {
				result.InboundConfig = *v
			}
		}
	}

	return result, nil
}

// WaitForAdvancedPoolHooksUpdatedEvent waits for a AdvancedPoolHooksUpdatedEvent event.
func (c *LockReleasePoolClient) WaitForAdvancedPoolHooksUpdatedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AdvancedPoolHooksUpdatedEvent) bool) (*AdvancedPoolHooksUpdatedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AdvancedPoolHooksUpdatedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAdvancedPoolHooksUpdatedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAdvancedPoolHooksUpdatedEvent(e protocolrpc.EventInfo) (*AdvancedPoolHooksUpdatedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AdvancedPoolHooksUpdatedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "old_hooks":
			v, err := scval.OptionalAddressFromScVal(entry.Val)
			if err == nil {
				result.OldHooks = v
			}
		case "new_hooks":
			v, err := scval.OptionalAddressFromScVal(entry.Val)
			if err == nil {
				result.NewHooks = v
			}
		}
	}

	return result, nil
}

// WaitForInboundRateLimitConsumedEvent waits for a InboundRateLimitConsumedEvent event.
func (c *LockReleasePoolClient) WaitForInboundRateLimitConsumedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*InboundRateLimitConsumedEvent) bool) (*InboundRateLimitConsumedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{InboundRateLimitConsumedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseInboundRateLimitConsumedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseInboundRateLimitConsumedEvent(e protocolrpc.EventInfo) (*InboundRateLimitConsumedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &InboundRateLimitConsumedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForOutboundRateLimitConsumedEvent waits for a OutboundRateLimitConsumedEvent event.
func (c *LockReleasePoolClient) WaitForOutboundRateLimitConsumedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OutboundRateLimitConsumedEvent) bool) (*OutboundRateLimitConsumedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OutboundRateLimitConsumedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOutboundRateLimitConsumedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOutboundRateLimitConsumedEvent(e protocolrpc.EventInfo) (*OutboundRateLimitConsumedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OutboundRateLimitConsumedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}
