[workspace]
resolver = "2"
members = [
    "data-feeds-common",
    "data-feeds-cache",
    "data-feeds-proxy",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.dependencies]
soroban-sdk = "=26.1.0"
stellar-access = "=0.7.2"
data-feeds-common = { path = "data-feeds-common" }
data-feeds-cache = { path = "data-feeds-cache", default-features = false }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
