// Code generated by stellar-bindings-generator. DO NOT EDIT.
package offramp

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// OffRampClient provides methods to interact with the OffRamp contract.
type OffRampClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewOffRampClient creates a new OffRampClient.
func NewOffRampClient(invoker bindings.Invoker, contractID string) *OffRampClient {
	return &OffRampClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *OffRampClient) ContractID() string {
	return c.contractID
}

// Init calls the init function on the contract.
func (c *OffRampClient) Init(ctx context.Context, rmnProxy string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(rmnProxy),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init", args)
	if err != nil {
		return fmt.Errorf("failed to call init: %w", err)
	}

	_ = result // void return
	return nil
}

// Owner calls the owner function on the contract.
func (c *OffRampClient) Owner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// Execute calls the execute function on the contract.
func (c *OffRampClient) Execute(ctx context.Context, encodedMessage []byte, ccvs []string, verifierResults [][]byte, gasLimitOverride uint32) error {
	args := []xdr.ScVal{
		scval.BytesToScVal(encodedMessage),
		scval.AddressSliceToScVal(ccvs),
		scval.BytesSliceToScVal(verifierResults),
		scval.Uint32ToScVal(gasLimitOverride),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "execute", args)
	if err != nil {
		return fmt.Errorf("failed to call execute: %w", err)
	}

	_ = result // void return
	return nil
}

// IsOwner calls the is_owner function on the contract.
func (c *OffRampClient) IsOwner(ctx context.Context, addr string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_owner", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_owner: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_owner")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// IsCursed calls the is_cursed function on the contract.
func (c *OffRampClient) IsCursed(ctx context.Context) (bool, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_cursed", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_cursed: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_cursed")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// InitOwner calls the init_owner function on the contract.
func (c *OffRampClient) InitOwner(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call init_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// Initialize calls the initialize function on the contract.
func (c *OffRampClient) Initialize(ctx context.Context, owner string, staticConfig StaticConfig) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
		scval.MustToScVal(staticConfig.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// RequireOwner calls the require_owner function on the contract.
func (c *OffRampClient) RequireOwner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call require_owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from require_owner")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// SetNewOwner calls the set_new_owner function on the contract.
func (c *OffRampClient) SetNewOwner(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_new_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call set_new_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *OffRampClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *OffRampClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetPendingOwner calls the get_pending_owner function on the contract.
func (c *OffRampClient) GetPendingOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pending_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pending_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pending_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// GetStaticConfig calls the get_static_config function on the contract.
func (c *OffRampClient) GetStaticConfig(ctx context.Context) (*StaticConfig, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_static_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_static_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_static_config")
	}

	return StaticConfigFromScVal(*result)
}

// IsSubjectCursed calls the is_subject_cursed function on the contract.
func (c *OffRampClient) IsSubjectCursed(ctx context.Context, subject [16]byte) (bool, error) {
	args := []xdr.ScVal{
		scval.Bytes16ToScVal(subject),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_subject_cursed", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_subject_cursed: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_subject_cursed")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// RequireNotCursed calls the require_not_cursed function on the contract.
func (c *OffRampClient) RequireNotCursed(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_not_cursed", args)
	if err != nil {
		return fmt.Errorf("failed to call require_not_cursed: %w", err)
	}

	_ = result // void return
	return nil
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *OffRampClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// GetExecutionState calls the get_execution_state function on the contract.
func (c *OffRampClient) GetExecutionState(ctx context.Context, messageId [32]byte) (MessageExecutionState, error) {
	args := []xdr.ScVal{
		scval.Bytes32ToScVal(messageId),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_execution_state", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_execution_state: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_execution_state")
	}

	return MessageExecutionStateFromScVal(*result)
}

// GetSourceChainConfig calls the get_source_chain_config function on the contract.
func (c *OffRampClient) GetSourceChainConfig(ctx context.Context, sourceChainSelector uint64) (*SourceChainConfig, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(sourceChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_source_chain_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_source_chain_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_source_chain_config")
	}

	return SourceChainConfigFromScVal(*result)
}

// RequireChainNotCursed calls the require_chain_not_cursed function on the contract.
func (c *OffRampClient) RequireChainNotCursed(ctx context.Context, chainSelector uint64) error {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(chainSelector),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_chain_not_cursed", args)
	if err != nil {
		return fmt.Errorf("failed to call require_chain_not_cursed: %w", err)
	}

	_ = result // void return
	return nil
}

// CancelOwnershipTransfer calls the cancel_ownership_transfer function on the contract.
func (c *OffRampClient) CancelOwnershipTransfer(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "cancel_ownership_transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call cancel_ownership_transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// ExtendExecutionStateTtl calls the extend_execution_state_ttl function on the contract.
func (c *OffRampClient) ExtendExecutionStateTtl(ctx context.Context, messageId [32]byte) error {
	args := []xdr.ScVal{
		scval.Bytes32ToScVal(messageId),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "extend_execution_state_ttl", args)
	if err != nil {
		return fmt.Errorf("failed to call extend_execution_state_ttl: %w", err)
	}

	_ = result // void return
	return nil
}

// RequireSubjectNotCursed calls the require_subject_not_cursed function on the contract.
func (c *OffRampClient) RequireSubjectNotCursed(ctx context.Context, subject [16]byte) error {
	args := []xdr.ScVal{
		scval.Bytes16ToScVal(subject),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_subject_not_cursed", args)
	if err != nil {
		return fmt.Errorf("failed to call require_subject_not_cursed: %w", err)
	}

	_ = result // void return
	return nil
}

// GetAllSourceChainConfigs calls the get_all_source_chain_configs function on the contract.
func (c *OffRampClient) GetAllSourceChainConfigs(ctx context.Context) ([]uint64, []SourceChainConfig, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_all_source_chain_configs", args)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to call get_all_source_chain_configs: %w", err)
	}

	if result == nil {
		return nil, nil, fmt.Errorf("no return value from get_all_source_chain_configs")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, nil, fmt.Errorf("expected vec for tuple return")
	}
	if len(*vec) != 2 {
		return nil, nil, fmt.Errorf("expected 2 elements, got %d", len(*vec))
	}

	v0Vec, ok := (*vec)[0].GetVec()
	if !ok || v0Vec == nil {
		return nil, nil, fmt.Errorf("tuple[0]: expected vec")
	}
	v0 := make([]uint64, len(*v0Vec))
	for i, item := range *v0Vec {
		val, err := scval.Uint64FromScVal(item)
		if err != nil {
			return nil, nil, fmt.Errorf("tuple[0][%d]: %w", i, err)
		}
		v0[i] = val
	}

	v1Vec, ok := (*vec)[1].GetVec()
	if !ok || v1Vec == nil {
		return nil, nil, fmt.Errorf("tuple[1]: expected vec")
	}
	v1 := make([]SourceChainConfig, len(*v1Vec))
	for i, item := range *v1Vec {
		val, err := SourceChainConfigFromScVal(item)
		if err != nil {
			return nil, nil, fmt.Errorf("tuple[1][%d]: %w", i, err)
		}
		v1[i] = *val
	}

	return v0, v1, nil
}

// ApplySourceChainCfgUpdates calls the apply_source_chain_cfg_updates function on the contract.
func (c *OffRampClient) ApplySourceChainCfgUpdates(ctx context.Context, sourceChainConfigArgs []SourceChainConfigArgs) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(sourceChainConfigArgs),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_source_chain_cfg_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_source_chain_cfg_updates: %w", err)
	}

	_ = result // void return
	return nil
}

// WaitForRoleGrantedEvent waits for a RoleGrantedEvent event.
func (c *OffRampClient) WaitForRoleGrantedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RoleGrantedEvent) bool) (*RoleGrantedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RoleGrantedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseRoleGrantedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseRoleGrantedEvent(e protocolrpc.EventInfo) (*RoleGrantedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RoleGrantedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "role":
			v, err := scval.SymbolFromScVal(entry.Val)
			if err == nil {
				result.Role = v
			}
		case "account":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Account = v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		}
	}

	return result, nil
}

// WaitForRoleRevokedEvent waits for a RoleRevokedEvent event.
func (c *OffRampClient) WaitForRoleRevokedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RoleRevokedEvent) bool) (*RoleRevokedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RoleRevokedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseRoleRevokedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseRoleRevokedEvent(e protocolrpc.EventInfo) (*RoleRevokedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RoleRevokedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "role":
			v, err := scval.SymbolFromScVal(entry.Val)
			if err == nil {
				result.Role = v
			}
		case "account":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Account = v
			}
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerAddedEvent waits for a AuthorizedCallerAddedEvent event.
func (c *OffRampClient) WaitForAuthorizedCallerAddedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerAddedEvent) bool) (*AuthorizedCallerAddedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerAddedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAuthorizedCallerAddedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAuthorizedCallerAddedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerAddedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerAddedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForAuthorizedCallerRemovedEvent waits for a AuthorizedCallerRemovedEvent event.
func (c *OffRampClient) WaitForAuthorizedCallerRemovedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*AuthorizedCallerRemovedEvent) bool) (*AuthorizedCallerRemovedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{AuthorizedCallerRemovedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseAuthorizedCallerRemovedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseAuthorizedCallerRemovedEvent(e protocolrpc.EventInfo) (*AuthorizedCallerRemovedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &AuthorizedCallerRemovedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "caller":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Caller = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransferStartedEvent waits for a OwnershipTransferStartedEvent event.
func (c *OffRampClient) WaitForOwnershipTransferStartedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransferStartedEvent) bool) (*OwnershipTransferStartedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferStartedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipTransferStartedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipTransferStartedEvent(e protocolrpc.EventInfo) (*OwnershipTransferStartedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransferStartedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "previous_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.PreviousOwner = v
			}
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		}
	}

	return result, nil
}

// WaitForStaticConfigSetEvent waits for a StaticConfigSetEvent event.
func (c *OffRampClient) WaitForStaticConfigSetEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*StaticConfigSetEvent) bool) (*StaticConfigSetEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{StaticConfigSetEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseStaticConfigSetEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseStaticConfigSetEvent(e protocolrpc.EventInfo) (*StaticConfigSetEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &StaticConfigSetEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "static_config":
			v, err := StaticConfigFromScVal(entry.Val)
			if err == nil {
				result.StaticConfig = *v
			}
		}
	}

	return result, nil
}

// WaitForSourceChainConfigSetEvent waits for a SourceChainConfigSetEvent event.
func (c *OffRampClient) WaitForSourceChainConfigSetEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*SourceChainConfigSetEvent) bool) (*SourceChainConfigSetEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{SourceChainConfigSetEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseSourceChainConfigSetEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseSourceChainConfigSetEvent(e protocolrpc.EventInfo) (*SourceChainConfigSetEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &SourceChainConfigSetEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "source_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.SourceChainSelector = v
			}
		case "source_config":
			v, err := SourceChainConfigFromScVal(entry.Val)
			if err == nil {
				result.SourceConfig = *v
			}
		}
	}

	return result, nil
}

// WaitForExecutionStateChangedEvent waits for a ExecutionStateChangedEvent event.
func (c *OffRampClient) WaitForExecutionStateChangedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ExecutionStateChangedEvent) bool) (*ExecutionStateChangedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ExecutionStateChangedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseExecutionStateChangedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseExecutionStateChangedEvent(e protocolrpc.EventInfo) (*ExecutionStateChangedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ExecutionStateChangedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "source_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.SourceChainSelector = v
			}
		case "sequence_number":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.SequenceNumber = v
			}
		case "message_id":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err == nil {
				result.MessageId = v
			}
		case "state":
			v, err := MessageExecutionStateFromScVal(entry.Val)
			if err == nil {
				result.State = v
			}
		case "return_data":
			v, ok := entry.Val.GetBytes()
			if ok {
				result.ReturnData = []byte(v)
			}
		}
	}

	return result, nil
}
