package main

import (
	"fmt"
	"strings"
)

// GenerateClient generates the client.go file content.
func GenerateClient(pkg string, contract *Contract) string {
	var b strings.Builder

	b.WriteString("// Code generated by stellar-bindings-generator. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg))

	// Imports
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	if len(contract.Events) > 0 {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"github.com/smartcontractkit/chainlink-stellar/bindings\"\n")
	b.WriteString("\t\"github.com/smartcontractkit/chainlink-stellar/bindings/scval\"\n")
	if len(contract.Events) > 0 {
		b.WriteString("\tprotocolrpc \"github.com/stellar/go-stellar-sdk/protocols/rpc\"\n")
	}
	b.WriteString("\t\"github.com/stellar/go-stellar-sdk/xdr\"\n")
	b.WriteString(")\n\n")

	// Generate client struct
	generateClientStruct(&b, contract)

	// Generate constructor
	generateConstructor(&b, contract)

	// Generate methods for each function
	for _, fn := range contract.Functions {
		generateMethod(&b, contract, fn)
	}

	// Generate event helpers
	generateEventHelpers(&b, contract)

	return b.String()
}

func generateClientStruct(b *strings.Builder, contract *Contract) {
	b.WriteString(fmt.Sprintf("// %sClient provides methods to interact with the %s contract.\n", contract.Name, contract.Name))
	b.WriteString(fmt.Sprintf("type %sClient struct {\n", contract.Name))
	b.WriteString("\tinvoker    bindings.Invoker\n")
	b.WriteString("\tcontractID string\n")
	b.WriteString("}\n\n")
}

func generateConstructor(b *strings.Builder, contract *Contract) {
	b.WriteString(fmt.Sprintf("// New%sClient creates a new %sClient.\n", contract.Name, contract.Name))
	b.WriteString(fmt.Sprintf("func New%sClient(invoker bindings.Invoker, contractID string) *%sClient {\n", contract.Name, contract.Name))
	b.WriteString(fmt.Sprintf("\treturn &%sClient{\n", contract.Name))
	b.WriteString("\t\tinvoker:    invoker,\n")
	b.WriteString("\t\tcontractID: contractID,\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// ContractID getter
	b.WriteString("// ContractID returns the contract ID.\n")
	b.WriteString(fmt.Sprintf("func (c *%sClient) ContractID() string {\n", contract.Name))
	b.WriteString("\treturn c.contractID\n")
	b.WriteString("}\n\n")
}

func generateMethod(b *strings.Builder, contract *Contract, fn Function) {
	methodName := snakeToPascal(fn.Name)

	// Determine if this is a read-only method (getter) or a state-changing method
	isReadOnly := isReadOnlyFunction(fn)

	// Parse return type
	returnType, returnsValue := parseReturnType(fn.Returns)

	// Generate method signature
	b.WriteString(fmt.Sprintf("// %s calls the %s function on the contract.\n", methodName, fn.Name))

	// Build parameter list
	params := []string{"ctx context.Context"}
	for _, input := range fn.Inputs {
		goType := rustTypeToGo(input.Type)
		params = append(params, fmt.Sprintf("%s %s", snakeToCamel(input.Name), goType))
	}

	// Build return type
	var returns string
	if returnsValue {
		if isTupleType(returnType) {
			var goTypes []string
			for _, t := range parseTupleTypes(returnType) {
				gt := rustTypeToGo(t)
				if !strings.HasPrefix(t, "Option<") && isStructType(t) {
					gt = "*" + gt
				}
				goTypes = append(goTypes, gt)
			}
			returns = fmt.Sprintf("(%s, error)", strings.Join(goTypes, ", "))
		} else {
			goReturnType := rustTypeToGo(returnType)
			if strings.HasPrefix(returnType, "Option<") {
				// rustTypeToGo already returns *T for Option<T>, no extra * needed
				returns = fmt.Sprintf("(%s, error)", goReturnType)
			} else if isStructType(returnType) {
				returns = fmt.Sprintf("(*%s, error)", goReturnType)
			} else {
				returns = fmt.Sprintf("(%s, error)", goReturnType)
			}
		}
	} else {
		returns = "error"
	}

	b.WriteString(fmt.Sprintf("func (c *%sClient) %s(%s) %s {\n", contract.Name, methodName, strings.Join(params, ", "), returns))

	// Build args slice
	if len(fn.Inputs) > 0 {
		b.WriteString("\targs := []xdr.ScVal{\n")
		for _, input := range fn.Inputs {
			converter := getArgConverter(input.Type, snakeToCamel(input.Name))
			b.WriteString(fmt.Sprintf("\t\t%s,\n", converter))
		}
		b.WriteString("\t}\n\n")
	} else {
		b.WriteString("\targs := []xdr.ScVal{}\n\n")
	}

	// Call invoke or simulate
	if isReadOnly {
		b.WriteString(fmt.Sprintf("\tresult, err := c.invoker.SimulateContract(ctx, c.contractID, \"%s\", args)\n", fn.Name))
	} else {
		b.WriteString(fmt.Sprintf("\tresult, err := c.invoker.InvokeContract(ctx, c.contractID, \"%s\", args)\n", fn.Name))
	}

	b.WriteString("\tif err != nil {\n")
	if returnsValue {
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"failed to call %s: %%w\", err)\n", zeroValue(returnType), fn.Name))
	} else {
		b.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to call %s: %%w\", err)\n", fn.Name))
	}
	b.WriteString("\t}\n\n")

	// Handle return value
	if returnsValue {
		b.WriteString("\tif result == nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"no return value from %s\")\n", zeroValue(returnType), fn.Name))
		b.WriteString("\t}\n\n")

		generateReturnValueParsing(b, returnType)
	} else {
		b.WriteString("\t_ = result // void return\n")
		b.WriteString("\treturn nil\n")
	}

	b.WriteString("}\n\n")
}

func generateReturnValueParsing(b *strings.Builder, returnType string) {
	switch {
	case returnType == "u64":
		b.WriteString("\tv, err := scval.Uint64FromScVal(*result)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn 0, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn v, nil\n")
	case returnType == "u32":
		b.WriteString("\tv, ok := result.GetU32()\n")
		b.WriteString("\tif !ok {\n")
		b.WriteString("\t\treturn 0, fmt.Errorf(\"expected u32 return type\")\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn uint32(v), nil\n")
	case returnType == "i128":
		b.WriteString("\tv, err := scval.I128FromScVal(*result)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn 0, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn v, nil\n")
	case returnType == "bool":
		b.WriteString("\tv, ok := result.GetB()\n")
		b.WriteString("\tif !ok {\n")
		b.WriteString("\t\treturn false, fmt.Errorf(\"expected bool return type\")\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn v, nil\n")
	case returnType == "soroban_sdk::Address":
		b.WriteString("\tv, err := scval.AddressFromScVal(*result)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn \"\", err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn v, nil\n")
	case returnType == "soroban_sdk::Bytes":
		b.WriteString("\tv, ok := result.GetBytes()\n")
		b.WriteString("\tif !ok {\n")
		b.WriteString("\t\treturn nil, fmt.Errorf(\"expected bytes return type\")\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn []byte(v), nil\n")
	case strings.Contains(returnType, "Option<") && strings.Contains(returnType, "soroban_sdk::Address"):
		b.WriteString("\tv, err := scval.OptionalAddressFromScVal(*result)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn nil, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn v, nil\n")
	case strings.HasPrefix(returnType, "Option<"):
		innerType := strings.TrimSuffix(strings.TrimPrefix(returnType, "Option<"), ">")
		innerType = strings.TrimSpace(innerType)
		structName := extractStructName(innerType)
		b.WriteString("\tif result.Type == xdr.ScValTypeScvVoid {\n")
		b.WriteString("\t\treturn nil, nil\n")
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\tv, err := %sFromScVal(*result)\n", structName))
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn nil, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn v, nil\n")
	case returnType == "u128":
		b.WriteString("\tv, err := scval.U128FromScVal(*result)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn scval.U128{}, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn v, nil\n")
	case strings.HasPrefix(returnType, "soroban_sdk::BytesN<"):
		n := extractBytesNSize(returnType)
		b.WriteString(fmt.Sprintf("\tv, err := scval.Bytes%dFromScVal(*result)\n", n))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn [%d]byte{}, err\n", n))
		b.WriteString("\t}\n")
		b.WriteString("\treturn v, nil\n")
	case strings.HasPrefix(returnType, "soroban_sdk::Vec<"):
		innerType := extractVecInnerType(returnType)
		if innerType == "soroban_sdk::Address" {
			b.WriteString("\tvec, ok := result.GetVec()\n")
			b.WriteString("\tif !ok || vec == nil {\n")
			b.WriteString("\t\treturn nil, fmt.Errorf(\"expected vec return type\")\n")
			b.WriteString("\t}\n")
			b.WriteString("\tout := make([]string, len(*vec))\n")
			b.WriteString("\tfor i, item := range *vec {\n")
			b.WriteString("\t\tv, err := scval.AddressFromScVal(item)\n")
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString("\t\t\treturn nil, err\n")
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tout[i] = v\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn out, nil\n")
		} else if innerType == "soroban_sdk::Bytes" {
			b.WriteString("\tvec, ok := result.GetVec()\n")
			b.WriteString("\tif !ok || vec == nil {\n")
			b.WriteString("\t\treturn nil, fmt.Errorf(\"expected vec return type\")\n")
			b.WriteString("\t}\n")
			b.WriteString("\tout := make([][]byte, len(*vec))\n")
			b.WriteString("\tfor i, item := range *vec {\n")
			b.WriteString("\t\tv, ok := item.GetBytes()\n")
			b.WriteString("\t\tif !ok {\n")
			b.WriteString("\t\t\treturn nil, fmt.Errorf(\"vec item is not bytes\")\n")
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tout[i] = []byte(v)\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn out, nil\n")
		} else if n := extractBytesNSize(innerType); n > 0 {
			goType := rustTypeToGo(innerType)
			b.WriteString("\tvec, ok := result.GetVec()\n")
			b.WriteString("\tif !ok || vec == nil {\n")
			b.WriteString("\t\treturn nil, fmt.Errorf(\"expected vec return type\")\n")
			b.WriteString("\t}\n")
			b.WriteString(fmt.Sprintf("\tout := make([]%s, len(*vec))\n", goType))
			b.WriteString("\tfor i, item := range *vec {\n")
			b.WriteString(fmt.Sprintf("\t\tv, err := scval.Bytes%dFromScVal(item)\n", n))
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString("\t\t\treturn nil, err\n")
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tout[i] = v\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn out, nil\n")
		} else {
			structName := extractStructName(innerType)
			b.WriteString("\tvec, ok := result.GetVec()\n")
			b.WriteString("\tif !ok || vec == nil {\n")
			b.WriteString("\t\treturn nil, fmt.Errorf(\"expected vec return type\")\n")
			b.WriteString("\t}\n")
			b.WriteString(fmt.Sprintf("\tout := make([]%s, len(*vec))\n", structName))
			b.WriteString("\tfor i, item := range *vec {\n")
			b.WriteString(fmt.Sprintf("\t\tv, err := %sFromScVal(item)\n", structName))
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString("\t\t\treturn nil, err\n")
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tout[i] = *v\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn out, nil\n")
		}
	case isTupleType(returnType):
		types := parseTupleTypes(returnType)
		zeros := zeroValue(returnType)
		b.WriteString("\tvec, ok := result.GetVec()\n")
		b.WriteString("\tif !ok || vec == nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"expected vec for tuple return\")\n", zeros))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\tif len(*vec) != %d {\n", len(types)))
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"expected %d elements, got %%d\", len(*vec))\n", zeros, len(types)))
		b.WriteString("\t}\n\n")
		for i, t := range types {
			generateTupleElementParsing(b, t, i, zeros)
		}
		var retVars []string
		for i := range types {
			retVars = append(retVars, fmt.Sprintf("v%d", i))
		}
		b.WriteString(fmt.Sprintf("\treturn %s, nil\n", strings.Join(retVars, ", ")))
	default:
		// Struct type
		structName := extractStructName(returnType)
		b.WriteString(fmt.Sprintf("\treturn %sFromScVal(*result)\n", structName))
	}
}

func generateEventHelpers(b *strings.Builder, contract *Contract) {
	if len(contract.Events) == 0 {
		return
	}

	// Generate WaitForEvent helper
	for _, event := range contract.Events {
		b.WriteString(fmt.Sprintf("// WaitFor%s waits for a %s event.\n", event.Name, event.Name))
		b.WriteString(fmt.Sprintf("func (c *%sClient) WaitFor%s(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*%s) bool) (*%s, error) {\n",
			contract.Name, event.Name, event.Name, event.Name))
		b.WriteString("\tstartTime := time.Now()\n")
		b.WriteString("\tticker := time.NewTicker(2 * time.Second)\n")
		b.WriteString("\tdefer ticker.Stop()\n\n")
		b.WriteString("\tfor {\n")
		b.WriteString("\t\tselect {\n")
		b.WriteString("\t\tcase <-ctx.Done():\n")
		b.WriteString("\t\t\treturn nil, ctx.Err()\n")
		b.WriteString("\t\tcase <-ticker.C:\n")
		b.WriteString("\t\t\tif time.Since(startTime) > timeout {\n")
		b.WriteString("\t\t\t\treturn nil, fmt.Errorf(\"timeout waiting for event\")\n")
		b.WriteString("\t\t\t}\n\n")
		b.WriteString(fmt.Sprintf("\t\t\tevents, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{%sTopic})\n", event.Name))
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\tcontinue\n")
		b.WriteString("\t\t\t}\n\n")
		b.WriteString("\t\t\tfor _, e := range events {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\tparsed, err := parse%s(e)\n", event.Name))
		b.WriteString("\t\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\t\tcontinue\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString("\t\t\t\tif filter == nil || filter(parsed) {\n")
		b.WriteString("\t\t\t\t\treturn parsed, nil\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		// Generate event parser
		generateEventParser(b, event)
	}
}

func generateEventParser(b *strings.Builder, event Event) {
	b.WriteString(fmt.Sprintf("func parse%s(e protocolrpc.EventInfo) (*%s, error) {\n", event.Name, event.Name))
	b.WriteString("\tvar eventVal xdr.ScVal\n")
	b.WriteString("\tif err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"failed to decode event: %w\", err)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tscMap, ok := eventVal.GetMap()\n")
	b.WriteString("\tif !ok || scMap == nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"event is not a map\")\n")
	b.WriteString("\t}\n\n")
	b.WriteString(fmt.Sprintf("\tresult := &%s{\n", event.Name))
	b.WriteString("\t\tLedger: uint32(e.Ledger),\n")
	b.WriteString("\t\tTxHash: e.TransactionHash,\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tfor _, entry := range *scMap {\n")
	b.WriteString("\t\tkey, ok := entry.Key.GetSym()\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n\n")
	b.WriteString("\t\tswitch string(key) {\n")

	for _, f := range event.Fields {
		b.WriteString(fmt.Sprintf("\t\tcase \"%s\":\n", f.Name))
		generateEventFieldParsing(b, f, "result."+snakeToPascal(f.Name))
	}

	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn result, nil\n")
	b.WriteString("}\n\n")
}

func generateEventFieldParsing(b *strings.Builder, f Field, target string) {
	switch {
	case f.Type == "u64":
		b.WriteString("\t\t\tv, err := scval.Uint64FromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err == nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
		b.WriteString("\t\t\t}\n")
	case f.Type == "u128":
		b.WriteString("\t\t\tv, err := scval.U128FromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err == nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
		b.WriteString("\t\t\t}\n")
	case f.Type == "i128":
		b.WriteString("\t\t\tv, err := scval.I128FromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err == nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
		b.WriteString("\t\t\t}\n")
	case f.Type == "soroban_sdk::Address":
		b.WriteString("\t\t\tv, err := scval.AddressFromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err == nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
		b.WriteString("\t\t\t}\n")
	case f.Type == "soroban_sdk::Symbol":
		b.WriteString("\t\t\tv, err := scval.SymbolFromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err == nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
		b.WriteString("\t\t\t}\n")
	case f.Type == "soroban_sdk::Bytes":
		b.WriteString("\t\t\tv, ok := entry.Val.GetBytes()\n")
		b.WriteString("\t\t\tif ok {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = []byte(v)\n", target))
		b.WriteString("\t\t\t}\n")
	case strings.HasPrefix(f.Type, "soroban_sdk::BytesN<"):
		n := extractBytesNSize(f.Type)
		b.WriteString(fmt.Sprintf("\t\t\tv, err := scval.Bytes%dFromScVal(entry.Val)\n", n))
		b.WriteString("\t\t\tif err == nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
		b.WriteString("\t\t\t}\n")
	case strings.HasPrefix(f.Type, "soroban_sdk::Vec<"):
		innerType := extractVecInnerType(f.Type)
		b.WriteString("\t\t\tvec, ok := entry.Val.GetVec()\n")
		b.WriteString("\t\t\tif ok && vec != nil {\n")
		if innerType == "soroban_sdk::Address" {
			b.WriteString(fmt.Sprintf("\t\t\t\tparsed := make([]string, len(*vec))\n"))
			b.WriteString("\t\t\t\tfor i, item := range *vec {\n")
			b.WriteString("\t\t\t\t\tv, err := scval.AddressFromScVal(item)\n")
			b.WriteString("\t\t\t\t\tif err == nil {\n")
			b.WriteString("\t\t\t\t\t\tparsed[i] = v\n")
			b.WriteString("\t\t\t\t\t}\n")
			b.WriteString("\t\t\t\t}\n")
		} else if innerType == "soroban_sdk::Bytes" {
			b.WriteString("\t\t\t\tparsed := make([][]byte, len(*vec))\n")
			b.WriteString("\t\t\t\tfor i, item := range *vec {\n")
			b.WriteString("\t\t\t\t\tv, ok := item.GetBytes()\n")
			b.WriteString("\t\t\t\t\tif ok {\n")
			b.WriteString("\t\t\t\t\t\tparsed[i] = []byte(v)\n")
			b.WriteString("\t\t\t\t\t}\n")
			b.WriteString("\t\t\t\t}\n")
		} else if n := extractBytesNSize(innerType); n > 0 {
			goType := rustTypeToGo(innerType)
			b.WriteString(fmt.Sprintf("\t\t\t\tparsed := make([]%s, len(*vec))\n", goType))
			b.WriteString("\t\t\t\tfor i, item := range *vec {\n")
			b.WriteString(fmt.Sprintf("\t\t\t\t\tv, err := scval.Bytes%dFromScVal(item)\n", n))
			b.WriteString("\t\t\t\t\tif err == nil {\n")
			b.WriteString("\t\t\t\t\t\tparsed[i] = v\n")
			b.WriteString("\t\t\t\t\t}\n")
			b.WriteString("\t\t\t\t}\n")
		} else {
			goType := rustTypeToGo(innerType)
			b.WriteString(fmt.Sprintf("\t\t\t\tparsed := make([]%s, 0, len(*vec))\n", goType))
			b.WriteString("\t\t\t\tfor _, item := range *vec {\n")
			structName := extractStructName(innerType)
			b.WriteString(fmt.Sprintf("\t\t\t\t\tv, err := %sFromScVal(item)\n", structName))
			b.WriteString("\t\t\t\t\tif err == nil {\n")
			b.WriteString("\t\t\t\t\t\tparsed = append(parsed, *v)\n")
			b.WriteString("\t\t\t\t\t}\n")
			b.WriteString("\t\t\t\t}\n")
		}
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = parsed\n", target))
		b.WriteString("\t\t\t}\n")
	default:
		b.WriteString("\t\t\t// TODO: parse complex type\n")
	}
}

// Helper functions

func isReadOnlyFunction(fn Function) bool {
	name := strings.ToLower(fn.Name)
	return strings.HasPrefix(name, "get_") ||
		strings.HasPrefix(name, "is_") ||
		name == "owner" ||
		name == "balance"
}

func parseReturnType(returnStr string) (string, bool) {
	returnStr = strings.TrimSpace(returnStr)

	if returnStr == "" {
		return "", false
	}

	// Option<InnerType> - return full type so rustTypeToGo can produce *string
	if strings.HasPrefix(returnStr, "Option<") {
		return returnStr, true
	} else if strings.HasPrefix(returnStr, "Result<") {
		// Result<RetType, Error> or Result<(), Error>
		inner := strings.TrimSuffix(strings.TrimPrefix(returnStr, "Result<"), ">")
		parts := splitReturnType(inner)
		if len(parts) >= 1 {
			okType := strings.TrimSpace(parts[0])
			if okType == "()" {
				return "", false
			}
			if strings.HasPrefix(okType, "(") {
				return okType, true
			}
			return okType, true
		}
	}

	return returnStr, true
}

func splitReturnType(s string) []string {
	// Split by comma but handle nested generics
	var result []string
	var current strings.Builder
	depth := 0

	for _, ch := range s {
		switch ch {
		case '<', '(':
			depth++
			current.WriteRune(ch)
		case '>', ')':
			depth--
			current.WriteRune(ch)
		case ',':
			if depth == 0 {
				result = append(result, strings.TrimSpace(current.String()))
				current.Reset()
			} else {
				current.WriteRune(ch)
			}
		default:
			current.WriteRune(ch)
		}
	}

	if s := strings.TrimSpace(current.String()); s != "" {
		result = append(result, s)
	}

	return result
}

func isStructType(rustType string) bool {
	// Check if it's a custom struct (not a primitive or SDK type)
	switch rustType {
	case "u64", "u32", "u128", "i128", "bool":
		return false
	case "soroban_sdk::Address", "soroban_sdk::Bytes", "soroban_sdk::Symbol":
		return false
	}
	if strings.HasPrefix(rustType, "soroban_sdk::") {
		return false
	}
	if strings.HasPrefix(rustType, "Option<") {
		inner := strings.TrimSuffix(strings.TrimPrefix(rustType, "Option<"), ">")
		inner = strings.TrimSpace(inner)
		return isStructType(inner)
	}
	return true
}

func getArgConverter(rustType, varName string) string {
	switch rustType {
	case "u64":
		return fmt.Sprintf("scval.Uint64ToScVal(%s)", varName)
	case "u32":
		return fmt.Sprintf("scval.Uint32ToScVal(%s)", varName)
	case "u128":
		return fmt.Sprintf("scval.MustToScVal((%s).ToScVal())", varName)
	case "i128":
		return fmt.Sprintf("scval.I128ToScVal(%s)", varName)
	case "bool":
		return fmt.Sprintf("scval.BoolToScVal(%s)", varName)
	case "soroban_sdk::Address":
		return fmt.Sprintf("scval.AddressToScVal(%s)", varName)
	case "soroban_sdk::Bytes":
		return fmt.Sprintf("scval.BytesToScVal(%s)", varName)
	}

	if strings.Contains(rustType, "Option<") && strings.Contains(rustType, "soroban_sdk::Address") {
		return fmt.Sprintf("scval.OptionalAddressToScVal(%s)", varName)
	}

	if strings.HasPrefix(rustType, "soroban_sdk::BytesN<") {
		n := extractBytesNSize(rustType)
		return fmt.Sprintf("scval.Bytes%dToScVal(%s)", n, varName)
	}

	if strings.HasPrefix(rustType, "soroban_sdk::Vec<") {
		innerType := extractVecInnerType(rustType)
		if innerType == "soroban_sdk::Address" {
			return fmt.Sprintf("scval.AddressSliceToScVal(%s)", varName)
		}
		if innerType == "soroban_sdk::Bytes" {
			return fmt.Sprintf("scval.BytesSliceToScVal(%s)", varName)
		}
		if n := extractBytesNSize(innerType); n > 0 {
			return fmt.Sprintf("scval.Bytes%dSliceToScVal(%s)", n, varName)
		}
		return fmt.Sprintf("scval.StructSliceToScVal(%s)", varName)
	}

	// Struct - call ToScVal
	return fmt.Sprintf("scval.MustToScVal(%s.ToScVal())", varName)
}

func zeroValue(rustType string) string {
	if isTupleType(rustType) {
		types := parseTupleTypes(rustType)
		zeros := make([]string, len(types))
		for i, t := range types {
			zeros[i] = zeroValue(t)
		}
		return strings.Join(zeros, ", ")
	}
	switch rustType {
	case "u64", "u32", "i128":
		return "0"
	case "u128":
		return "scval.U128{}"
	case "bool":
		return "false"
	case "soroban_sdk::Address":
		return "\"\""
	}
	if strings.HasPrefix(rustType, "Option<") {
		return "nil"
	}
	if strings.HasPrefix(rustType, "soroban_sdk::BytesN<") {
		n := extractBytesNSize(rustType)
		return fmt.Sprintf("[%d]byte{}", n)
	}
	return "nil"
}

func isTupleType(rustType string) bool {
	return strings.HasPrefix(rustType, "(") && strings.HasSuffix(rustType, ")")
}

func parseTupleTypes(tupleType string) []string {
	inner := strings.TrimSuffix(strings.TrimPrefix(tupleType, "("), ")")
	return splitReturnType(inner)
}

func generateTupleElementParsing(b *strings.Builder, rustType string, idx int, zeros string) {
	elem := fmt.Sprintf("(*vec)[%d]", idx)
	v := fmt.Sprintf("v%d", idx)

	switch {
	case rustType == "u32":
		b.WriteString(fmt.Sprintf("\t%sRaw, ok := %s.GetU32()\n", v, elem))
		b.WriteString("\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: expected u32\")\n", zeros, idx))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\t%s := uint32(%sRaw)\n\n", v, v))
	case rustType == "u64":
		b.WriteString(fmt.Sprintf("\t%s, err := scval.Uint64FromScVal(%s)\n", v, elem))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: %%w\", err)\n", zeros, idx))
		b.WriteString("\t}\n\n")
	case rustType == "i128":
		b.WriteString(fmt.Sprintf("\t%s, err := scval.I128FromScVal(%s)\n", v, elem))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: %%w\", err)\n", zeros, idx))
		b.WriteString("\t}\n\n")
	case rustType == "bool":
		b.WriteString(fmt.Sprintf("\t%s, ok := %s.GetB()\n", v, elem))
		b.WriteString("\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: expected bool\")\n", zeros, idx))
		b.WriteString("\t}\n\n")
	case rustType == "soroban_sdk::Address":
		b.WriteString(fmt.Sprintf("\t%s, err := scval.AddressFromScVal(%s)\n", v, elem))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: %%w\", err)\n", zeros, idx))
		b.WriteString("\t}\n\n")
	case rustType == "soroban_sdk::Bytes":
		b.WriteString(fmt.Sprintf("\t%sBytes, ok := %s.GetBytes()\n", v, elem))
		b.WriteString("\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: expected bytes\")\n", zeros, idx))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\t%s := []byte(%sBytes)\n\n", v, v))
	case strings.HasPrefix(rustType, "soroban_sdk::BytesN<"):
		n := extractBytesNSize(rustType)
		b.WriteString(fmt.Sprintf("\t%s, err := scval.Bytes%dFromScVal(%s)\n", v, n, elem))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: %%w\", err)\n", zeros, idx))
		b.WriteString("\t}\n\n")
	case strings.HasPrefix(rustType, "soroban_sdk::Vec<"):
		innerType := extractVecInnerType(rustType)
		goElemType := rustTypeToGo(innerType)
		b.WriteString(fmt.Sprintf("\t%sVec, ok := %s.GetVec()\n", v, elem))
		b.WriteString(fmt.Sprintf("\tif !ok || %sVec == nil {\n", v))
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: expected vec\")\n", zeros, idx))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\t%s := make([]%s, len(*%sVec))\n", v, goElemType, v))
		b.WriteString(fmt.Sprintf("\tfor i, item := range *%sVec {\n", v))
		switch {
		case innerType == "u64":
			b.WriteString("\t\tval, err := scval.Uint64FromScVal(item)\n")
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\t\treturn %s, fmt.Errorf(\"tuple[%d][%%d]: %%w\", i, err)\n", zeros, idx))
			b.WriteString("\t\t}\n")
			b.WriteString(fmt.Sprintf("\t\t%s[i] = val\n", v))
		case innerType == "u32":
			b.WriteString("\t\tval, ok := item.GetU32()\n")
			b.WriteString("\t\tif !ok {\n")
			b.WriteString(fmt.Sprintf("\t\t\treturn %s, fmt.Errorf(\"tuple[%d][%%d]: expected u32\", i)\n", zeros, idx))
			b.WriteString("\t\t}\n")
			b.WriteString(fmt.Sprintf("\t\t%s[i] = uint32(val)\n", v))
		case innerType == "soroban_sdk::Address":
			b.WriteString("\t\tval, err := scval.AddressFromScVal(item)\n")
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\t\treturn %s, fmt.Errorf(\"tuple[%d][%%d]: %%w\", i, err)\n", zeros, idx))
			b.WriteString("\t\t}\n")
			b.WriteString(fmt.Sprintf("\t\t%s[i] = val\n", v))
		case innerType == "soroban_sdk::Bytes":
			b.WriteString("\t\tval, ok := item.GetBytes()\n")
			b.WriteString("\t\tif !ok {\n")
			b.WriteString(fmt.Sprintf("\t\t\treturn %s, fmt.Errorf(\"tuple[%d][%%d]: expected bytes\", i)\n", zeros, idx))
			b.WriteString("\t\t}\n")
			b.WriteString(fmt.Sprintf("\t\t%s[i] = []byte(val)\n", v))
		default:
			structName := extractStructName(innerType)
			b.WriteString(fmt.Sprintf("\t\tval, err := %sFromScVal(item)\n", structName))
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\t\treturn %s, fmt.Errorf(\"tuple[%d][%%d]: %%w\", i, err)\n", zeros, idx))
			b.WriteString("\t\t}\n")
			b.WriteString(fmt.Sprintf("\t\t%s[i] = *val\n", v))
		}
		b.WriteString("\t}\n\n")
	default:
		structName := extractStructName(rustType)
		b.WriteString(fmt.Sprintf("\t%s, err := %sFromScVal(%s)\n", v, structName, elem))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s, fmt.Errorf(\"tuple[%d]: %%w\", err)\n", zeros, idx))
		b.WriteString("\t}\n\n")
	}
}

func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
