package main

import (
	"fmt"
	"strings"
	"unicode"
)

// GenerateTypes generates the types.go file content.
func GenerateTypes(pkg string, contract *Contract) string {
	var b strings.Builder

	b.WriteString("// Code generated by stellar-bindings-generator. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg))

	// Imports
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n\n")
	b.WriteString("\t\"github.com/smartcontractkit/chainlink-stellar/bindings/scval\"\n")
	b.WriteString("\t\"github.com/stellar/go-stellar-sdk/xdr\"\n")
	b.WriteString(")\n\n")

	// Generate structs
	for _, s := range contract.Structs {
		generateStruct(&b, s)
	}

	// Generate error enums
	for _, e := range contract.Errors {
		generateErrorEnum(&b, e)
	}

	// Generate events
	for _, e := range contract.Events {
		generateEventStruct(&b, e)
	}

	return b.String()
}

func generateStruct(b *strings.Builder, s Struct) {
	// Go struct
	b.WriteString(fmt.Sprintf("// %s represents the %s struct from the contract.\n", s.Name, s.Name))
	b.WriteString(fmt.Sprintf("type %s struct {\n", s.Name))
	for _, f := range s.Fields {
		goType := rustTypeToGo(f.Type)
		b.WriteString(fmt.Sprintf("\t%s %s\n", snakeToPascal(f.Name), goType))
	}
	b.WriteString("}\n\n")

	// ToScVal method - use value receiver for generics compatibility
	b.WriteString(fmt.Sprintf("// ToScVal converts %s to an xdr.ScVal for contract calls.\n", s.Name))
	b.WriteString(fmt.Sprintf("func (s %s) ToScVal() (xdr.ScVal, error) {\n", s.Name))
	b.WriteString("\treturn scval.BuildStructScVal(map[string]xdr.ScVal{\n")
	for _, f := range s.Fields {
		converter := getToScValConverter(f.Type, "s."+snakeToPascal(f.Name))
		b.WriteString(fmt.Sprintf("\t\t\"%s\": %s,\n", f.Name, converter))
	}
	b.WriteString("\t})\n")
	b.WriteString("}\n\n")

	// FromScVal function
	b.WriteString(fmt.Sprintf("// %sFromScVal parses an xdr.ScVal into %s.\n", s.Name, s.Name))
	b.WriteString(fmt.Sprintf("func %sFromScVal(val xdr.ScVal) (*%s, error) {\n", s.Name, s.Name))
	b.WriteString("\tscMap, ok := val.GetMap()\n")
	b.WriteString("\tif !ok || scMap == nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"not a map type\")\n")
	b.WriteString("\t}\n\n")
	b.WriteString(fmt.Sprintf("\tresult := &%s{}\n", s.Name))
	b.WriteString("\tfor _, entry := range *scMap {\n")
	b.WriteString("\t\tkey, ok := entry.Key.GetSym()\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n\n")
	b.WriteString("\t\tswitch string(key) {\n")
	for _, f := range s.Fields {
		b.WriteString(fmt.Sprintf("\t\tcase \"%s\":\n", f.Name))
		generateFromScValField(b, f, "result."+snakeToPascal(f.Name))
	}
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn result, nil\n")
	b.WriteString("}\n\n")
}

func generateFromScValField(b *strings.Builder, f Field, target string) {
	switch {
	case f.Type == "u64":
		b.WriteString(fmt.Sprintf("\t\t\tv, err := scval.Uint64FromScVal(entry.Val)\n"))
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case f.Type == "u32":
		b.WriteString("\t\t\tv, ok := entry.Val.GetU32()\n")
		b.WriteString("\t\t\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s is not u32\")\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = uint32(v)\n", target))
	case f.Type == "i128":
		b.WriteString("\t\t\tv, err := scval.I128FromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case f.Type == "bool":
		b.WriteString("\t\t\tv, ok := entry.Val.GetB()\n")
		b.WriteString("\t\t\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s is not bool\")\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case f.Type == "soroban_sdk::Address":
		b.WriteString("\t\t\tv, err := scval.AddressFromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case f.Type == "soroban_sdk::Bytes":
		b.WriteString("\t\t\tv, ok := entry.Val.GetBytes()\n")
		b.WriteString("\t\t\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s is not bytes\")\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = []byte(v)\n", target))
	case f.Type == "u128":
		b.WriteString("\t\t\tv, err := scval.U128FromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case strings.Contains(f.Type, "Option<") && strings.Contains(f.Type, "soroban_sdk::Address"):
		b.WriteString("\t\t\tv, err := scval.OptionalAddressFromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case strings.HasPrefix(f.Type, "soroban_sdk::BytesN<"):
		n := extractBytesNSize(f.Type)
		b.WriteString(fmt.Sprintf("\t\t\tv, err := scval.Bytes%dFromScVal(entry.Val)\n", n))
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case strings.HasPrefix(f.Type, "soroban_sdk::Vec<"):
		innerType := extractVecInnerType(f.Type)
		b.WriteString("\t\t\tvec, ok := entry.Val.GetVec()\n")
		b.WriteString("\t\t\tif !ok || vec == nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s is not a vec\")\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = make(%s, len(*vec))\n", target, rustTypeToGo(f.Type)))
		b.WriteString("\t\t\tfor i, item := range *vec {\n")
		generateVecItemParse(b, innerType, target+"[i]")
		b.WriteString("\t\t\t}\n")
	default:
		// Nested struct
		structName := extractStructName(f.Type)
		b.WriteString(fmt.Sprintf("\t\t\tv, err := %sFromScVal(entry.Val)\n", structName))
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = *v\n", target))
	}
}

func generateVecItemParse(b *strings.Builder, innerType, target string) {
	switch innerType {
	case "soroban_sdk::Address":
		b.WriteString("\t\t\t\tv, err := scval.AddressFromScVal(item)\n")
		b.WriteString("\t\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\t\treturn nil, err\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
	case "soroban_sdk::Bytes":
		b.WriteString("\t\t\t\tv, ok := item.GetBytes()\n")
		b.WriteString("\t\t\t\tif !ok {\n")
		b.WriteString("\t\t\t\t\treturn nil, fmt.Errorf(\"vec item is not bytes\")\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = []byte(v)\n", target))
	case "u128":
		b.WriteString("\t\t\t\tv, err := scval.U128FromScVal(item)\n")
		b.WriteString("\t\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\t\treturn nil, err\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
	default:
		if n := extractBytesNSize(innerType); n > 0 {
			b.WriteString(fmt.Sprintf("\t\t\t\tv, err := scval.Bytes%dFromScVal(item)\n", n))
			b.WriteString("\t\t\t\tif err != nil {\n")
			b.WriteString("\t\t\t\t\treturn nil, err\n")
			b.WriteString("\t\t\t\t}\n")
			b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
		} else {
			// Nested struct in vec
			structName := extractStructName(innerType)
			b.WriteString(fmt.Sprintf("\t\t\t\tv, err := %sFromScVal(item)\n", structName))
			b.WriteString("\t\t\t\tif err != nil {\n")
			b.WriteString("\t\t\t\t\treturn nil, err\n")
			b.WriteString("\t\t\t\t}\n")
			b.WriteString(fmt.Sprintf("\t\t\t\t%s = *v\n", target))
		}
	}
}

func generateErrorEnum(b *strings.Builder, e ErrorEnum) {
	b.WriteString(fmt.Sprintf("// %s represents the contract error codes.\n", e.Name))
	b.WriteString("const (\n")
	for _, v := range e.Variants {
		b.WriteString(fmt.Sprintf("\t%s%s = %d\n", e.Name, v.Name, v.Value))
	}
	b.WriteString(")\n\n")

	// Error message map
	b.WriteString(fmt.Sprintf("// %sMessage returns a human-readable message for error codes.\n", e.Name))
	b.WriteString(fmt.Sprintf("var %sMessage = map[int]string{\n", e.Name))
	for _, v := range e.Variants {
		b.WriteString(fmt.Sprintf("\t%d: \"%s\",\n", v.Value, camelToSpaces(v.Name)))
	}
	b.WriteString("}\n\n")
}

func generateEventStruct(b *strings.Builder, e Event) {
	b.WriteString(fmt.Sprintf("// %s represents the %s event.\n", e.Name, e.Name))
	b.WriteString(fmt.Sprintf("// Topics: %v\n", e.Topics))
	b.WriteString(fmt.Sprintf("type %s struct {\n", e.Name))
	for _, f := range e.Fields {
		goType := rustTypeToGo(f.Type)
		b.WriteString(fmt.Sprintf("\t%s %s\n", snakeToPascal(f.Name), goType))
	}
	// Add metadata fields
	b.WriteString("\t// Event metadata\n")
	b.WriteString("\tLedger uint32\n")
	b.WriteString("\tTxHash string\n")
	b.WriteString("}\n\n")

	// Topic constant
	if len(e.Topics) > 0 {
		b.WriteString(fmt.Sprintf("// %sTopic is the event topic identifier.\n", e.Name))
		b.WriteString(fmt.Sprintf("const %sTopic = \"%s\"\n\n", e.Name, e.Topics[0]))
	}
}

// Type conversion helpers

func rustTypeToGo(rustType string) string {
	switch rustType {
	case "u64":
		return "uint64"
	case "u32":
		return "uint32"
	case "u128":
		return "scval.U128"
	case "i128":
		return "int64"
	case "bool":
		return "bool"
	case "soroban_sdk::Address":
		return "string"
	case "soroban_sdk::Bytes":
		return "[]byte"
	case "soroban_sdk::Symbol":
		return "string"
	}

	if strings.HasPrefix(rustType, "Option<") {
		inner := strings.TrimSuffix(strings.TrimPrefix(rustType, "Option<"), ">")
		inner = strings.TrimSpace(inner)
		if inner == "soroban_sdk::Address" {
			return "*string"
		}
		// Option<Struct> -> *Struct
		innerType := rustTypeToGo(inner)
		return "*" + innerType
	}

	if strings.HasPrefix(rustType, "soroban_sdk::BytesN<") {
		// Extract N
		n := strings.TrimSuffix(strings.TrimPrefix(rustType, "soroban_sdk::BytesN<"), ">")
		return fmt.Sprintf("[%s]byte", n)
	}

	if strings.HasPrefix(rustType, "soroban_sdk::Vec<") {
		inner := extractVecInnerType(rustType)
		return "[]" + rustTypeToGo(inner)
	}

	// Assume it's a struct name
	return extractStructName(rustType)
}

func extractVecInnerType(vecType string) string {
	// soroban_sdk::Vec<InnerType>
	inner := strings.TrimSuffix(strings.TrimPrefix(vecType, "soroban_sdk::Vec<"), ">")
	return strings.TrimSpace(inner)
}

// extractBytesNSize returns N from soroban_sdk::BytesN<N>, or 0 if not matched.
func extractBytesNSize(rustType string) int {
	if !strings.HasPrefix(rustType, "soroban_sdk::BytesN<") {
		return 0
	}
	nStr := strings.TrimSuffix(strings.TrimPrefix(rustType, "soroban_sdk::BytesN<"), ">")
	var n int
	fmt.Sscanf(strings.TrimSpace(nStr), "%d", &n)
	return n
}

func extractStructName(rustType string) string {
	// Handle things like TokenAmount or soroban_sdk types
	if strings.Contains(rustType, "::") {
		parts := strings.Split(rustType, "::")
		return parts[len(parts)-1]
	}
	return rustType
}

func getToScValConverter(rustType, expr string) string {
	switch rustType {
	case "u64":
		return fmt.Sprintf("scval.Uint64ToScVal(%s)", expr)
	case "u32":
		return fmt.Sprintf("scval.Uint32ToScVal(%s)", expr)
	case "u128":
		return fmt.Sprintf("scval.MustToScVal((%s).ToScVal())", expr)
	case "i128":
		return fmt.Sprintf("scval.I128ToScVal(%s)", expr)
	case "bool":
		return fmt.Sprintf("scval.BoolToScVal(%s)", expr)
	case "soroban_sdk::Address":
		return fmt.Sprintf("scval.AddressToScVal(%s)", expr)
	case "soroban_sdk::Bytes":
		return fmt.Sprintf("scval.BytesToScVal(%s)", expr)
	}

	if strings.Contains(rustType, "Option<") && strings.Contains(rustType, "soroban_sdk::Address") {
		return fmt.Sprintf("scval.OptionalAddressToScVal(%s)", expr)
	}

	if strings.HasPrefix(rustType, "soroban_sdk::BytesN<") {
		n := extractBytesNSize(rustType)
		return fmt.Sprintf("scval.Bytes%dToScVal(%s)", n, expr)
	}

	if strings.HasPrefix(rustType, "soroban_sdk::Vec<") {
		inner := extractVecInnerType(rustType)
		if inner == "soroban_sdk::Address" {
			return fmt.Sprintf("scval.AddressSliceToScVal(%s)", expr)
		}
		if inner == "soroban_sdk::Bytes" {
			return fmt.Sprintf("scval.BytesSliceToScVal(%s)", expr)
		}
		if n := extractBytesNSize(inner); n > 0 {
			return fmt.Sprintf("scval.Bytes%dSliceToScVal(%s)", n, expr)
		}
		// u128 and structs have ToScVal
		return fmt.Sprintf("scval.StructSliceToScVal(%s)", expr)
	}

	// Struct - call ToScVal
	return fmt.Sprintf("scval.MustToScVal((%s).ToScVal())", expr)
}

func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func camelToSpaces(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			result.WriteRune(' ')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
