#!/usr/bin/env bash
# Generate Go bindings for all contracts from their Rust interface files.
#
# Reads from contracts/common/interfaces/src/*.rs (generated by gen_interfaces.sh)
# and outputs to bindings/contracts/{pkg}/.
#
# Usage:
#   ./scripts/gen_bindings.sh                    # Generate bindings (runs gen_interfaces first)
#   ./scripts/gen_bindings.sh --no-interfaces    # Skip gen_interfaces, use existing interface files
#
# Requires: gen_interfaces.sh has been run (or use --no-interfaces with existing interfaces),
#           go, stellar CLI

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WASM_DIR="$REPO_ROOT/target/wasm32v1-none/release"
INTERFACES_DIR="$REPO_ROOT/contracts/common/interfaces/src"
BINDINGS_DIR="$REPO_ROOT/bindings"
CONTRACTS_DIR="$BINDINGS_DIR/contracts"

# Contract config: "interface_module|PascalCaseName|go_package|use_common_message|events_file|readonly_fns|include_void_fns"
# use_common_message=1 when the interface uses StellarToAnyMessage/TokenAmount from common_message
# (fee_quoter, onramp have these structs replaced with a common_message import by
# gen_interfaces; we prepend the canonical definitions extracted from the onramp wasm spec)
# events_file: optional path (relative to REPO_ROOT) to a Rust events source file for -events flag
# readonly_fns: optional comma-separated -readonly list; when set, listed fns simulate and
# all others submit transactions; when empty the name heuristic (get_*/is_*/owner/balance) applies
# include_void_fns: optional comma-separated -include-void list; listed void fns (no return
# type) get generated methods, unlisted ones are omitted
CONTRACTS=(
  "committee_verifier|CommitteeVerifier|committee_verifier|0|"
  "executor|Executor|executor|0|"
  "fee_quoter|FeeQuoter|fee_quoter|1|"
  "versioned_verifier_resolver|VersionedVerifierResolver|versioned_verifier_resolver|0|"
  "onramp|OnRamp|onramp|1|"
  "rmn_proxy|RmnProxy|rmn_proxy|0|"
  "rmn_remote|RmnRemote|rmn_remote|0|"
  "offramp|OffRamp|offramp|0|contracts/offramp/src/events.rs"
  "router|Router|router|0|"
  "ramp_registry|RampRegistry|ramp_registry|0|"
  "ccip_receiver|ExampleCcipReceiver|ccip_receiver|0|"
  "token_admin_registry|TokenAdminRegistry|token_admin_registry|0|"
  "lock_release_pool|LockReleasePool|lock_release_pool|0|contracts/pools/lock-release-pool/src/events.rs"
  "burn_mint_pool|BurnMintPool|burn_mint_pool|0|contracts/pools/burn-mint-pool/src/events.rs"
  # bnm_token: no events_file — gen_interfaces uses empty prefixes (keep-all)
  # for BnM (its event topics are unprefixed lowercase and can't match the
  # prefix rule), so all 8 events are already in the interface. -events is
  # idempotent (the generator dedupes by event name), so passing one would be
  # a harmless no-op, but it isn't needed.
  # readonly_fns: the SAC read entrypoints (name/symbol/decimals/admin/balance/
  # allowance/authorized/type_and_version) plus the owner/minter reads
  # (owner/is_owner/get_minters/get_pending_owner) must simulate, not submit —
  # the name heuristic only catches `balance`/`owner`. include_void_fns: the
  # SAC write entrypoints plus `drip` and `mint_as` are void (`()`), so they're
  # omitted unless explicitly listed (the Ownable and add/remove_minter fns
  # return Result, not void, so they are generated regardless).
  "bnm_token|BnmToken|bnm_token|0||name,symbol,decimals,admin,balance,allowance,authorized,type_and_version,owner,is_owner,get_minters,get_pending_owner|burn,drip,mint,mint_as,approve,clawback,transfer,burn_from,set_admin,transfer_from,set_authorized,trust"
  # link_token: same as bnm_token minus drip — LINK has no local faucet (mint
  # is admin-only, i.e. the burn-mint pool on inbound bridge messages).
  "link_token|LinkToken|link_token|0||name,symbol,decimals,admin,balance,allowance,authorized,type_and_version,owner,is_owner,get_minters,get_pending_owner|burn,mint,mint_as,approve,clawback,transfer,burn_from,set_admin,transfer_from,set_authorized,trust"
  "token_pool|TokenPool|token_pool|0"
  "token_lock_box|TokenLockBox|token_lock_box|0"
  "siloed_lock_release_pool|SiloedLockReleasePool|siloed_lock_release_pool|0"
  "advanced_pool_hooks|AdvancedPoolHooks|advanced_pool_hooks|0|"
  # advanced_pool_hooks_extractor: both fns are pure views (EVM IExtractor
  # extract/type_and_version are `external pure/view`), so both simulate.
  "advanced_pool_hooks_extractor|AdvancedPoolHooksExtractor|advanced_pool_hooks_extractor|0||extract,type_and_version"
  "mcms|Mcms|mcms|0"
  "timelock|Timelock|timelock|0|"
  "forwarder|Forwarder|cre|0|"
  # mock_forwarder: permissionless forwarder used by `cre workflow simulate`.
  "mock_forwarder|MockForwarder|cre_mock_forwarder|0||type_and_version,get_transmission_info|"
  "data_feeds_cache|DataFeedsCache|data_feeds_cache|0||latest_round,get_round,round_range,find_round,decimals,description,get_feed_permissions,has_permission,is_feed_admin,is_frozen,is_configured,version,type_and_version,get_owner|upgrade,recover_tokens,accept_ownership,renounce_ownership,transfer_ownership"
  "data_feeds_proxy|DataFeedsProxy|data_feeds_proxy|0||latest_round,get_round,decimals,description,get_min_decimals,get_cache,version,type_and_version,get_owner|upgrade,set_cache,recover_tokens,accept_ownership,renounce_ownership,transfer_ownership"
)

# Extract the canonical TokenAmount and StellarToAnyMessage struct definitions for
# contracts that use common_message (gen_interfaces.sh replaces them with a
# `use common_message::...` import in fee_quoter/onramp, so the Go generator needs
# them re-supplied). Sourced from the onramp wasm spec, which embeds the
# common_message types used by its trait.
prepend_common_message() {
  local enabled="$1"
  if [[ "$enabled" != "1" ]]; then
    cat
    return
  fi
  stellar contract bindings rust --wasm "$WASM_DIR/onramp.wasm" 2>/dev/null | awk '
    /^#\[soroban_sdk::contracttype/ { a1=$0; getline; a2=$0; next }
    /^pub struct TokenAmount \{/ { if (!seen["TokenAmount"]++) { print a1; print a2; print; capturing=1 } next }
    /^pub struct StellarToAnyMessage \{/ { if (!seen["StellarToAnyMessage"]++) { print a1; print a2; print; capturing=1 } next }
    capturing { print; if (/^\}$/) capturing=0 }
  '
  echo ""
  cat
}

run_interfaces=true
for arg in "$@"; do
  case "$arg" in
    --no-interfaces) run_interfaces=false ;;
    -h|--help)
      echo "Usage: $0 [--no-interfaces]"
      echo "  --no-interfaces  Skip gen_interfaces.sh, use existing interface files"
      exit 0
      ;;
  esac
done

cd "$REPO_ROOT"

if [[ "$run_interfaces" == true ]]; then
  echo "Running gen_interfaces.sh first..."
  "$SCRIPT_DIR/gen_interfaces.sh" && rustfmt --edition 2021 "$INTERFACES_DIR"/*.rs
  echo ""
fi

mkdir -p "$CONTRACTS_DIR"

for entry in "${CONTRACTS[@]}"; do
  IFS='|' read -r iface_module pascal_name pkg use_common_msg events_file readonly_fns include_void_fns <<< "$entry"
  iface_path="$INTERFACES_DIR/${iface_module}.rs"
  out_dir="$CONTRACTS_DIR/$pkg"

  if [[ ! -f "$iface_path" ]]; then
    echo "ERROR: $iface_path not found for $pkg" >&2
    exit 1
  fi

  events_flag=""
  if [[ -n "$events_file" ]]; then
    events_flag="-events $REPO_ROOT/$events_file"
  fi

  readonly_flag=""
  if [[ -n "${readonly_fns:-}" ]]; then
    readonly_flag="-readonly $readonly_fns"
  fi

  void_flag=""
  if [[ -n "${include_void_fns:-}" ]]; then
    void_flag="-include-void $include_void_fns"
  fi

  echo "Generating Go bindings for $pascal_name..."
  prepend_common_message "${use_common_msg:-0}" < "$iface_path" | (cd "$BINDINGS_DIR" && go run ./generator -name "$pascal_name" -pkg "$pkg" -out "$out_dir" $events_flag $readonly_flag $void_flag)
done

echo ""
echo "Done. Bindings written to $CONTRACTS_DIR"
