with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

dir: ./mocks
outpkg: mocks

packages:
  github.com/smartcontractkit/chainlink-stellar/bindings:
    interfaces:
      Invoker:

  github.com/smartcontractkit/chainlink-stellar/relayer/chain:
    interfaces:
      RPCClient:
      SorobanClient:

  github.com/smartcontractkit/chainlink-stellar/relayer:
    interfaces:
      StellarTxManager:

  github.com/smartcontractkit/chainlink-common/pkg/types/core:
    config:
      dir: ./monitor/mocks
    interfaces:
      Keystore:

  github.com/smartcontractkit/chainlink-stellar/relayer/monitor:
    config:
      dir: ./monitor/mocks
    interfaces:
      BalanceMonitorRPCClient:
