// Code generated by stellar-bindings-generator. DO NOT EDIT.
package data_feeds_proxy

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// DataFeedsProxyClient provides methods to interact with the DataFeedsProxy contract.
type DataFeedsProxyClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewDataFeedsProxyClient creates a new DataFeedsProxyClient.
func NewDataFeedsProxyClient(invoker bindings.Invoker, contractID string) *DataFeedsProxyClient {
	return &DataFeedsProxyClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *DataFeedsProxyClient) ContractID() string {
	return c.contractID
}

// Upgrade calls the upgrade function on the contract.
func (c *DataFeedsProxyClient) Upgrade(ctx context.Context, newWasmHash [32]byte) error {
	args := []xdr.ScVal{
		scval.Bytes32ToScVal(newWasmHash),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "upgrade", args)
	if err != nil {
		return fmt.Errorf("failed to call upgrade: %w", err)
	}

	_ = result // void return
	return nil
}

// Version calls the version function on the contract.
func (c *DataFeedsProxyClient) Version(ctx context.Context) (uint32, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "version", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call version: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from version")
	}

	v, ok := result.GetU32()
	if !ok {
		return 0, fmt.Errorf("expected u32 return type")
	}
	return uint32(v), nil
}

// Decimals calls the decimals function on the contract.
func (c *DataFeedsProxyClient) Decimals(ctx context.Context, dataId [16]byte) (uint32, error) {
	args := []xdr.ScVal{
		scval.Bytes16ToScVal(dataId),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "decimals", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call decimals: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from decimals")
	}

	v, ok := result.GetU32()
	if !ok {
		return 0, fmt.Errorf("expected u32 return type")
	}
	return uint32(v), nil
}

// GetOwner calls the get_owner function on the contract.
func (c *DataFeedsProxyClient) GetOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// GetRound calls the get_round function on the contract.
func (c *DataFeedsProxyClient) GetRound(ctx context.Context, dataId [16]byte, roundId uint64) (*Round, error) {
	args := []xdr.ScVal{
		scval.Bytes16ToScVal(dataId),
		scval.Uint64ToScVal(roundId),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_round", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_round: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_round")
	}

	return RoundFromScVal(*result)
}

// SetCache calls the set_cache function on the contract.
func (c *DataFeedsProxyClient) SetCache(ctx context.Context, cache string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(cache),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_cache", args)
	if err != nil {
		return fmt.Errorf("failed to call set_cache: %w", err)
	}

	_ = result // void return
	return nil
}

// Description calls the description function on the contract.
func (c *DataFeedsProxyClient) Description(ctx context.Context, dataId [16]byte) (string, error) {
	args := []xdr.ScVal{
		scval.Bytes16ToScVal(dataId),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "description", args)
	if err != nil {
		return "", fmt.Errorf("failed to call description: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from description")
	}

	return scval.StringFromScVal(*result)
}

// LatestRound calls the latest_round function on the contract.
func (c *DataFeedsProxyClient) LatestRound(ctx context.Context, dataId [16]byte) (*Round, error) {
	args := []xdr.ScVal{
		scval.Bytes16ToScVal(dataId),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "latest_round", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call latest_round: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from latest_round")
	}

	return RoundFromScVal(*result)
}

// RecoverTokens calls the recover_tokens function on the contract.
func (c *DataFeedsProxyClient) RecoverTokens(ctx context.Context, token string, to string, amount int64) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
		scval.AddressToScVal(to),
		scval.I128ToScVal(amount),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "recover_tokens", args)
	if err != nil {
		return fmt.Errorf("failed to call recover_tokens: %w", err)
	}

	_ = result // void return
	return nil
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *DataFeedsProxyClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *DataFeedsProxyClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// RenounceOwnership calls the renounce_ownership function on the contract.
func (c *DataFeedsProxyClient) RenounceOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "renounce_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call renounce_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *DataFeedsProxyClient) TransferOwnership(ctx context.Context, newOwner string, liveUntilLedger uint32) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
		scval.Uint32ToScVal(liveUntilLedger),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// WaitForCacheSet waits for a CacheSet event.
func (c *DataFeedsProxyClient) WaitForCacheSet(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*CacheSet) bool) (*CacheSet, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{CacheSetTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseCacheSet(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseCacheSet(e protocolrpc.EventInfo) (*CacheSet, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &CacheSet{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "old_cache":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.OldCache = v
			}
		case "new_cache":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewCache = v
			}
		}
	}

	return result, nil
}

// WaitForUpgraded waits for a Upgraded event.
func (c *DataFeedsProxyClient) WaitForUpgraded(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*Upgraded) bool) (*Upgraded, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{UpgradedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseUpgraded(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseUpgraded(e protocolrpc.EventInfo) (*Upgraded, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &Upgraded{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "new_wasm_hash":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err == nil {
				result.NewWasmHash = v
			}
		}
	}

	return result, nil
}

// WaitForTokenRecovered waits for a TokenRecovered event.
func (c *DataFeedsProxyClient) WaitForTokenRecovered(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*TokenRecovered) bool) (*TokenRecovered, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{TokenRecoveredTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseTokenRecovered(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseTokenRecovered(e protocolrpc.EventInfo) (*TokenRecovered, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &TokenRecovered{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Token = v
			}
		case "to":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.To = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransfer waits for a OwnershipTransfer event.
func (c *DataFeedsProxyClient) WaitForOwnershipTransfer(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransfer) bool) (*OwnershipTransfer, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipTransfer(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipTransfer(e protocolrpc.EventInfo) (*OwnershipTransfer, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransfer{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "old_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.OldOwner = v
			}
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		case "live_until_ledger":
			v, ok := entry.Val.GetU32()
			if ok {
				result.LiveUntilLedger = uint32(v)
			}
		}
	}

	return result, nil
}

// WaitForOwnershipRenounced waits for a OwnershipRenounced event.
func (c *DataFeedsProxyClient) WaitForOwnershipRenounced(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipRenounced) bool) (*OwnershipRenounced, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipRenouncedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipRenounced(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipRenounced(e protocolrpc.EventInfo) (*OwnershipRenounced, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipRenounced{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "old_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.OldOwner = v
			}
		}
	}

	return result, nil
}

// WaitForOwnershipTransferCompleted waits for a OwnershipTransferCompleted event.
func (c *DataFeedsProxyClient) WaitForOwnershipTransferCompleted(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OwnershipTransferCompleted) bool) (*OwnershipTransferCompleted, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OwnershipTransferCompletedTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOwnershipTransferCompleted(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOwnershipTransferCompleted(e protocolrpc.EventInfo) (*OwnershipTransferCompleted, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OwnershipTransferCompleted{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "new_owner":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.NewOwner = v
			}
		}
	}

	return result, nil
}
