// Code generated by stellar-bindings-generator. DO NOT EDIT.
package cre

import (
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// AllowListEntry represents the AllowListEntry struct from the contract.
type AllowListEntry struct {
	Allowlist        []string
	AllowlistEnabled bool
}

// ToScVal converts AllowListEntry to an xdr.ScVal for contract calls.
func (s AllowListEntry) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"allowlist":         scval.AddressSliceToScVal(s.Allowlist),
		"allowlist_enabled": scval.BoolToScVal(s.AllowlistEnabled),
	})
}

// AllowListEntryFromScVal parses an xdr.ScVal into AllowListEntry.
func AllowListEntryFromScVal(val xdr.ScVal) (*AllowListEntry, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &AllowListEntry{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "allowlist":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("allowlist is not a vec")
			}
			result.Allowlist = make([]string, len(*vec))
			for i, item := range *vec {
				v, err := scval.AddressFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.Allowlist[i] = v
			}
		case "allowlist_enabled":
			v, ok := entry.Val.GetB()
			if !ok {
				return nil, fmt.Errorf("allowlist_enabled is not bool")
			}
			result.AllowlistEnabled = v
		}
	}

	return result, nil
}

// AllowListUpdate represents the AllowListUpdate struct from the contract.
type AllowListUpdate struct {
	AddedAllowlistedSenders   []string
	AllowlistEnabled          bool
	DestChainSelector         uint64
	RemovedAllowlistedSenders []string
}

// ToScVal converts AllowListUpdate to an xdr.ScVal for contract calls.
func (s AllowListUpdate) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"added_allowlisted_senders":   scval.AddressSliceToScVal(s.AddedAllowlistedSenders),
		"allowlist_enabled":           scval.BoolToScVal(s.AllowlistEnabled),
		"dest_chain_selector":         scval.Uint64ToScVal(s.DestChainSelector),
		"removed_allowlisted_senders": scval.AddressSliceToScVal(s.RemovedAllowlistedSenders),
	})
}

// AllowListUpdateFromScVal parses an xdr.ScVal into AllowListUpdate.
func AllowListUpdateFromScVal(val xdr.ScVal) (*AllowListUpdate, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &AllowListUpdate{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "added_allowlisted_senders":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("added_allowlisted_senders is not a vec")
			}
			result.AddedAllowlistedSenders = make([]string, len(*vec))
			for i, item := range *vec {
				v, err := scval.AddressFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.AddedAllowlistedSenders[i] = v
			}
		case "allowlist_enabled":
			v, ok := entry.Val.GetB()
			if !ok {
				return nil, fmt.Errorf("allowlist_enabled is not bool")
			}
			result.AllowlistEnabled = v
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		case "removed_allowlisted_senders":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("removed_allowlisted_senders is not a vec")
			}
			result.RemovedAllowlistedSenders = make([]string, len(*vec))
			for i, item := range *vec {
				v, err := scval.AddressFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.RemovedAllowlistedSenders[i] = v
			}
		}
	}

	return result, nil
}

// TokenAmount represents the TokenAmount struct from the contract.
type TokenAmount struct {
	Amount int64
	Token  string
}

// ToScVal converts TokenAmount to an xdr.ScVal for contract calls.
func (s TokenAmount) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"amount": scval.I128ToScVal(s.Amount),
		"token":  scval.AddressToScVal(s.Token),
	})
}

// TokenAmountFromScVal parses an xdr.ScVal into TokenAmount.
func TokenAmountFromScVal(val xdr.ScVal) (*TokenAmount, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenAmount{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("amount: %w", err)
			}
			result.Amount = v
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("token: %w", err)
			}
			result.Token = v
		}
	}

	return result, nil
}

// GenericExtraArgsV3 represents the GenericExtraArgsV3 struct from the contract.
type GenericExtraArgsV3 struct {
	BlockConfirmations uint32
	CcvArgs            [][]byte
	Ccvs               []string
	Executor           string
	ExecutorArgs       []byte
	GasLimit           uint32
	TokenArgs          []byte
	TokenReceiver      []byte
}

// ToScVal converts GenericExtraArgsV3 to an xdr.ScVal for contract calls.
func (s GenericExtraArgsV3) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"block_confirmations": scval.Uint32ToScVal(s.BlockConfirmations),
		"ccv_args":            scval.BytesSliceToScVal(s.CcvArgs),
		"ccvs":                scval.AddressSliceToScVal(s.Ccvs),
		"executor":            scval.AddressToScVal(s.Executor),
		"executor_args":       scval.BytesToScVal(s.ExecutorArgs),
		"gas_limit":           scval.Uint32ToScVal(s.GasLimit),
		"token_args":          scval.BytesToScVal(s.TokenArgs),
		"token_receiver":      scval.BytesToScVal(s.TokenReceiver),
	})
}

// GenericExtraArgsV3FromScVal parses an xdr.ScVal into GenericExtraArgsV3.
func GenericExtraArgsV3FromScVal(val xdr.ScVal) (*GenericExtraArgsV3, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &GenericExtraArgsV3{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "block_confirmations":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("block_confirmations is not u32")
			}
			result.BlockConfirmations = uint32(v)
		case "ccv_args":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("ccv_args is not a vec")
			}
			result.CcvArgs = make([][]byte, len(*vec))
			for i, item := range *vec {
				v, ok := item.GetBytes()
				if !ok {
					return nil, fmt.Errorf("vec item is not bytes")
				}
				result.CcvArgs[i] = []byte(v)
			}
		case "ccvs":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("ccvs is not a vec")
			}
			result.Ccvs = make([]string, len(*vec))
			for i, item := range *vec {
				v, err := scval.AddressFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.Ccvs[i] = v
			}
		case "executor":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("executor: %w", err)
			}
			result.Executor = v
		case "executor_args":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("executor_args is not bytes")
			}
			result.ExecutorArgs = []byte(v)
		case "gas_limit":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("gas_limit is not u32")
			}
			result.GasLimit = uint32(v)
		case "token_args":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("token_args is not bytes")
			}
			result.TokenArgs = []byte(v)
		case "token_receiver":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("token_receiver is not bytes")
			}
			result.TokenReceiver = []byte(v)
		}
	}

	return result, nil
}

// AnyToStellarMessage represents the AnyToStellarMessage struct from the contract.
type AnyToStellarMessage struct {
	Data                []byte
	DestTokenAmounts    []TokenAmount
	MessageId           [32]byte
	Sender              []byte
	SourceChainSelector uint64
}

// ToScVal converts AnyToStellarMessage to an xdr.ScVal for contract calls.
func (s AnyToStellarMessage) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"data":                  scval.BytesToScVal(s.Data),
		"dest_token_amounts":    scval.StructSliceToScVal(s.DestTokenAmounts),
		"message_id":            scval.Bytes32ToScVal(s.MessageId),
		"sender":                scval.BytesToScVal(s.Sender),
		"source_chain_selector": scval.Uint64ToScVal(s.SourceChainSelector),
	})
}

// AnyToStellarMessageFromScVal parses an xdr.ScVal into AnyToStellarMessage.
func AnyToStellarMessageFromScVal(val xdr.ScVal) (*AnyToStellarMessage, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &AnyToStellarMessage{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("data is not bytes")
			}
			result.Data = []byte(v)
		case "dest_token_amounts":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("dest_token_amounts is not a vec")
			}
			result.DestTokenAmounts = make([]TokenAmount, len(*vec))
			for i, item := range *vec {
				v, err := TokenAmountFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.DestTokenAmounts[i] = *v
			}
		case "message_id":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("message_id: %w", err)
			}
			result.MessageId = v
		case "sender":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("sender is not bytes")
			}
			result.Sender = []byte(v)
		case "source_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("source_chain_selector: %w", err)
			}
			result.SourceChainSelector = v
		}
	}

	return result, nil
}

// StellarToAnyMessage represents the StellarToAnyMessage struct from the contract.
type StellarToAnyMessage struct {
	Data         []byte
	ExtraArgs    []byte
	FeeToken     string
	Receiver     []byte
	TokenAmounts []TokenAmount
}

// ToScVal converts StellarToAnyMessage to an xdr.ScVal for contract calls.
func (s StellarToAnyMessage) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"data":          scval.BytesToScVal(s.Data),
		"extra_args":    scval.BytesToScVal(s.ExtraArgs),
		"fee_token":     scval.AddressToScVal(s.FeeToken),
		"receiver":      scval.BytesToScVal(s.Receiver),
		"token_amounts": scval.StructSliceToScVal(s.TokenAmounts),
	})
}

// StellarToAnyMessageFromScVal parses an xdr.ScVal into StellarToAnyMessage.
func StellarToAnyMessageFromScVal(val xdr.ScVal) (*StellarToAnyMessage, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &StellarToAnyMessage{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("data is not bytes")
			}
			result.Data = []byte(v)
		case "extra_args":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("extra_args is not bytes")
			}
			result.ExtraArgs = []byte(v)
		case "fee_token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("fee_token: %w", err)
			}
			result.FeeToken = v
		case "receiver":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("receiver is not bytes")
			}
			result.Receiver = []byte(v)
		case "token_amounts":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("token_amounts is not a vec")
			}
			result.TokenAmounts = make([]TokenAmount, len(*vec))
			for i, item := range *vec {
				v, err := TokenAmountFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.TokenAmounts[i] = *v
			}
		}
	}

	return result, nil
}

// SignatureConfig represents the SignatureConfig struct from the contract.
type SignatureConfig struct {
	Signers      [][32]byte
	Verification SignatureVerificationConfig
}

// ToScVal converts SignatureConfig to an xdr.ScVal for contract calls.
func (s SignatureConfig) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"signers":      scval.Bytes32SliceToScVal(s.Signers),
		"verification": scval.MustToScVal((s.Verification).ToScVal()),
	})
}

// SignatureConfigFromScVal parses an xdr.ScVal into SignatureConfig.
func SignatureConfigFromScVal(val xdr.ScVal) (*SignatureConfig, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &SignatureConfig{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "signers":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("signers is not a vec")
			}
			result.Signers = make([][32]byte, len(*vec))
			for i, item := range *vec {
				v, err := scval.Bytes32FromScVal(item)
				if err != nil {
					return nil, err
				}
				result.Signers[i] = v
			}
		case "verification":
			v, err := SignatureVerificationConfigFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("verification: %w", err)
			}
			result.Verification = v
		}
	}

	return result, nil
}

// Config represents the Config struct from the contract.
type Config struct {
	F       uint32
	Signers [][32]byte
}

// ToScVal converts Config to an xdr.ScVal for contract calls.
func (s Config) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"f":       scval.Uint32ToScVal(s.F),
		"signers": scval.Bytes32SliceToScVal(s.Signers),
	})
}

// ConfigFromScVal parses an xdr.ScVal into Config.
func ConfigFromScVal(val xdr.ScVal) (*Config, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &Config{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "f":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("f is not u32")
			}
			result.F = uint32(v)
		case "signers":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("signers is not a vec")
			}
			result.Signers = make([][32]byte, len(*vec))
			for i, item := range *vec {
				v, err := scval.Bytes32FromScVal(item)
				if err != nil {
					return nil, err
				}
				result.Signers[i] = v
			}
		}
	}

	return result, nil
}

// Transmission represents the Transmission struct from the contract.
type Transmission struct {
	State       TransmissionState
	Transmitter string
}

// ToScVal converts Transmission to an xdr.ScVal for contract calls.
func (s Transmission) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"state":       scval.MustToScVal((s.State).ToScVal()),
		"transmitter": scval.AddressToScVal(s.Transmitter),
	})
}

// TransmissionFromScVal parses an xdr.ScVal into Transmission.
func TransmissionFromScVal(val xdr.ScVal) (*Transmission, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &Transmission{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "state":
			v, err := TransmissionStateFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("state: %w", err)
			}
			result.State = v
		case "transmitter":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("transmitter: %w", err)
			}
			result.Transmitter = v
		}
	}

	return result, nil
}

// Ed25519Signature represents the Ed25519Signature struct from the contract.
type Ed25519Signature struct {
	PublicKey [32]byte
	Signature [64]byte
}

// ToScVal converts Ed25519Signature to an xdr.ScVal for contract calls.
func (s Ed25519Signature) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"public_key": scval.Bytes32ToScVal(s.PublicKey),
		"signature":  scval.Bytes64ToScVal(s.Signature),
	})
}

// Ed25519SignatureFromScVal parses an xdr.ScVal into Ed25519Signature.
func Ed25519SignatureFromScVal(val xdr.ScVal) (*Ed25519Signature, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &Ed25519Signature{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "public_key":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("public_key: %w", err)
			}
			result.PublicKey = v
		case "signature":
			v, err := scval.Bytes64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("signature: %w", err)
			}
			result.Signature = v
		}
	}

	return result, nil
}

// TransmissionInfo represents the TransmissionInfo struct from the contract.
type TransmissionInfo struct {
	State       TransmissionState
	Transmitter *string
}

// ToScVal converts TransmissionInfo to an xdr.ScVal for contract calls.
func (s TransmissionInfo) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"state":       scval.MustToScVal((s.State).ToScVal()),
		"transmitter": scval.OptionalAddressToScVal(s.Transmitter),
	})
}

// TransmissionInfoFromScVal parses an xdr.ScVal into TransmissionInfo.
func TransmissionInfoFromScVal(val xdr.ScVal) (*TransmissionInfo, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TransmissionInfo{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "state":
			v, err := TransmissionStateFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("state: %w", err)
			}
			result.State = v
		case "transmitter":
			v, err := scval.OptionalAddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("transmitter: %w", err)
			}
			result.Transmitter = v
		}
	}

	return result, nil
}

// CCIPError represents the contract error codes.
const (
	CCIPErrorNotInitialized                      = 1
	CCIPErrorAlreadyInitialized                  = 2
	CCIPErrorUnauthorized                        = 3
	CCIPErrorNotOwner                            = 4
	CCIPErrorNoPendingOwner                      = 5
	CCIPErrorCallerNotAuthorized                 = 6
	CCIPErrorCallerAlreadyAuthorized             = 7
	CCIPErrorCallerNotFound                      = 8
	CCIPErrorRoleNotGranted                      = 9
	CCIPErrorFeatureNotEnabled                   = 10
	CCIPErrorRoleAlreadyGranted                  = 11
	CCIPErrorCannotRenounceRole                  = 12
	CCIPErrorInvalidVersionTag                   = 13
	CCIPErrorInvalidSignatureLength              = 14
	CCIPErrorInvalidSignature                    = 15
	CCIPErrorInvalidSignatureCount               = 16
	CCIPErrorInvalidSignatureThreshold           = 17
	CCIPErrorInvalidSignaturePubkey              = 18
	CCIPErrorSourceSignersNotConfigured          = 19
	CCIPErrorInvalidVerifierResults              = 20
	CCIPErrorReentrantCall                       = 21
	CCIPErrorTokenNotSupported                   = 22
	CCIPErrorFeeTokenNotSupported                = 23
	CCIPErrorNoGasPriceAvailable                 = 24
	CCIPErrorDestinationChainNotEnabled          = 25
	CCIPErrorInvalidExtraArgsTag                 = 26
	CCIPErrorInvalidExtraArgsData                = 27
	CCIPErrorMessageGasLimitTooHigh              = 28
	CCIPErrorMessageTooLarge                     = 29
	CCIPErrorUnsupportedNumberOfTokens           = 30
	CCIPErrorInvalidDestChainConfig              = 31
	CCIPErrorMessageFeeTooHigh                   = 32
	CCIPErrorInvalidStaticConfig                 = 33
	CCIPErrorInvalidTokenReceiver                = 34
	CCIPErrorSourceTokenDataTooLarge             = 35
	CCIPErrorInvalidDestBytesOverhead            = 36
	CCIPErrorDestinationChainNotSupported        = 37
	CCIPErrorMustBeCalledByRouter                = 38
	CCIPErrorRouterMustSetOriginalSender         = 39
	CCIPErrorCannotSendZeroTokens                = 40
	CCIPErrorCanOnlySendOneTokenPerMessage       = 41
	CCIPErrorUnsupportedToken                    = 42
	CCIPErrorInvalidDestChainAddress             = 43
	CCIPErrorFeeExceedsMaxAllowed                = 44
	CCIPErrorInsufficientFeeTokenAmount          = 45
	CCIPErrorTokenReceiverNotAllowed             = 46
	CCIPErrorCursedByRMN                         = 47
	CCIPErrorRemoteChainNotSupported             = 48
	CCIPErrorSenderNotAllowed                    = 49
	CCIPErrorInvalidTokenAmount                  = 50
	CCIPErrorInvalidReceiverAddress              = 51
	CCIPErrorInvalidConfig                       = 52
	CCIPErrorInvalidVerifierResultsLength        = 53
	CCIPErrorInboundImplementationNotFound       = 54
	CCIPErrorOutboundImplementationNotFound      = 55
	CCIPErrorInvalidAddress                      = 56
	CCIPErrorInvalidChainSelector                = 57
	CCIPErrorInvalidVersion                      = 58
	CCIPErrorInvalidCCVVersion                   = 59
	CCIPErrorOffRampAlreadyExists                = 60
	CCIPErrorOffRampMismatch                     = 61
	CCIPErrorBadRMNSignal                        = 62
	CCIPErrorUnsupportedDestinationChain         = 63
	CCIPErrorAlreadyCursed                       = 64
	CCIPErrorConfigNotSet                        = 65
	CCIPErrorDuplicateOnchainPublicKey           = 66
	CCIPErrorInvalidSignerOrder                  = 67
	CCIPErrorNotEnoughSigners                    = 68
	CCIPErrorNotCursed                           = 69
	CCIPErrorOutOfOrderSignatures                = 70
	CCIPErrorThresholdNotMet                     = 71
	CCIPErrorUnexpectedSigner                    = 72
	CCIPErrorZeroValueNotAllowed                 = 73
	CCIPErrorSourceChainNotEnabled               = 100
	CCIPErrorInvalidSourceChainConfig            = 101
	CCIPErrorInvalidOnRampAddress                = 102
	CCIPErrorInvalidOffRampAddress               = 103
	CCIPErrorInvalidMessageDestination           = 104
	CCIPErrorMessageAlreadyExecuted              = 105
	CCIPErrorInvalidExecutionState               = 106
	CCIPErrorCCVLengthMismatch                   = 107
	CCIPErrorCCVQuorumNotMet                     = 108
	CCIPErrorReceiverError                       = 109
	CCIPErrorGasLimitOverrideTooLow              = 110
	CCIPErrorInvalidReceiverLength               = 111
	CCIPErrorTokenHandlingError                  = 112
	CCIPErrorMessageDecodingError                = 113
	CCIPErrorReceiverDoesNotExist                = 114
	CCIPErrorReceiverNotWasmContract             = 115
	CCIPErrorRequiredCCVMissing                  = 116
	CCIPErrorOnlyRegistryModuleOrOwner           = 201
	CCIPErrorOnlyAdministrator                   = 202
	CCIPErrorOnlyPendingAdministrator            = 203
	CCIPErrorTokenAlreadyRegistered              = 204
	CCIPErrorInvalidTokenPoolToken               = 205
	CCIPErrorPoolTokenMismatch                   = 301
	CCIPErrorChainNotSupported                   = 302
	CCIPErrorCallerIsNotRamp                     = 303
	CCIPErrorInsufficientPoolLiquidity           = 304
	CCIPErrorInvalidRemotePoolAddress            = 305
	CCIPErrorInvalidRemoteChainConfig            = 306
	CCIPErrorInvalidRemoteChainDecimals          = 307
	CCIPErrorDecimalAmountOverflow               = 308
	CCIPErrorInvalidPoolTokenDecimals            = 309
	CCIPErrorBucketOverfilled                    = 310
	CCIPErrorTokenMaxCapacityExceeded            = 311
	CCIPErrorTokenRateLimitReached               = 312
	CCIPErrorInvalidRateLimitRate                = 313
	CCIPErrorDisabledNonZeroRateLimit            = 314
	CCIPErrorInvalidRequestedFinality            = 315
	CCIPErrorRequestedFinalityCanOnlyHaveOneMode = 316
	CCIPErrorInvalidChainForClient               = 317
	CCIPErrorRouterNotConfigured                 = 318
	CCIPErrorInvalidFeeCalculation               = 801
	CCIPErrorInvalidFeeTokenConversion           = 802
	CCIPErrorZeroFeeAggregatorNotAllowed         = 803
)

// CCIPErrorMessage returns a human-readable message for error codes.
var CCIPErrorMessage = map[int]string{
	1:   "not initialized",
	2:   "already initialized",
	3:   "unauthorized",
	4:   "not owner",
	5:   "no pending owner",
	6:   "caller not authorized",
	7:   "caller already authorized",
	8:   "caller not found",
	9:   "role not granted",
	10:  "feature not enabled",
	11:  "role already granted",
	12:  "cannot renounce role",
	13:  "invalid version tag",
	14:  "invalid signature length",
	15:  "invalid signature",
	16:  "invalid signature count",
	17:  "invalid signature threshold",
	18:  "invalid signature pubkey",
	19:  "source signers not configured",
	20:  "invalid verifier results",
	21:  "reentrant call",
	22:  "token not supported",
	23:  "fee token not supported",
	24:  "no gas price available",
	25:  "destination chain not enabled",
	26:  "invalid extra args tag",
	27:  "invalid extra args data",
	28:  "message gas limit too high",
	29:  "message too large",
	30:  "unsupported number of tokens",
	31:  "invalid dest chain config",
	32:  "message fee too high",
	33:  "invalid static config",
	34:  "invalid token receiver",
	35:  "source token data too large",
	36:  "invalid dest bytes overhead",
	37:  "destination chain not supported",
	38:  "must be called by router",
	39:  "router must set original sender",
	40:  "cannot send zero tokens",
	41:  "can only send one token per message",
	42:  "unsupported token",
	43:  "invalid dest chain address",
	44:  "fee exceeds max allowed",
	45:  "insufficient fee token amount",
	46:  "token receiver not allowed",
	47:  "cursed by r m n",
	48:  "remote chain not supported",
	49:  "sender not allowed",
	50:  "invalid token amount",
	51:  "invalid receiver address",
	52:  "invalid config",
	53:  "invalid verifier results length",
	54:  "inbound implementation not found",
	55:  "outbound implementation not found",
	56:  "invalid address",
	57:  "invalid chain selector",
	58:  "invalid version",
	59:  "invalid c c v version",
	60:  "off ramp already exists",
	61:  "off ramp mismatch",
	62:  "bad r m n signal",
	63:  "unsupported destination chain",
	64:  "already cursed",
	65:  "config not set",
	66:  "duplicate onchain public key",
	67:  "invalid signer order",
	68:  "not enough signers",
	69:  "not cursed",
	70:  "out of order signatures",
	71:  "threshold not met",
	72:  "unexpected signer",
	73:  "zero value not allowed",
	100: "source chain not enabled",
	101: "invalid source chain config",
	102: "invalid on ramp address",
	103: "invalid off ramp address",
	104: "invalid message destination",
	105: "message already executed",
	106: "invalid execution state",
	107: "c c v length mismatch",
	108: "c c v quorum not met",
	109: "receiver error",
	110: "gas limit override too low",
	111: "invalid receiver length",
	112: "token handling error",
	113: "message decoding error",
	114: "receiver does not exist",
	115: "receiver not wasm contract",
	116: "required c c v missing",
	201: "only registry module or owner",
	202: "only administrator",
	203: "only pending administrator",
	204: "token already registered",
	205: "invalid token pool token",
	301: "pool token mismatch",
	302: "chain not supported",
	303: "caller is not ramp",
	304: "insufficient pool liquidity",
	305: "invalid remote pool address",
	306: "invalid remote chain config",
	307: "invalid remote chain decimals",
	308: "decimal amount overflow",
	309: "invalid pool token decimals",
	310: "bucket overfilled",
	311: "token max capacity exceeded",
	312: "token rate limit reached",
	313: "invalid rate limit rate",
	314: "disabled non zero rate limit",
	315: "invalid requested finality",
	316: "requested finality can only have one mode",
	317: "invalid chain for client",
	318: "router not configured",
	801: "invalid fee calculation",
	802: "invalid fee token conversion",
	803: "zero fee aggregator not allowed",
}

// ForwarderError represents the contract error codes.
const (
	ForwarderErrorAlreadyInitialized           = 1
	ForwarderErrorInvalidReport                = 2
	ForwarderErrorInvalidReportContext         = 3
	ForwarderErrorInvalidReportVersion         = 4
	ForwarderErrorFaultToleranceMustBePositive = 5
	ForwarderErrorExcessSigners                = 6
	ForwarderErrorInsufficientSigners          = 7
	ForwarderErrorInvalidConfig                = 8
	ForwarderErrorInvalidSignatureCount        = 9
	ForwarderErrorDuplicateSigner              = 10
	ForwarderErrorInvalidSignature             = 11
	ForwarderErrorInvalidSignerOrder           = 12
	ForwarderErrorAlreadyProcessed             = 13
	ForwarderErrorNotOwner                     = 14
	ForwarderErrorNotProposedOwner             = 15
	ForwarderErrorUninitialized                = 16
	ForwarderErrorUnauthorizedForwarder        = 17
	ForwarderErrorInvalidReceiver              = 18
	ForwarderErrorInvalidSigner                = 19
	ForwarderErrorCannotRemoveSelf             = 20
)

// ForwarderErrorMessage returns a human-readable message for error codes.
var ForwarderErrorMessage = map[int]string{
	1:  "already initialized",
	2:  "invalid report",
	3:  "invalid report context",
	4:  "invalid report version",
	5:  "fault tolerance must be positive",
	6:  "excess signers",
	7:  "insufficient signers",
	8:  "invalid config",
	9:  "invalid signature count",
	10: "duplicate signer",
	11: "invalid signature",
	12: "invalid signer order",
	13: "already processed",
	14: "not owner",
	15: "not proposed owner",
	16: "uninitialized",
	17: "unauthorized forwarder",
	18: "invalid receiver",
	19: "invalid signer",
	20: "cannot remove self",
}

// RoleGrantedEvent represents the RoleGrantedEvent event.
// Topics: [auth_RoleGranted]
type RoleGrantedEvent struct {
	Role    string
	Account string
	Sender  string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleGrantedEventTopic is the event topic identifier.
const RoleGrantedEventTopic = "auth_RoleGranted"

// RoleRevokedEvent represents the RoleRevokedEvent event.
// Topics: [auth_RoleRevoked]
type RoleRevokedEvent struct {
	Role    string
	Account string
	Sender  string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleRevokedEventTopic is the event topic identifier.
const RoleRevokedEventTopic = "auth_RoleRevoked"

// OwnershipTransferredEvent represents the OwnershipTransferredEvent event.
// Topics: [auth_OwnerTransferred]
type OwnershipTransferredEvent struct {
	PreviousOwner string
	NewOwner      string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferredEventTopic is the event topic identifier.
const OwnershipTransferredEventTopic = "auth_OwnerTransferred"

// AuthorizedCallerAddedEvent represents the AuthorizedCallerAddedEvent event.
// Topics: [auth_CallerAdded]
type AuthorizedCallerAddedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerAddedEventTopic is the event topic identifier.
const AuthorizedCallerAddedEventTopic = "auth_CallerAdded"

// AuthorizedCallerRemovedEvent represents the AuthorizedCallerRemovedEvent event.
// Topics: [auth_CallerRemoved]
type AuthorizedCallerRemovedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerRemovedEventTopic is the event topic identifier.
const AuthorizedCallerRemovedEventTopic = "auth_CallerRemoved"

// OwnershipTransferStartedEvent represents the OwnershipTransferStartedEvent event.
// Topics: [auth_OwnerTransferStart]
type OwnershipTransferStartedEvent struct {
	PreviousOwner string
	NewOwner      string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferStartedEventTopic is the event topic identifier.
const OwnershipTransferStartedEventTopic = "auth_OwnerTransferStart"

// ConfigSetEvent represents the ConfigSetEvent event.
// Topics: [forwarder_ConfigSet]
type ConfigSetEvent struct {
	DonId         uint32
	ConfigVersion uint32
	F             uint32
	Signers       [][32]byte
	// Event metadata
	Ledger uint32
	TxHash string
}

// ConfigSetEventTopic is the event topic identifier.
const ConfigSetEventTopic = "forwarder_ConfigSet"

// ForwarderAddedEvent represents the ForwarderAddedEvent event.
// Topics: [forwarder_ForwarderAdded]
type ForwarderAddedEvent struct {
	Forwarder string
	// Event metadata
	Ledger uint32
	TxHash string
}

// ForwarderAddedEventTopic is the event topic identifier.
const ForwarderAddedEventTopic = "forwarder_ForwarderAdded"

// ReportProcessedEvent represents the ReportProcessedEvent event.
// Topics: [forwarder_ReportProcessed]
type ReportProcessedEvent struct {
	Receiver            string
	WorkflowExecutionId [32]byte
	ReportId            [2]byte
	Success             bool
	// Event metadata
	Ledger uint32
	TxHash string
}

// ReportProcessedEventTopic is the event topic identifier.
const ReportProcessedEventTopic = "forwarder_ReportProcessed"

// ForwarderRemovedEvent represents the ForwarderRemovedEvent event.
// Topics: [forwarder_ForwarderRemoved]
type ForwarderRemovedEvent struct {
	Forwarder string
	// Event metadata
	Ledger uint32
	TxHash string
}

// ForwarderRemovedEventTopic is the event topic identifier.
const ForwarderRemovedEventTopic = "forwarder_ForwarderRemoved"

// SignatureVerificationConfig is a Soroban discriminated-union (#[contracttype] enum with payload(s)).
// Wire format: ScVal::Vec([ScVal::Symbol(<VariantName>), <payload fields...>]).
// Construct by setting exactly one variant pointer to a non-nil value.
type SignatureVerificationConfig struct {
	Threshold *SignatureVerificationConfigThreshold
	Failure   *SignatureVerificationConfigFailure
}

// SignatureVerificationConfigThreshold is the tuple variant SignatureVerificationConfig::Threshold.
type SignatureVerificationConfigThreshold struct {
	Field0 uint32
}

// SignatureVerificationConfigFailure is the tuple variant SignatureVerificationConfig::Failure.
type SignatureVerificationConfigFailure struct {
	Field0 uint32
}

// ToScVal converts SignatureVerificationConfig to its Soroban discriminated-union encoding.
// Returns an error if zero or multiple variant pointers are set.
func (e SignatureVerificationConfig) ToScVal() (xdr.ScVal, error) {
	set := 0
	if e.Threshold != nil {
		set++
	}
	if e.Failure != nil {
		set++
	}
	if set != 1 {
		return xdr.ScVal{}, fmt.Errorf("SignatureVerificationConfig: expected exactly one variant set, got %d", set)
	}
	if e.Threshold != nil {
		items := []xdr.ScVal{
			scval.SymbolToScVal("Threshold"),
			scval.Uint32ToScVal(e.Threshold.Field0),
		}
		return scval.VecToScVal(items), nil
	}
	if e.Failure != nil {
		items := []xdr.ScVal{
			scval.SymbolToScVal("Failure"),
			scval.Uint32ToScVal(e.Failure.Field0),
		}
		return scval.VecToScVal(items), nil
	}
	return xdr.ScVal{}, fmt.Errorf("SignatureVerificationConfig: unreachable")
}

// SignatureVerificationConfigFromScVal parses an xdr.ScVal into SignatureVerificationConfig.
func SignatureVerificationConfigFromScVal(val xdr.ScVal) (SignatureVerificationConfig, error) {
	vecPtr, ok := val.GetVec()
	if !ok || vecPtr == nil || *vecPtr == nil {
		return SignatureVerificationConfig{}, fmt.Errorf("expected vec for SignatureVerificationConfig enum")
	}
	vec := *vecPtr
	if len(vec) < 1 {
		return SignatureVerificationConfig{}, fmt.Errorf("SignatureVerificationConfig: empty vec")
	}
	tag, err := scval.SymbolFromScVal(vec[0])
	if err != nil {
		return SignatureVerificationConfig{}, fmt.Errorf("SignatureVerificationConfig: variant tag: %w", err)
	}
	switch tag {
	case "Threshold":
		if len(vec) != 2 {
			return SignatureVerificationConfig{}, fmt.Errorf("SignatureVerificationConfig::Threshold: expected 2 elements, got %d", len(vec))
		}
		payload := &SignatureVerificationConfigThreshold{}
		if v, ok := vec[1].GetU32(); ok {
			payload.Field0 = uint32(v)
		} else {
			return SignatureVerificationConfig{}, fmt.Errorf("SignatureVerificationConfig::Threshold[0]: expected u32")
		}
		return SignatureVerificationConfig{Threshold: payload}, nil
	case "Failure":
		if len(vec) != 2 {
			return SignatureVerificationConfig{}, fmt.Errorf("SignatureVerificationConfig::Failure: expected 2 elements, got %d", len(vec))
		}
		payload := &SignatureVerificationConfigFailure{}
		if v, ok := vec[1].GetU32(); ok {
			payload.Field0 = uint32(v)
		} else {
			return SignatureVerificationConfig{}, fmt.Errorf("SignatureVerificationConfig::Failure[0]: expected u32")
		}
		return SignatureVerificationConfig{Failure: payload}, nil
	default:
		return SignatureVerificationConfig{}, fmt.Errorf("SignatureVerificationConfig: unknown variant %q", tag)
	}
}

// DataKey is a Soroban discriminated-union (#[contracttype] enum with payload(s)).
// Wire format: ScVal::Vec([ScVal::Symbol(<VariantName>), <payload fields...>]).
// Construct by setting exactly one variant pointer to a non-nil value.
type DataKey struct {
	Forwarder    *DataKeyForwarder
	Config       *DataKeyConfig
	Transmission *DataKeyTransmission
}

// DataKeyForwarder is the tuple variant DataKey::Forwarder.
type DataKeyForwarder struct {
	Field0 string
}

// DataKeyConfig is the tuple variant DataKey::Config.
type DataKeyConfig struct {
	Field0 uint64
}

// DataKeyTransmission is the tuple variant DataKey::Transmission.
type DataKeyTransmission struct {
	Field0 [32]byte
}

// ToScVal converts DataKey to its Soroban discriminated-union encoding.
// Returns an error if zero or multiple variant pointers are set.
func (e DataKey) ToScVal() (xdr.ScVal, error) {
	set := 0
	if e.Forwarder != nil {
		set++
	}
	if e.Config != nil {
		set++
	}
	if e.Transmission != nil {
		set++
	}
	if set != 1 {
		return xdr.ScVal{}, fmt.Errorf("DataKey: expected exactly one variant set, got %d", set)
	}
	if e.Forwarder != nil {
		items := []xdr.ScVal{
			scval.SymbolToScVal("Forwarder"),
			scval.AddressToScVal(e.Forwarder.Field0),
		}
		return scval.VecToScVal(items), nil
	}
	if e.Config != nil {
		items := []xdr.ScVal{
			scval.SymbolToScVal("Config"),
			scval.Uint64ToScVal(e.Config.Field0),
		}
		return scval.VecToScVal(items), nil
	}
	if e.Transmission != nil {
		items := []xdr.ScVal{
			scval.SymbolToScVal("Transmission"),
			scval.Bytes32ToScVal(e.Transmission.Field0),
		}
		return scval.VecToScVal(items), nil
	}
	return xdr.ScVal{}, fmt.Errorf("DataKey: unreachable")
}

// DataKeyFromScVal parses an xdr.ScVal into DataKey.
func DataKeyFromScVal(val xdr.ScVal) (DataKey, error) {
	vecPtr, ok := val.GetVec()
	if !ok || vecPtr == nil || *vecPtr == nil {
		return DataKey{}, fmt.Errorf("expected vec for DataKey enum")
	}
	vec := *vecPtr
	if len(vec) < 1 {
		return DataKey{}, fmt.Errorf("DataKey: empty vec")
	}
	tag, err := scval.SymbolFromScVal(vec[0])
	if err != nil {
		return DataKey{}, fmt.Errorf("DataKey: variant tag: %w", err)
	}
	switch tag {
	case "Forwarder":
		if len(vec) != 2 {
			return DataKey{}, fmt.Errorf("DataKey::Forwarder: expected 2 elements, got %d", len(vec))
		}
		payload := &DataKeyForwarder{}
		if v, err := scval.AddressFromScVal(vec[1]); err != nil {
			return DataKey{}, fmt.Errorf("DataKey::Forwarder[0]: %w", err)
		} else {
			payload.Field0 = v
		}
		return DataKey{Forwarder: payload}, nil
	case "Config":
		if len(vec) != 2 {
			return DataKey{}, fmt.Errorf("DataKey::Config: expected 2 elements, got %d", len(vec))
		}
		payload := &DataKeyConfig{}
		if v, err := scval.Uint64FromScVal(vec[1]); err != nil {
			return DataKey{}, fmt.Errorf("DataKey::Config[0]: %w", err)
		} else {
			payload.Field0 = v
		}
		return DataKey{Config: payload}, nil
	case "Transmission":
		if len(vec) != 2 {
			return DataKey{}, fmt.Errorf("DataKey::Transmission: expected 2 elements, got %d", len(vec))
		}
		payload := &DataKeyTransmission{}
		if v, err := scval.Bytes32FromScVal(vec[1]); err != nil {
			return DataKey{}, fmt.Errorf("DataKey::Transmission[0]: %w", err)
		} else {
			payload.Field0 = v
		}
		return DataKey{Transmission: payload}, nil
	default:
		return DataKey{}, fmt.Errorf("DataKey: unknown variant %q", tag)
	}
}

// TransmissionState represents the TransmissionState enum (unit-only Soroban contracttype, encoded as ScVal::U32).
type TransmissionState uint32

const (
	TransmissionStateNotAttempted    TransmissionState = 0
	TransmissionStateSucceeded       TransmissionState = 1
	TransmissionStateInvalidReceiver TransmissionState = 2
	TransmissionStateFailed          TransmissionState = 3
)

// ToScVal converts TransmissionState to an xdr.ScVal.
func (e TransmissionState) ToScVal() (xdr.ScVal, error) {
	return scval.Uint32ToScVal(uint32(e)), nil
}

// TransmissionStateFromScVal parses an xdr.ScVal into TransmissionState.
func TransmissionStateFromScVal(val xdr.ScVal) (TransmissionState, error) {
	v, ok := val.GetU32()
	if !ok {
		return 0, fmt.Errorf("expected u32 for TransmissionState enum")
	}
	return TransmissionState(v), nil
}
