name: Go Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/smartcontractkit/*
      GONOSUMCHECK: github.com/smartcontractkit/*
    steps:
      - name: Setup GitHub Token
        uses: smartcontractkit/.github/actions/setup-github-token@ef78fa97bf3c77de6563db1175422703e9e6674f # setup-github-token@0.2.1
        with:
          aws-role-arn: ${{ secrets.GATI_AWS_ROLE_ARN_CHAINLINK_READ_ONLY }}
          aws-lambda-url: ${{ secrets.GATI_LAMBDA_URL_RELENG }}
          aws-region: ${{ secrets.GATI_AWS_REGION }}
          set-git-config: true

      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          cache: true
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run unit tests
        run: go test -v -race -fullpath -shuffle on -coverprofile=coverage.out ./...

      - name: Display coverage
        if: always()
        run: |
          if [ -f coverage.out ]; then
            go tool cover -func=coverage.out | tail -1
          fi
